### ISSUE TITLE
Moving inferred classification to imports

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12315]
Move all inferred classification to an imported file and switch to flush and replace for inference.  Editors will be able to check the results of edits by running existing reports.

Tasks:

* Review & clean up classifications marked: EXISTS, TAGGED-INFERRED, NOT-ENTAILED (ETINE) 
   - [x] Make tsv for review: [etines.tsv](https://github.com/geneontology/go-ontology/blob/master/refactoring_inference_pipeline/etines.tsv).  Columns: class_id, class_name, superclass_id, superclass_name, status (1/0), manual (1/0), Entailed - checked in protege (1/0),	Redundant (1/0), Fixed (1/0), Notes (free text)
  - [x] Review  - following [strategy doc](https://github.com/geneontology/go-ontology/blob/master/refactoring_inference_pipeline/README.md)

**Comment by cmungall** [comment]
Did we decide on how to handle this in the context of OE import behavior?

**Comment by dosumis** [comment]
We should be able to use a filtered save with a link filter - in addition to the term filter on ID we currently use to save only GO terms:

![image](https://cloud.githubusercontent.com/assets/112839/13503464/701cc56e-e167-11e5-9320-695aea4a729e.png)

**Comment by cmungall** [comment]
Changes to inference pipeline:

 - [ ] Move (tagged) inferred classifications to an imported file https://github.com/ontodev/robot/issues/66
 - [ ] Ensure  classifications are tagged https://github.com/ontodev/robot/issues/67
 - [ ] Turn on flush and replace (@dosumis, what is this exactly?)
 - [ ] switch off assertion in TG (or TBD: change TG architecture)
 - [ ] sign off from all editors that they have updated their OE config
 - [ ] create jenkins job replacing build.berkeleybop.org/view/GO/job/build-go-assert-inferences
     - TBD: run with every commit?
 - [ ] ensure redundant axioms are only removed from release files, never editors: https://github.com/ontodev/robot/issues/16




https://github.com/ontodev/robot/issues/67

**Comment by cmungall** [comment]
This is the diff when we remove the S=1 M=1 etines:

```
[Term]
id: GO:0000237 ! leptotene
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0000238 ! zygotene
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0000239 ! pachytene
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0000240 ! diplotene
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0000241 ! diakinesis
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0000758 ! agglutination involved in conjugation with mutual genetic exchange
-is_a: GO:0000771 {is_inferred="true"} ! agglutination involved in conjugation

[Term]
id: GO:0000914 ! phragmoplast assembly
-is_a: GO:1902407 {is_inferred="true"} ! assembly of actomyosin apparatus involved in mitotic cytokinesis

[Term]
id: GO:0006286 ! base-excision repair, base-free sugar-phosphate removal
-is_a: GO:0098502 {is_inferred="true"} ! DNA dephosphorylation

[Term]
id: GO:0006853 ! carnitine shuttle
-is_a: GO:1990542 {is_inferred="true"} ! mitochondrial transmembrane transport

[Term]
id: GO:0007042 ! lysosomal lumen acidification
-is_a: GO:0007035 {is_inferred="true"} ! vacuolar acidification

[Term]
id: GO:0007128 ! meiotic prophase I
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0007132 ! meiotic metaphase I
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0007134 ! meiotic telophase I
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:0008320 ! protein transmembrane transporter activity
-is_a: GO:0022884 {is_inferred="true"} ! macromolecule transmembrane transporter activity

[Term]
id: GO:0008979 ! prophage integrase activity
-is_a: GO:0008907 {is_inferred="true"} ! integrase activity

[Term]
id: GO:0015557 ! arginine targeting transmembrane transporter activity
-is_a: GO:0008320 {is_inferred="true"} ! protein transmembrane transporter activity

[Term]
id: GO:0019538 ! protein metabolic process
-is_a: GO:0043170 {is_inferred="true"} ! macromolecule metabolic process

[Term]
id: GO:0021784 ! postganglionic parasympathetic fiber development
-is_a: GO:0048483 {is_inferred="true"} ! autonomic nervous system development

[Term]
id: GO:0030163 ! protein catabolic process
-is_a: GO:0009057 {is_inferred="true"} ! macromolecule catabolic process

[Term]
id: GO:0042740 ! exogenous antibiotic catabolic process
-is_a: GO:0017001 {is_inferred="true"} ! antibiotic catabolic process

[Term]
id: GO:0043690 ! cell-cell adhesion involved in flocculation via cell wall protein-carbohydrate interaction
-is_a: GO:0043689 {is_inferred="true"} ! cell-cell adhesion involved in flocculation

[Term]
id: GO:0043707 ! cell adhesion involved in single-species biofilm formation in or on host organism
-is_a: GO:0043709 {is_inferred="true"} ! cell adhesion involved in single-species biofilm formation

[Term]
id: GO:0044844 ! meiotic interphase II
-is_a: GO:0051328 {is_inferred="true"} ! meiotic interphase
-is_a: GO:0098765 {is_inferred="true"} ! meiosis II cell cycle phase

[Term]
id: GO:0045476 ! nurse cell apoptotic process
-is_a: GO:0003006 {is_inferred="true"} ! developmental process involved in reproduction

[Term]
id: GO:0050892 ! intestinal absorption
-is_a: GO:0022600 {is_inferred="true"} ! digestive system process

[Term]
id: GO:0060136 ! embryonic process involved in female pregnancy
-is_a: GO:0048609 {is_inferred="true"} ! multicellular organismal reproductive process

[Term]
id: GO:0060530 ! smooth muscle cell differentiation involved in prostate glandular acinus development
-is_a: GO:0003006 {is_inferred="true"} ! developmental process involved in reproduction

[Term]
id: GO:0060706 ! cell differentiation involved in embryonic placenta development
-is_a: GO:0003006 {is_inferred="true"} ! developmental process involved in reproduction

[Term]
id: GO:0060742 ! epithelial cell differentiation involved in prostate gland development
-is_a: GO:0003006 {is_inferred="true"} ! developmental process involved in reproduction

[Term]
id: GO:0061009 ! common bile duct development
-is_a: GO:0035295 {is_inferred="true"} ! tube development

[Term]
id: GO:0061691 ! detoxification of hydrogen peroxide
-is_a: GO:0042743 {is_inferred="true"} ! hydrogen peroxide metabolic process

[Term]
id: GO:0071050 ! snoRNA polyadenylation
-is_a: GO:0031126 {is_inferred="true"} ! snoRNA 3'-end processing

[Term]
id: GO:0072520 ! seminiferous tubule development
-is_a: GO:0035295 {is_inferred="true"} ! tube development

[Term]
id: GO:0080162 ! intracellular auxin transport
-is_a: GO:0060919 {is_inferred="true"} ! auxin influx

[Term]
id: GO:0098765 ! meiosis II cell cycle phase
-is_a: GO:0098762 {is_inferred="true"} ! meiotic cell cycle phase

[Term]
id: GO:0098768 ! meiotic prometaphase I
-is_a: GO:0098764 {is_inferred="true"} ! meiosis I cell cycle phase

[Term]
id: GO:1901487 ! negative regulation of SREBP signaling pathway by positive regulation of transcription factor catabolic process in response to increased oxygen levels
-is_a: GO:1901486 {is_inferred="true"} ! negative regulation of SREBP signaling pathway by positive regulation of transcription factor catabolic process

[Term]
id: GO:1901619 ! tRNA methylation in response to nitrogen starvation
-is_a: GO:0030488 {is_inferred="true"} ! tRNA methylation

[Term]
id: GO:1902178 ! fibroblast growth factor receptor apoptotic signaling pathway
-is_a: GO:0008543 {is_inferred="true"} ! fibroblast growth factor receptor signaling pathway

[Term]
id: GO:1903445 ! protein transport from ciliary membrane to plasma membrane
-is_a: GO:0015031 {is_inferred="true"} ! protein transport
-is_a: GO:0090002 {is_inferred="true"} ! establishment of protein localization to plasma membrane
```

**Comment by cmungall** [comment]
TG now no longer asserts inferences.

As a test I added this:

```
[Term]
id: GO:1905270
name: Meynert cell differentiation
namespace: biological_process
def: "The process in which a relatively unspecialized cell acquires the specialized features of a Meynert cell." [GO_REF:0000086, GOC:TermGenie, PMID:4142639]
intersection_of: GO:0030154 ! cell differentiation
intersection_of: results_in_acquisition_of_features_of CL:2000056 ! Meynert cell
created_by: cjm
creation_date: 2016-06-15T23:44:17Z
```

As expected, this is in GO without any is_as. In the inferred file we expect this to be intermediate between two existing classes

As expected, Jenkins redballs due to apparent isa-incompleteness. The pipeline is now changed so this is allowed in editors.

**Comment by cmungall** [comment]
Everyone should also confirm they see this in P5:

<img width="1418" alt="screen shot 2016-06-15 at 6 07 05 pm" src="https://cloud.githubusercontent.com/assets/50745/16102407/01eff55c-3324-11e6-8330-21bf49ed3000.png">

 - [ ] @dosumis 
 - [ ] @mcourtot 
 - [ ] @paolaroncaglia 
 - [ ] @tberardini 
 - [ ] @ukemi

**Comment by dosumis** [comment]
I just realised the file on the repo is out of date, did you commit changes to the trunk?  5' job to update.   Sorry!!!

**Comment by paolaroncaglia** [comment]
Mentioning @rebeccafoulger too as she also does some editing.

**Comment by tberardini** [comment]
Trying to view in Protege (admittedly, I'm still on v. 4.3) but using the same URL as in your screenshot, I ended up loading purl.obolibrary.org/obo/go/releases/2016-06-15/go.owl, and do not get the same view
<img width="1274" alt="screen shot 2016-06-17 at 11 04 04 am" src="https://cloud.githubusercontent.com/assets/4998871/16160125/3f632014-347b-11e6-96e1-71185021c9ec.png">
.  Am I not seeing the equivalence axioms and inferred parentage because of the Protege 4.3 version or because the go.owl version didn't have the data?

**Comment by cmungall** [comment]
@tberardini that's expected behavior for the public PURL

But as an editor you would have the repo checked out and open gene_ontology_write.obo directly in Protege

Of course you can't open obo in p4, so everyone should erase p4 from their hard drives :-)
