### ISSUE TITLE
erroneous links involving spindle pole body terms

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#12761]
I've just noticed that GO has links that imply that the spindle pole body (SPB) is part of the spindle, but this is not always true. When a spindle exists, the SPB is indeed part of the spindle pole, and therefore part of the spindle, but the SPB is present throughout the cell cycle and therefore also exists at times when there is no spindle.

Selected tags from the relevant OBO stanzas:

```
id: GO:0005816
name: spindle pole body
def: "The microtubule organizing center in fungi; functionally homologous to the animal cell centrosome." [ISBN:0879693568]
is_a: GO:0005815 ! microtubule organizing center
relationship: part_of GO:0000922 ! spindle pole

id: GO:0044732
name: mitotic spindle pole body
def: "The microtubule organizing center on a spindle that forms as part of mitosis; functionally homologous to the animal cell centrosome." [GOC:vw]
is_a: GO:0005816 ! spindle pole body
relationship: part_of GO:0072686 ! mitotic spindle

id: GO:0035974
name: meiotic spindle pole body
def: "The microtubule organizing center on a spindle that forms as part of meiosis; functionally homologous to the animal cell centrosome." [GOC:vw, PMID:21775631]
is_a: GO:0005816 ! spindle pole body
relationship: part_of GO:0072687 ! meiotic spindle
```

To fix, remove the asserted part_of links from all three, and change the text defs of GO:0035974 and GO:0044732 to use "forms as part of the mitotic|meiotic cell cycle".

I'm guessing that one ore more of the CC links is/are what causes this link to be inferred in BP, which is also not always true:

```
id: GO:1902440
name: protein localization to mitotic spindle pole body
is_a: GO:1902480 {is_inferred="true"} ! protein localization to mitotic spindle
```

It would probably be worth checking to make sure that link is no longer inferred (or investigating where it's coming from, if not from links in CC).

**Comment by tberardini** [comment]
I'm thinking about how to fix the relationship/s in the cc part of the ontology.  Does this make sense?

spindle
has_part: spindle pole

vs.

spindle
part_of: spindle pole

Whenever the spindle exists, it has part spindle pole (and therefore spindle pole body).

Or 

spindle pole
has_part spindle pole body

vs.

spindle pole
part_of spindle pole body

Looks like some tidying should be done under spindle pole.  Let's get this right.

**Comment by mah11** [comment]
Hang on, now I'm confused about which way round to read these snippets. If we're reading bottom-up, this is backwards:

> spindle
> has_part: spindle pole

But the text underneath is correct, except for the part in parentheses:

> Whenever the spindle exists, it has part spindle pole. [only true if the sentence ends here]

These are true, logically and biologically, if read bottom-up:

> spindle pole
> has_part: spindle
> 
> spindle
> part_of: spindle pole

Or, putting each on one line to read like normal prose,

    spindle has_part spindle pole
    spindle pole part_of spindle

Every spindle has spindle poles, and every spindle pole is part of some spindle.


But my problem is with the spindle pole _body_ terms. These are all logically false (again, just on one line to read left-to-right):

> spindle pole has_part spindle pole body

This is always true in fungi, but not in other taxa. Other species have functionally equivalent, but structurally different, microtubule organizing centers at their spindle poles (e.g. animals have centrioles).

> spindle pole body part_of spindle pole

This is the problem! It's not always true because -- despite its name -- the spindle pole body does not require a spindle pole to be part of. When there is a spindle, that spindle has poles and the poles contain the spindle pole bodies, BUT the cell always has at least one spindle pole body, even when there's no spindle present (i.e. in the other phases of the cell cycle).

> spindle pole body has_part spindle pole
> spindle pole part_of spindle pole body

These are backwards because the spindle pole is the bigger thing, and the spindle pole body is (sometimes) the part.

**Comment by tberardini** [comment]
Ok.  @mah11: please review

- [ ] deep six (and not create) ANY part_of/has_part relationships between 'spindle pole body' and 'spindle pole' terms AND 'spindle pole body' and 'spindle' terms in cc.

- [ ] make sure the relationships between spindle and spindle pole are
  spindle has_part spindle pole
  spindle pole part_of spindle

- [ ] change the text defs of GO:0035974 and GO:0044732 to use "forms as part of the mitotic|meiotic cell cycle".

- [ ] after edits, check that the BP inference below goes away

  id: GO:1902440
  name: protein localization to mitotic spindle pole body
  is_a: GO:1902480 {is_inferred="true"} ! protein localization to mitotic spindle

**Comment by mah11** [comment]
Yes to all of those. Thanks!

**Comment by tberardini** [comment]
For spindle /spindle pole, I kept the spindle pole part_of spindle and didn't add splindle has_part spindle pole because I didnt want to muck things up with two different relationships between the same two terms.

 id: GO:0035974
 name: meiotic spindle pole body
-def: "The microtubule organizing center **on a spindle** that forms as part of meiosis; functionally homologous to the animal cell centrosome." [GOC:vw, PMID:21775631]
+def: "The microtubule organizing center that forms as part of t**he meiotic cell cycle**; functionally homologous to the animal cell centrosome." [GOC:vw, PMID:21775631]
-relationship: part_of GO:0072687 ! meiotic spindle

 id: GO:0044732
 name: mitotic spindle pole body
-def: "The microtubule organizing center **on a spindle** that forms as part of mitosis; functionally homologous to the animal cell centrosome." [GOC:vw]
+def: "The microtubule organizing center that forms as part of **the mitotic cell cycle**; functionally homologous to the animal cell centrosome." [GOC:mah, GOC:vw]
-relationship: part_of GO:0072686 ! mitotic spindle

spindle pole body
-relationship: part_of GO:0000922 ! spindle pole


Going to wait and see what happens with inferred BP link before I close this.

**Comment by mah11** [comment]
> For spindle /spindle pole, I kept the spindle pole part_of spindle and didn't add splindle has_part spindle pole because I didnt want to muck things up with two different relationships between the same two terms.

That's fine by me - both are technically true, but the part_of link is much more useful for annotation propagation, and it would be a bit fussy to include both even if it didn't muck anything up.

Thanks!

**Comment by tberardini** [comment]
Ok!  Those inferred links are now gone.  
 
[Term]
 id: GO:1902440 ! protein localization to mitotic spindle pole body
-is_a: GO:1902480 {is_inferred="true"} ! protein localization to mitotic spindle
 is_a: GO:1905508 {is_inferred="true"} ! protein localization to microtubule organizing center
 
 [Term]
 id: GO:1902441 ! protein localization to meiotic spindle pole body
 is_a: GO:0022414 {is_inferred="true"} ! reproductive process
-is_a: GO:1905359 {is_inferred="true"} ! protein localization to meiotic spindle
 is_a: GO:1905508 {is_inferred="true"} ! protein localization to microtubule organizing center

Closing.
