### ISSUE TITLE
MP microtubule severing/ parentage, F-P link

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13968]
GO:0051013  microtubule severing
The process in which a microtubule is broken down into smaller segments. 

 I'm not sure if this should be in the process ontology, but since it is can we:

- [x]  Make "microtubule cytoskeleton organization a parent"
(at present it has only "microtubule-based process, a less specific term which includes transport along microtubules.
- [x]  Make a  F-P link between  
GO:0008568 | microtubule-severing ATPase activity
- [x] The ref for GO:0051013  is about actin severing....

**Comment by ValWood** [comment]
A review https://www.ncbi.nlm.nih.gov/pubmed/27037673 to replace existing ref

**Comment by pgaudet** [comment]
Hello, 

I changed the parent of GO:0051013 microtubule severing 
OLD: is_a: GO:0007017 ! microtubule-based process
NEW: GO:0000226 ! microtubule cytoskeleton organization

And updated the definition and reference:

OLD: def: "The process in which a microtubule is broken down into smaller segments." [GOC:ai, PMID:14657234]
NEW: "The process in which a microtubule is broken down into smaller segments. Severing enzymes remove dimers from the middle of the filament to create new ends, unlike depolymerizing kinesins that use ATP to uncap microtubules at their ends" [GOC:ai, PMID:27037673]

Pascale
