### ISSUE TITLE
NTR: missing parent term -neuron projection cytoplasm

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14472]
Could I request a gap-filler term?

neuron projection cytoplasm:
Is_a cell projection cytoplasm GO:0032838
part_of neuron projection GO:0043005

and place all cell projection cytoplasm GO:0032838 children under neuron projection cytoplasm

GO:1904115 axon cytoplasm
GO:0032839	dendrite cytoplasm
GO:0071598 neuronal ribonucleoprotein granule (note: this has a part_of relationship)

neuron projection cytoplasm definition:All of the contents of a plasma membrane bounded neuron projection, excluding the plasma membrane surrounding the projection.

**Comment by krchristie** [comment]
- [ ] New term for "neuron projection cytoplasm
- [ ] changed logical defs/relationships for "GO:1904115 axon cytoplasm" & "GO:0032839 dendrite cytoplasm" to be types of "neuron projection cytoplasm" instead of "cell projection cytoplasm"
- [ ] changed some relationships of "GO:0071598 neuronal ribonucleoprotein granule"

**Comment by krchristie** [comment]
@hattrill - I assumed that GOC:ha was the appropriate reference to credit you with the definition. If that is incorrect, let me know what the correct one is so I can fix it.

**Comment by hattrill** [comment]
Thanks - that's all good for me.
