### ISSUE TITLE
MP  plasma membrane fusion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15939]
GO:0045026 plasma membrane fusion
https://www.ebi.ac.uk/QuickGO/term/GO:0045026

missing parent

GO:0007009 plasma membrane organization
https://www.ebi.ac.uk/QuickGO/term/GO:0007009

Isn't the reasoner working?

**Comment by pgaudet** [comment]
Nothing is a quick fix :( 
Once again this is caused by logical definitions. To fix I need to understand what the terms really mean. 

* What is 'plasma membrane fusion'? The definition states "The joining of two or more lipid bilayer membranes that surround a cell." (no reference). 
* However GO:0099500 vesicle fusion to plasma membrane is a child, which seems inconsistent (since we're not only fusing plasma membranes anymore).
* Looking at some annotations, it seems like what is mean is 'cell fusion' . The closest term is 'GO:0000768 syncytium formation by plasma membrane fusion' 

So I would lean towards
 - [ ]  renaming GO:0045026 plasma membrane fusion 
 - [ ]  making it a parent of GO:0000768 syncytium formation by plasma membrane fusion
 - [ ]  These children terms would be OK under the same parentage: 
- 'fusion of sperm to egg plasma membrane involved in double fertilization forming a zygote and endosperm'
'- fusion of sperm to egg plasma membrane involved in double fertilization forming two zygotes'
- 'fusion of sperm to egg plasma membrane involved in single fertilization'
- 'plasma membrane fusion involved in cytogamy'
 - [ ]  Need to be rehoused: 
 - 'synaptic vesicle fusion to presynaptic active zone membrane'
' - vesicle fusion to plasma membrane'
 - [ ]  Not sure: 
- 'midbody abscission'? Seems to be a step in cytokinesis, see the reference cited (PMID:12737809): no annotations; related to mitotic cleavage furrow ingression ? 


MGI, WormBase, UniProt have EXP annotations - @ukemi @vanaukenk @ggeorghiou @sylvainpoux your input would be welcome !

Thanks, Pascale

**Comment by pgaudet** [comment]
added to editors-discussion for feedback.

**Comment by ValWood** [comment]
Instead of
 renaming GO:0045026 plasma membrane fusion -> cell fusion

create a new term cell-cell fusion

cell-cell fusion
--plasma membrane fusion involved in cytogamy
--syncytium formation by plasma membrane fusion

membrane fusion
--plasma membrane fusion
--

**Comment by pgaudet** [comment]
Also, can we change the definition to state that the fusion is between plasma membranes of *different* cells? Are there examples of a plasma membrane fusing with itself?

**Comment by pgaudet** [comment]
@ValWood I just noticed: 

GO:0000768 Syncytium formation has definition: The formation of a syncytium, a mass of cytoplasm containing several nuclei enclosed within a single plasma membrane, by the fusion of the plasma membranes of two or more individual cells.
and exact synonym: cell-cell fusion. 

But cell-cell fusion may also form a mononucleated cell (@ValWood can you provide a reference?) 
So I will remove the synonym. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 
I can't find 'plasma membrane fusion involved in conjugation with cellular fusion' 
only 'plasma membrane organization involved in conjugation with cellular fusion' (GO:0070872); 0 annotations. 

Should I just rename ?

**Comment by pgaudet** [comment]
@ValWood 
Shouldn't 'karyogamy involved in involved in conjugation with cellular fusion' be a child of karyogamy only?

**Comment by pgaudet** [comment]
Current state of these branches of the ontology: 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/4782928/44053482-0cb36c96-9f40-11e8-81ca-3c41362dffa3.png">

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140253
+name: cell-cell fusion
+namespace: biological_process
+def: "A cellular process in which two or more cells combine together, they plasma mebrane fusing, to produce a single cell. In some cases, nuclei fuse, producing a multiploid cell, while in other cases, nuclei remain separate, producing a syncytium." [Wikipedia:Cell_fusion]
+synonym: "cell cell fusion" EXACT []
+synonym: "cell fusion" BROAD []
+is_a: GO:0009987 ! cellular process
+relationship: has_part GO:0045026 ! plasma membrane fusion
+created_by: pg
+creation_date: 2018-08-13T18:38:18Z

**Comment by ValWood** [comment]
> But cell-cell fusion may also form a mononucleated cell (@ValWood can you provide a reference?)
So I will remove the synonym.

this is an example of cell-cell fusion forming a nucleated cell:
https://www.ncbi.nlm.nih.gov/pubmed?holding=pombase&term=29134248

**Comment by ValWood** [comment]
> I can't find 'plasma membrane fusion involved in conjugation with cellular fusion'
only 'plasma membrane organization involved in conjugation with cellular fusion' (GO:0070872); 0 annotations.

Odd that we haven't used that for the dni1 paper, but yes I think you can rename

**Comment by ValWood** [comment]
> Shouldn't 'karyogamy involved in involved in conjugation with cellular fusion' be a child of karyogamy only?

current parentage seems correct to me. It is a descendant of both "conjugation, and karyogamy'. Not all karyogamy occurs in the context of conjugation.

**Comment by ValWood** [comment]
note:

typos within
+def: "A cellular process in which two or more cells combine together, they plasma mebrane fusing, to produce a single cell. In some cases, nuclei fuse, producing a multiploid cell, while in other cases, nuclei remain separate, producing a syncytium." [Wikipedia:Cell_fusion]

they
mebrane

**Comment by mah11** [comment]
> > Shouldn't 'karyogamy involved in involved in conjugation with cellular fusion' be a child of karyogamy only?
> 
> current parentage seems correct to me. It is a descendant of both "conjugation, and karyogamy'. Not all karyogamy occurs in the context of conjugation.

I agree. GO:0000742 is a type of karyogamy (is_a GO:0000741) and part of a type of conjugation (part_of GO:0000747). It is true that I don't see any other suitable _is_a_ parent for GO:0000742.

**Comment by mah11** [comment]
re def typos - usually "polyploid" rather than "multiploid", too

**Comment by mah11** [comment]
> I can't find 'plasma membrane fusion involved in conjugation with cellular fusion'
only 'plasma membrane organization involved in conjugation with cellular fusion' 

This is a bit odd, and I don't remember why it was done this way (I added the PM fusion term here, but almost certainly following advice from someone else):

![go_32220](https://user-images.githubusercontent.com/5196259/44096605-99beb102-9fd3-11e8-990a-e70869ab7802.png)


It's GO:0032220 part_of GO:0000755
and GO:0032220 is_a GO:0045026
and GO:0000755 part_of GO:0000747

**Comment by mah11** [comment]
... so I think you could either add the link GO:0032220 is_a GO:0070872, or merge them. I don't know offhand if there's any PM organization other than fusion involved in this kind of conjugation.

**Comment by ValWood** [comment]
> I don't know offhand if there's any PM organization other than fusion involved in this kind of conjugation.

I wasn't sure. I guess there is organization during shmooing?
So  best to  keep both terms, properly connected

**Comment by hdrabkin** [comment]
id: GO:0140253  name: cell-cell fusion

I cannot find this in a fresh pull; was this actually committed and merged??

**Comment by pgaudet** [comment]
@hdrabkin it's not yet merged; I stilll need to read and address comments: 
https://github.com/geneontology/go-ontology/pull/16242/commits/b8893b6523175810b9566838868d8304447e9d1f
