### ISSUE TITLE
2 small fixes in pathogen host branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17441]
![tmep](https://user-images.githubusercontent.com/7359272/58830580-8fcc3880-8642-11e9-81de-bd1f05550d4b.jpg)

add
- [x] 
GO:0044068    modulation by symbiont of host cellular process
as a parent of
GO:0052552    modulation by organism of immune response of other organism involved in symbiotic interaction

- [x] and rename to
GO:0052552    modulation by symbiont  of host immune response  

i.e now it will be named like the descendant term
GO:0075528    modulation by virus of host immune response

**Comment by ValWood** [comment]
Hang on
GO:0052553    modulation by symbiont of host immune response
already exists!

defined
Any process in which an organism modulates the frequency, rate or extent of the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction.

GO:0052552 modulation by organism of immune response of other organism involved in symbiotic interaction
is defined
Any process in which an organism modulates the frequency, rate or extent of the immune response of a second organism, where the two organisms are in a symbiotic interaction. The immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat.

these terms mean exactly the same  don't they? or am I missing something?

**Comment by ukemi** [comment]
Not my field of expertise, but it seems to me that 553 is more specific in that it specifies the host response. 552 can be either organism in the symbiotic relationship.

**Comment by ValWood** [comment]
I don't understand? If an organism is regulating the host immune response it must be a symbiont?
No?

**Comment by ValWood** [comment]
The children of the parent term are


GO:0052555    positive regulation by organism of immune response of other organism involved in symbiotic interaction | is_a
-- | --
GO:0052283    modulation by organism of jasmonic acid-mediated defense response of other organism involved in symbiotic interaction | is_a
GO:0052294    modulation by organism of cell-mediated immune response of other organism involved in symbiotic interaction | is_a
GO:0052304    modulation by organism of phytoalexin production in other organism involved in symbiotic interaction | is_a
GO:0052553    modulation by symbiont of host immune response | is_a
GO:0052306    modulation by organism of innate immune response in other organism involved in symbiotic interaction | is_a
GO:0052293    modulation by organism of B-cell mediated immune response of other organism involved in symbiotic interaction | is_a
GO:0052561    negative regulation by organism of immune response of other organism involved in symbiotic interaction | is_a
GO:0052299    modulation by organism of systemic acquired resistance in other organism involved in symbiotic interaction | is_a
GO:0052302    modulation by organism of defense-related nitric oxide production in other organism involved in symbiotic interaction



Some of these should move up to be children of the grand parent "defense response" term (if they are required. Others should move down to be *under* the "immune system process" term, that should only leave "regulation" (although I am slightly struggling with the use of "modulation" vs "regulation" in this branch. But essentially I'm sure these 2 terms are equivalent.

**Comment by addiehl** [comment]
Not sure how modulation of another organism's immune response is an immune system process.  The immune system is an integrated biological system of a single organism, not an amalgamation of the processes of two organisms.

**Comment by ValWood** [comment]
by "under the immune system process term" I am referring to

GO:0052553 modulation by symbiont of host immune response
as opposed to  the current parent
GO:0052031  modulation by symbiont of host defense response

**Comment by addiehl** [comment]
Thanks for the clarification.  Your suggestion makes sense now.

**Comment by ValWood** [comment]
Sorry I should have spelled it out! I was using *shorthand* for the context of the term in question ;)

**Comment by pgaudet** [comment]
> If an organism is regulating the host immune response it must be a symbiont?

Right !! That's why I am proposing to merge many of the 'triad' terms. 
@mgiglio99 do you have examples of host mediating the symbiont's immune response ? 

This whole branch (GO:0052552 and children) seems like it only applies to host. 

Let me know - I can start merging. 

Thanks, Pascale

**Comment by ukemi** [comment]
anemonefish? Does the anemone influence their resistance to the nematocyst poison?

**Comment by pgaudet** [comment]
Is resistance to poison an immune response ?

**Comment by mgiglio99** [comment]
I don't have any examples of a host modulating a symbiont's immune system, but that's likely because I  know mostly about microbe symbionts which only have innate immune systems. But there are multicellular symbionts. Has anything come up like this in the pathogenic nematodes that wormbase might know about?  I know very little about immune system stuff.

**Comment by ValWood** [comment]
We shouldn't  include this if we don't have any examples.

How are we defining the symbiont "immune system"? 
The GO def is quite vague (or at least to me difficult to distinguish from defense response"
Any process involved in the development or functioning of the immune system, an organismal system for calibrated responses to potential internal or invasive threats.

I don't  know of any examples in plants of the host modulating the symbiont in a direct way. Plant mount responses to pathogen defences mechanism (for example the hypesensitive cell death response to inhibit pathogen growth), but we wouldn't really refer to the processes as modulating the "pathogen immune system". However, as I say, I don't really know what would be classed as a "pathogen immune system".  I haven't seen fungal defences referred to as "immune system". If we had examples of fungal defences that are classified as "immune system" it would help us to  nail down the bondaries of the  immune system definiton.

So what is the minimal requirement for "immune system" classification?

**Comment by ValWood** [comment]
Wikipedia begins
"The immune system is a host defense system"
which might help to get around may problems.....

**Comment by ValWood** [comment]
@addiehl do you think we can make the "immune system" definition clearer? Is the def necessary and sufficient?

**Comment by ValWood** [comment]
but  even the current def  seems to rule out:
host mediating the symbiont's immune response

"calibrated responses to potential internal or invasive threats" 

because the host isn't  internal to or invading the pathogen?

**Comment by addiehl** [comment]
Do we have a single example of a host mediating or modulating a symbiont's immune response?  If not, let's not get hung up on this point.

The general wording of the definitions of 'immune system process' and 'immune response' were intended to include regulatory immune responses, where one branch of the immune controls the magnitude of the response of another branch to a common threat or antigen, for instance the role of regulatory T cell responses tamping down the activity of effector T cells and neutrophils to prevent excess collateral damage or uncontrolled autoimmune responses (an uncontrolled immune response represents an internal threat).

**Comment by pgaudet** [comment]
Discussed with @mgiglio99 , and we decided that for 
GO:0052564 'response to immune response of other organism involved in symbiotic interaction'
and children, we will merge all the term pairs such as 
[1] 'active evasion of immune response of other organism involved in symbiotic interaction'
[2] 'active evasion of host immune response'
into the most precise term (in this case, [2]). 

I'll list the merges in the next comment. 

Pascale

**Comment by pgaudet** [comment]
- [x] 'GO:0051812 active evasion of host immune response via regulation of host cytokine network' (0 annotations)
-> merge into
'GO:0042785 active evasion of immune response of other organism via regulation of cytokine network of other organism involved in symbiotic interaction'

- [x] GO:0051811 active evasion of immune response of other organism via regulation of complement system of other organism involved in symbiotic interaction (0 annotations)
into GO:0042784 active evasion of host immune response via regulation of host complement system

- [x]  GO:0051810 'active evasion of immune response of other organism involved in symbiotic interaction' (0 annotations)
into GO:0042783 'active evasion of host immune response'

-  [x] ' GO:0051813  active evasion of immune response of other organism via regulation of antigen processing and presentation in other organism involved in symbiotic interaction' (0 annotations)
into  'GO:0042786 active evasion of host immune response via regulation of host antigen processing and presentation'(0 annotations)

- [x] GO:0052385 evasion or tolerance by organism of reactive oxygen species produced by other organism involved in symbiotic interaction (0 annotations)
into GO:0052059 evasion or tolerance by symbiont of host-produced reactive oxygen species 

-  [x] GO:0052264 induction by organism of defense-related reactive oxygen species production in other organism involved in symbiotic interaction (0 annotations)
merge into  GO:0052064 induction by symbiont of defense-related host reactive oxygen species production 

-  [x]  GO:0052281 negative regulation by organism of B-cell mediated immune response of other organism involved in symbiotic interaction. (0 annotations)
merge into  GO:0052086 negative regulation by symbiont of host B-cell mediated immune response  (0 annotations)

-  [x] GO:0052293 modulation by organism of B-cell mediated immune response of other organism involved in symbiotic interaction (0 annotations)
merge into  GO:0052154 modulation by symbiont of host B-cell mediated immune response  (0 annotations)

-  [x]  GO:0052280 negative regulation by organism of T-cell mediated immune response of other organism involved in symbiotic interaction (0 annotations) 
merge into  GO:0052085 negative regulation by symbiont of host T-cell mediated immune response 

- [x]  GO:0052295 modulation by organism of T-cell mediated immune response of other organism involved in symbiotic interaction (0 annotations) 
merge into GO:0052156 modulation by symbiont of host T-cell mediated immune response 

- [x]   GO:0052294   modulation by organism of cell-mediated immune response of other organism involved in symbiotic interaction (0 annotations) 
merge into GO:0052155 modulation by symbiont of host cell-mediated immune response

- [x]   GO:0052278 negative regulation by organism of cell-mediated immune response of other organism involved in symbiotic interaction  (0 annotations) 
merge into GO:0052083 negative regulation by symbiont of host cell-mediated immune response 

- [x]   GO:0052561 negative regulation by organism of immune response of other organism involved in symbiotic interaction  (0 annotations) 
merge into  GO:0052562 negative regulation by symbiont of host immune response

- [x]  GO:0052309 negative regulation of innate immune response in other organism (0 annotations) 
merge into GO:0052170 negative regulation by symbiont of host innate immune response 

- [x]  GO:0052258 negative regulation by organism of pathogen-associated molecular pattern-induced innate immune response of other organism involved in symbiotic interaction (0 annotations) 
merge into GO:0052034 negative regulation by symbiont of microbe-associated molecular pattern-induced host innate immune response 

 - [x] GO:0052289 induction by organism of systemic acquired resistance in other organism involved in symbiotic interaction  (0 annotations) 
merge into GO:0052104 induction by symbiont of host systemic acquired resistance   (0 annotations) 
**Is the symbiont actually inducing the response ? this term may need to be obsoleted**

**Comment by pgaudet** [comment]
- [ ]  GO:0052285 modulation by organism of defense-related callose deposition of other organism involved in symbiotic interaction
merge into  GO:0052189 modulation by symbiont of defense-related host cell wall callose deposition

- [ ]   GO:0052310 modulation by organism of defense-related cell wall callose deposition in other organism involved in symbiotic interaction
merge into  GO:0052189 modulation by symbiont of defense-related host cell wall callose deposition

- [ ]  GO:0052090 modulation by symbiont of defense-related host callose deposition 
merge into  GO:0052189 modulation by symbiont of defense-related host cell wall callose deposition

- I think 'callose' is always in the cell wall; right @tberardini ?

**Comment by pgaudet** [comment]
- [ ]     GO:0051809     passive evasion of immune response of other organism involved in symbiotic interaction  (0 annotations)
merge into ' GO:0042782 passive evasion of host immune response' and move child term 'GO:0020033 antigenic variation' under it ?? @mgiglio99 
I am not sure about this term. Annotations seem to be to antigens... obsolete ?

**Comment by pgaudet** [comment]
-  [ ] GO:0051805 evasion or tolerance of immune response of other organism involved in symbiotic interaction   (0 annotations)
merge into  GO:0020012 evasion or tolerance of host immune response

-  [x]  GO:0051810 active evasion of immune response of other organism involved in symbiotic interaction  (0 annotations)
merge into GO:0042783 active evasion of host immune response 

-  [ ] GO:0052555 positive regulation by organism of immune response of other organism involved in symbiotic interaction  (0 annotations)
merge into GO:0052556 positive regulation by symbiont of host immune response 
**Look at children with @mgiglio99 **

**Comment by tberardini** [comment]
> I think 'callose' is always in the cell wall; right @tberardini ?

As far as I can tell, yes.

**Comment by ValWood** [comment]
still to go:

- [ ] GO:0052552    JSON
modulation by organism of immune response of other organism involved in symbiotic interaction

**Comment by ValWood** [comment]
@pgaudet  can this close?

**Comment by ValWood** [comment]
I think it is done

**Comment by ValWood** [comment]
done

**Comment by pgaudet** [comment]
What was left was is  GO:0052556 positive regulation by symbiont of host immune response
and children: 

* GO:0052559 induction by symbiont of host immune response
*  GO:0052347 positive regulation by symbiont of defense-related host nitric oxide production
* GO:0052533 positive regulation by symbiont of host induced systemic resistance
*  GO:0052166 positive regulation by symbiont of host innate immune response
*  GO:0052075 positive regulation by symbiont of host jasmonic acid-mediated defense response
* GO:0052344 positive regulation by symbiont of host phytoalexin production
* GO:0052527 positive regulation by symbiont of host resistance gene-dependent defense response
*  GO:0052537 positive regulation by symbiont of host systemic acquired resistance 

As we discussed today, I think those should should be obsoleted because the symbiont is not positively regulating the host defense response. OK @ValWood ?

**Comment by pgaudet** [comment]
or merge into 'GO:0052390 induction by symbiont of host innate immune response'?

**Comment by ValWood** [comment]
These are likely readouts for effector-triggered susceptibility (the necrotrophs)

GO:0052166 positive regulation by symbiont of host innate immune response
can merge into
'GO:0052390 induction by symbiont of host innate immune response


GO:0052527 positive regulation by symbiont of host resistance gene-dependent defense response
can merge into
GO:0080185 effector-triggered induction by symbiont of plant hypersensitive response

(r-genes are effector-triggered I)

If the others aren't used I would obsolete

**Comment by pgaudet** [comment]
Talking with @ValWood : many annotations can be moved to GO:0080185 effector-triggered induction by symbiont of plant hypersensitive response

**Comment by mgiglio99** [comment]
would it be easier on users to merge them instead of obsolete?

**Comment by ValWood** [comment]
GO:0052166 positive regulation by symbiont of host innate immune response
can merge into
'GO:0052390 induction by symbiont of host innate immune response

was merged (is already merged in QuickGO)

GO:0052527 positive regulation by symbiont of host resistance gene-dependent defense response

 has no annotations.
but can merge into

GO:0080185 effector-triggered induction by symbiont of plant hypersensitive response

@pgaudet  the synonyms will be useful.

I made a note to sanitiy check  the synonyms of GO:0080185  because it will have 100's

**Comment by pgaudet** [comment]
@ValWood we should look at those annotations: 
https://docs.google.com/spreadsheets/d/11qsaHEHYvG0T1LH6DlbIaDZrPz4EAXflCewkZglVGUc/edit#gid=0

https://docs.google.com/spreadsheets/d/1unkv0Z0QTWpgSGEOw5rDqrGN3J0hBqr17xXQt8TDzTE/edit#gid=0

**Comment by pgaudet** [comment]
Here are the synonyms 

synonym: "activation by organism of defense response in host by specific elicitors" EXACT []
synonym: "activation by organism of host gene-for-gene resistance" EXACT []
synonym: "activation by organism of host resistance gene-dependent defense response" EXACT []
synonym: "activation by organism of pathogen-race/host plant cultivar-specific resistance in host" EXACT []
synonym: "activation by symbiont of host resistance gene-dependent defense response" EXACT []
synonym: "effector dependent induction by symbiont of host immune response" EXACT []
synonym: "effector dependent induction by symbiont of host immunity" EXACT []
synonym: "effector triggered induction of host immune response" EXACT []
synonym: "effector-dependent induction by symbiont of host immune response" EXACT []
synonym: "effector-triggered induction of host immune response" BROAD []
synonym: "effector-triggered induction of host innate immune response" EXACT []
synonym: "ETI triggered of host innate immune response" EXACT []
synonym: "ETI-triggered of host innate immune response" EXACT []
synonym: "induction by organism of defense response in host by specific elicitors" EXACT []
synonym: "induction by organism of host gene-for-gene resistance" EXACT []
synonym: "induction by organism of pathogen-race/host plant cultivar-specific resistance in host" EXACT []
synonym: "induction by organism of resistance gene-dependent defense response of other organism involved in symbiotic interaction" BROAD []
synonym: "induction by symbiont of host resistance gene-dependent defense response" EXACT []
synonym: "induction of effector-triggered immunity (PTI)" EXACT []
synonym: "positive regulation by organism of defense response in host by specific elicitors" RELATED []
synonym: "positive regulation by organism of host gene-for-gene resistance" RELATED []
synonym: "positive regulation by organism of pathogen-race/host plant cultivar-specific resistance in symbiont" RELATED []
synonym: "positive regulation by organism of resistance gene-dependent defense response of other organism involved in symbiotic interaction" BROAD []
synonym: "positive regulation by symbiont of host resistance gene-dependent defense response" RELATED []
synonym: "stimulation by symbiont of host resistance gene-dependent defense response" RELATED []
synonym: "up regulation by symbiont of host resistance gene-dependent defense response" RELATED []
synonym: "up-regulation by symbiont of host resistance gene-dependent defense response" RELATED []
synonym: "upregulation by symbiont of host resistance gene-dependent defense response" RELATED []

**Comment by ValWood** [comment]
|OK I flagged som,e for removal and changed scope of some.

**Comment by ValWood** [comment]
this looks so nearly done, what needs to be done to close this  one?

**Comment by pgaudet** [comment]
This is all done AFAIK. I wanted you to check the synonyms.
