### ISSUE TITLE
Corrections/changes to  GO:0004573 mannosyl-oligosaccharide glucosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17674]
GO:0004573 mannosyl-oligosaccharide glucosidase activity
Definition 
Catalysis of the exohydrolysis of the non-reducing terminal glucose residue in the mannosyl-oligosaccharide Glc(3)Man(9)GlcNAc(2).

mannosyl-oligosaccharide glucohydrolase activity	exact
processing A-glucosidase I activity	related
mannosyl-oligosaccharide glucosidase (processing A-glucosidase I) activity	exact
Glc3Man9NAc2 oligosaccharide glucosidase activity	exact
trimming glucosidase I	related

1. 
- [x] The definition here is more specific than the term name.
In this case it would be better to make the primary term  name
Glc3Man9NAc2 oligosaccharide glucosidase activity	exact
(all of the experimental annotations are to 
Glc3Man9NAc2 oligosaccharide glucosidase activity i.e glucosidase I)

2.
- [x]  Glc3Man9NAc2 oligosaccharide glucosidase activity	 (existing synonym, new primary name) has a typo. Please correct to Glc3Man9GlcNAc2 (the last two monosaccharide are N-acetylglucosamine, abbreviated as GlcNAc, not NAc)

3. 
- [x] trimming glucosidase I	related
should be "exact"
(this is the precise def for "trimming glucosidase I")

4. 
- [ ]  "mannosyl-oligosaccharide glucosidase activity"
also fits  also fits for "Glucosidase II activity" 
should be  a parent of both (new terms requested below)

**Comment by ValWood** [comment]
5  GLucosidase II is 

EC 3.2.1.207
Glc(2)Man(9)GlcNAc(2)-[protein] + H(2)O <=> GlcMan(9)GlcNAc(2)-[protein] + beta-D-glucopyranose

we should have a term for this.
Currently it is a related synonym of
GO:0033919    JSON
glucan 1,3-alpha-glucosidase activity
Definition (GO:0033919 GONUTS page)
Catalysis of the hydrolysis of terminal (1->3)-alpha-D-glucosidic links in 1,3-alpha-D-glucans.

**Comment by ValWood** [comment]
Summary

mannosyl-oligosaccharide glucosidase activity
--GO:0033919 glucan 1,3-alpha-glucosidase activity
----Glc3Man9GlcNAc2 oligosaccharide glucosidase activity
----Glc2Man9GlcNAc2 oligosaccharide glucosidase activity

**Comment by ValWood** [comment]
Most of this came from Cecilia D
community curator and author of Alessio
https://www.pombase.org/reference/PMID:30389790

(I need to ask her to check my  extended interpretations)

**Comment by ValWood** [comment]
Glucosidase 1: Trims Glc alpha 1,2 Glc bond in Glc3Man9GlcNAc2 oligosaccharide in inmature glycoproteins

Glucosidase 2 first reaction: Trims Glc alpha 1,3 Glc bond in Glc2Man9GlcNAc2 oligosaccharide in inmature glycoproteins

Glucosidase 2 second reaction: Trims Glc alpha 1,3 Man bond in Glc1Man9GlcNAc2 oligosaccharide in inmature glycoproteins

I will fix above to reflect this.

**Comment by ValWood** [comment]
GO:0033913    glucan endo-1,2-beta-glucosidase activity
Definition (GO:0033913 GONUTS page)
Catalysis of the random hydrolysis of (1->2)-glucosidic linkages in (1->2)-beta-D-glucans.

can be a parent of
Glucosidase 1: Trims Glc alpha 1,2 Glc bond in Glc3Man9GlcNAc2 oligosaccharide in inmature glycoproteins

i.e
Glc3Man9GlcNAc2 oligosaccharide glucosidase activity (rename existing GO:0004573)

but we should remove the word "random"

**Comment by ValWood** [comment]
Cecilia provides this for clarification

![cecilia](https://user-images.githubusercontent.com/7359272/62307214-1bafe480-b47b-11e9-9e18-8a2849513598.jpg)

We need specific terms for the 3 reactions indicated

**Comment by ValWood** [comment]
Summary

mannosyl-oligosaccharide glucosidase activity (new term)
~--GO:0033919 glucan 1,3-alpha-glucosidase activity~  this can only be a parent of the glucosidase II reactions
----Glc3Man9GlcNAc2 oligosaccharide glucosidase activity (rename existing GO:0004573)
----Glc2Man9GlcNAc2 oligosaccharide glucosidase activity (new term)
----Glc1Man9GlcNAc2 oligosaccharide glucosidase activity

**Comment by hdrabkin** [comment]
Need PMIDs for def refs.

**Comment by ValWood** [comment]
https://www.pombase.org/reference/PMID:30389790

**Comment by ValWood** [comment]
Hi Harold,   any changes these could be implemented? A community expert suggested. Let me know if anything needs clarification, I can ask.

v

**Comment by pgaudet** [comment]
@hdrabkin Can this one be completed? It seems close to be done
