### ISSUE TITLE
'cell junction' biological process terms - revision of relations, names and definitions

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#18129]
To complement revisions of 'cell-cell junction' cellular component terms (https://github.com/geneontology/go-ontology/issues/18119) the related biological process terms also need to be reviewed.

The related terms are shown in the QuickGO screenshot of the ancestor chart below (the chart can be enlarged by clicking on it). Here is a summary of changes that need to be made and which are also marked on the chart below. Background and supporting evidence for making these changes are provided in https://github.com/geneontology/go-ontology/issues/18119.

- [x] 1. 'Adherens junction organisation' (yellow arrow in chart) is currently a child of 'cell junction organisation'. This needs to be repositioned to become a child of 'cell-cell junction organisation' and definition(s) revised accordingly. An annotation review will be needed first to determine whether the annotations refer to 'cell-substrate junction organization' or 'adherens junction organization' (adherens junctions are always cell-cell junctions). The review also needs to be done for the child regulation terms, if any exist. (_annotation review: https://github.com/geneontology/go-annotation/issues/2700_).

- [x] 2. 'Adherens junction maintenance' is currently a child of 'cell junction maintenance'. This needs to be repositioned to become a child of 'cell-cell junction maintenance' and definition(s) revised accordingly. An annotation review will be needed first to determine whether the annotations refer to 'cell-substrate junction maintenance' or 'adherens junction maintenance' (adherens junctions are always cell-cell junctions). (No regulation child terms exist for this GO term). (_annotation review: https://github.com/geneontology/go-annotation/issues/2702_).

- [x] 3. 'Positive/negative regulation of adherens junction organisation' should be a child of 'regulation of adherens junction organisation'. This should be achieved using logical definitions/equivalence axioms.

- [x] 4. 'Cell-substrate junction assembly' and 'cell-substrate adherens junction assembly' should be merged, and definition revised accordingly (magenta arrows (4) in chart). (There is no such structure as 'cell-substrate adherens junction'). This will require an annotation review first to determine whether the associated annotations refer to 'cell-substrate junction assembly', or 'adherens junction assembly' (adherens junctions are always cell-cell junctions). (No regulation child terms exist for this GO term). (_annotation review: https://github.com/geneontology/go-annotation/issues/2701_).

- [x] 5. 'Cell-substrate adherens junction disassembly' is currently a child of 'adherens junction disassembly' (There is no such structure as 'cell-substrate adherens junction'). This term will _either_ need to be renamed to 'Cell-substrate junction disassembly', _or_ obsoleted, and definition revised accordingly (magenta arrow (5) in chart). _There are currently no direct annotations to this term, and it has no direct regulation child terms (AmiGO and QuickGO checked on 14 Nov 2019)._ 

- [x] 6. A new term 'cell-substrate junction organization' should be added as a child of 'cell junction organization'. This new term will become a parent/grouping term for both 'cell-substrate junction assembly' and 'cell-substrate junction disassembly' (dark blue arrows in chart).

- [x] 7. 'protein localization to adherens junction' is currently a child of 'protein localization to cell junction'. It needs to be repositioned to become a child of 'protein localization to cell-cell junction' and definitions revised accordingly (adherens junctions are always cell-cell junctions). This will require an annotation review first to check whether current 'protein localization to adherens junction' annotations definitely refer to cell-cell junctions. The review also needs to be done for the child regulation terms, if any exist. (_annotation review: https://github.com/geneontology/go-annotation/issues/2703_).

- [x] 8. 'protein localization to cell-cell adherens junction' should be merged into 'protein localization to adherens junction' and the child regulation terms renamed accordingly (light blue arrows in chart). Definitions should also be revised (adherens junctions are always cell-cell junctions). This will require an annotation review first to check whether current 'protein localization to adherens junction' annotations definitely refer to cell-cell junctions (this is the same annotation review as for point 7 above). The review also needs to be done for the child regulation terms, if any exist. (_annotation review: https://github.com/geneontology/go-annotation/issues/2703_).

- [x] 9. The GO term 'cell-cell singaling involved in cell-cell junction organization' (red star in chart) should be obsoleted (it's been used for only 1 NAS annotation and can be represented as a GO-CAM). _Obsoletion notice: https://github.com/geneontology/go-ontology/issues/18164 - please respond by Nov 20th, 2019_.

![BP terms revisions](https://user-images.githubusercontent.com/16541096/68291416-e549bd00-009a-11ea-8255-76348a0e7495.png)
Image modified from QuickGO, 6th Nov 2019.

cc
@RLovering 
@milarolo

**Comment by hattrill** [comment]
Hi @BarbaraCzub I just came across a weird link between positive and negative regulation of adherens junction organization and positive and negative regulation of focal adhesion assembly - not sure if this is on your radar as lots of tickets, but thought that I would quickly flag it here.
![Screenshot 2019-11-19 at 11 45 41](https://user-images.githubusercontent.com/11865746/69144098-6e60eb00-0ac2-11ea-8f4f-1682a1adfb1c.png)

**Comment by BarbaraCzub** [comment]
Thanks @hattrill it appears I did not include it in my original revisions figure above. I'll go through this again, ensuring that all the child terms are in it! Thanks for pointing this out :)

**Comment by BarbaraCzub** [comment]
To do:

- [ ] complete points 1-9 above.

- [ ] check relationships with child terms, as pointed out by Helen, on 19 Nov.

**Comment by BarbaraCzub** [comment]
![BP terms_20191119](https://user-images.githubusercontent.com/16541096/69147035-2d78ce80-0ae2-11ea-898b-a6cb6d4686fc.png)

**Comment by BarbaraCzub** [comment]
![BP terms_20191119](https://user-images.githubusercontent.com/16541096/69147821-fd322f80-0ae3-11ea-952b-defcb709822b.png)

**Comment by BarbaraCzub** [comment]
Further improvements required based on the current (8th Dec 2019) ontology structure (image below):

- [ ] cell-cell junction organisation --> cell junction organisation
- [ ] cell-substrate junction disassembly --> cell-substrate junction organisation

Further improvements that will be helpful based on the current (8th Dec 2019) ontology structure (image below):
- [ ] adherens junction disassembly --> cell-cell junction disassembly (new term) --> cell junction disassembly (new term) --> cell junction organisation
- [ ] cell-substrate junction disassembly --> cell junction disassembly (new term) --> cell junction organisation

![BP terms revisions_20191208](https://user-images.githubusercontent.com/16541096/70388399-3f9fab80-19c2-11ea-905a-c566390de812.png)
