### ISSUE TITLE
differences between how microtubule and microfilament motors are described

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18664]
despite analogous activities the terms for

ATP-dependent microtubule motor activity
and
"ATP-dependent actin filament motor activity" (i.e myosin)

are quite different graphs:

<img width="488" alt="microfilament motor" src="https://user-images.githubusercontent.com/7359272/73257412-a029b880-41bb-11ea-9051-77b90273f0e1.png">

<img width="534" alt="microtubule motor" src="https://user-images.githubusercontent.com/7359272/73257389-956f2380-41bb-11ea-9c6e-3f14e28a86ea.png">

**Comment by ValWood** [comment]
The microfilament term
"ATP-dependent microtubule motor activity" I prefer becasue I only need to make a single annotation to describe the microtubule motor, which is coupled to the ATPase.

For the actin-microfilament motor, I would need to make 2 annotations to say the same thing. 

Suggestions to make consistent:

NOTE motor activity is defined
Catalysis of the generation of force resulting either in movement along a microfilament or microtubule, or in torque resulting in membrane scission, coupled to the hydrolysis of a nucleoside triphosphate. PMID:11242086
(I.e is necessarily nucleotide-dependent)

 -  [ ] I am not sure but I think all microtubule and microfilament motors are ATP dependent (the "scission motors are the only GTPase dependent ones I have come across. I can check this.


- [ ] GO:0030898  actin-dependent ATPase activity
Catalysis of the reaction: ATP + H2O = ADP + phosphate. This reaction requires the presence of an actin filament to accelerate release of ADP and phosphate.

should be a descendant of
GO:0000146    microfilament motor activity
Catalysis of movement along a microfilament, coupled to the hydrolysis of a nucleoside triphosphate (usually ATP).

(this term would be analogous to "ATP dependent microtubule motor activity"

- [ ] . SInce microfilament/microtubule motor activities are necessarily microtubule/microfilament dependent it seems  more consistent to say 

"ATP-dependent actin microfilament  motor activity" instead of "actin-dependent ATPase activity"
(unless there are any actin-dependent ATPases which are not motors? But so far all 56  EXP annotations are to myosins.

This would then mirror the microtubule motor graph, and make annotations more consistent.

i.e ALL  "actin-dependent ATPase activity" should be annotated to GO:0000146    microfilament motor activity, this is not currently the case:

<img width="488" alt="microfilament motor" src="https://user-images.githubusercontent.com/7359272/73259494-dc5f1800-41bf-11ea-9db2-88015848153d.png">

**Comment by ukemi** [comment]
PMID:10823888, PMID:10860951, PMID:12514193?

**Comment by ValWood** [comment]
PMID:10823888 implies hydrolysis (depolymerization is ATPase dependent)
in which case  would be useful to have "ATP-dependent actin microfilament motor activity" as a new term descendant to describe actin motors (not that currently  the existing term  GO:0030898 actin-dependent ATPase activity is only used for "actin motors")

**Comment by ValWood** [comment]
From these papers
PMID:10823888, PMID:10860951, PMID:12514193?

I isn't clear if the  ATP dependent actin depolymerization is a gene dependent process or just the favourable reaction in the absence of stabililization by capping etc. It would be good to find a gene product to annotate to non-myosin actin-dependent ATPase

**Comment by sjm41** [comment]
I just came across this myself, only to find (again!) that Val has already reported it.
Right now, to accurately annotate a myosin, you need to know to add both the "microfilament motor activity" term and the "actin-dependent ATPase activity" - the myosin annotations I've seen tend to be either one or the other, so searches using either one term or the other only give partial lists.... 

So, I would also like to see the "microfilament motor activity" branch made comparable to the "microtubule motor activity", for the same reasons Val states. And I would also support changing the term name and def of the current "actin-dependent ATPase activity" to mirror the "ATP-dependent microtubule motor activity" term.

FYI, here's how things currently look (changed a bit since Val's original post):

==

id: GO:0003777
name: microtubule motor activity
namespace: molecular_function
def: "Catalysis of movement along a microtubule, coupled to the hydrolysis of a nucleoside triphosphate (usually ATP)." [GOC:mah, ISBN:0815316194]
is_a: GO:0003774 ! motor activity

==

id: GO:1990939
name: ATP-dependent microtubule motor activity
namespace: molecular_function
def: "Catalysis of movement along a microtubule, coupled to the hydrolysis of ATP." [PMID:19686686]
xref: Reactome:R-HSA-9610627 "KIF17 transports GluN1:GluN2B (GRIN1:GRIN2B) NMDA receptors to the plasma membrane"
is_a: GO:0003777 ! microtubule motor activity
is_a: GO:0016887 ! ATPase activity

==

id: GO:0000146
name: microfilament motor activity
namespace: molecular_function
def: "Catalysis of movement along a microfilament, coupled to the hydrolysis of a nucleoside triphosphate (usually ATP)." [GOC:mah, ISBN:0815316194]
is_a: GO:0003774 ! motor activity

==

id: GO:0030898
name: actin-dependent ATPase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + H2O = ADP + phosphate. This reaction requires the presence of an actin filament to accelerate release of ADP and phosphate." [GOC:mah]
synonym: "actin-activated ATPase activity" EXACT []
is_a: GO:0016887 ! ATPase activity

==

![Screenshot 2020-06-17 at 08 35 07](https://user-images.githubusercontent.com/16306861/84869074-7c391780-b075-11ea-8bdc-71d70fb93945.png)

**Comment by ValWood** [comment]
Is this now out. of date?
This term request might also impact 
https://github.com/geneontology/go-ontology/issues/20563

**Comment by ValWood** [comment]
Actually more info here. I will close 
https://github.com/geneontology/go-ontology/issues/18664
as duplicate

**Comment by pgaudet** [comment]
@ValWood @sjm41 

Do we need both terms in those pairs: 

 **GO:1990939 ATP-dependent microtubule motor activity** vs   **GO:0003777 microtubule motor activity** 
and 
**GO:0030898 actin-dependent ATPase activity**  vs **GO:0000146 microfilament motor activity** 

I was proposing to merge, see #20877

Thanks, Pascale

**Comment by ValWood** [comment]
I think they can merge?

**Comment by sjm41** [comment]
I agree.

I think it would make sense for the final two terms to be named: "ATP-dependent microtubule motor activity" and "ATP-dependent actin microfilament motor activity".
And the final terms would each have two parents, 'motor activity' and 'ATPase activity', right?

I'm sure you're aware, but there will also be some child terms to sort out/merge here:

1. Update these child term names to match final parent name (maybe this is automatic?):
GO:2000574 regulation of microtubule motor activity
GO:2000575 negative regulation of microtubule motor activity
GO:2000575 negative regulation of microtubule motor activity

2. Merge/update names of children of GO:0030898 and GO:0000146:
GO:1904621 regulation of actin-dependent ATPase activity (regulates GO:0030898)
GO:1904623 positive regulation of actin-dependent ATPase activity (positively_regulates GO:0030898)
GO:1904622 negative regulation of actin-dependent ATPase activity (negatively_regulates GO:0030898)

GO:0120079 regulation of microfilament motor activity (regulates GO:0000146)
GO:0120081 positive regulation of microfilament motor activity (positively_regulates GO:0000146)
GO:0120080 negative regulation of microfilament motor activity (negatively_regulates GO:0000146)
GO:0060002 plus-end directed microfilament motor activity (is_a GO:0000146)
GO:0060001 minus-end directed microfilament motor activity (is_a GO:0000146)

**Comment by pgaudet** [comment]
Is the ATP-dependent useful to the users, or did we just get used to it ? (I can never tell). I would have done simply 'microtubule motor activity' and 'actin microfilament motor activity'

**Comment by ValWood** [comment]
I think since all motors are ATP-dependent it would be OK not to mention in the term name, but it should be part of the definition (and can be exact synonym)

**Comment by sjm41** [comment]
Dumping the ATP-bit in the term name (but maintaining the ATPase parentage!) is fine with me.

**Comment by sjm41** [comment]
Just realised that #19738 is relevant to reclassifying ATP-depedent motors.
That is, it looks like the primary enzymatic function of these motor proteins should be an isomerase activity (rather than a ATPase/hydrolase activity) - maybe change parent of  "motor activity" (GO:0003774) from "nucleoside-triphosphatase activity (GO:0017111 JSON)" to "GO:0016853 ! isomerase activity"?

**Comment by pgaudet** [comment]
I was thinking to change the main parent to 'motor activity' - the isomerase activity seems odd, as @kaxelsen points out, in EC it means "Isomerases altering macromolecular conformation"; while GO is using isomerase in the more 'classical/chemical' meaning. 

I was planning to add the missing ECs for #19738  but not add the isomerase parent. Unless you think this is useful?

**Comment by sjm41** [comment]
I guess there are 2 (related) points here:

1. EC now clearly defines these motor proteins as isomerases (EC:5) rather than hydrolases (EC:3), whereas GO defines them as hydrolases (via the current parentage of 'motor activity'). Do we want to align with EC on this?

2. The current parent of 'motor activity' is 'nucleoside-triphosphatase activity' - I guess that reflects that the 3 children of 'motor activity' are coupled to an ATPase or GTPase activity:
GO:0061791 GTPase motor activity (this has only 2 annotations!)
GO:0003777 microtubule motor activity (this is 'ATP dependent')
GO:0000146 microfilament motor activity (this is 'ATP dependent')
So based on the other discussion about classifying MF that use ATP, having the 'nucleoside-triphosphatase activity' parent here seems inconsistent?  From that viewpoint, and we want an alternative catalytic activity parent for 'motor activity', then maybe 'isomerase activity' is best??

**Comment by ValWood** [comment]
note that all of these:
Update these child term names to match final parent name (maybe this is automatic?):
GO:2000574 regulation of microtubule motor activity
GO:2000575 negative regulation of microtubule motor activity
GO:2000575 negative regulation of microtubule motor activity

Merge/update names of children of GO:0030898 and GO:0000146:
GO:1904621 regulation of actin-dependent ATPase activity (regulates GO:0030898)
GO:1904623 positive regulation of actin-dependent ATPase activity (positively_regulates GO:0030898)
GO:1904622 negative regulation of actin-dependent ATPase activity (negatively_regulates GO:0030898)

GO:0120079 regulation of microfilament motor activity (regulates GO:0000146)
GO:0120081 positive regulation of microfilament motor activity (positively_regulates GO:0000146)
GO:0120080 negative regulation of microfilament motor activity (negatively_regulates GO:0000146)
GO:0060002 plus-end directed microfilament motor activity (is_a GO:0000146)
GO:0060001 minus-end directed microfilament motor activity (is_a GO:0000146)


are BP terms in the "regulation of molecular function" branch. There is talk of getting rid of these terms because they usually represent MF in the BP ontology. Indeed, these  terms are used for myosin/dynein/kinesin light chain /regulatory subunits.

So it might be good to establish the MF regulator terms and figure out if these processes are really required 
(or merge them with the appropriate MF terms)

**Comment by ValWood** [comment]
@thomaspd 
@pgaudet 
This should be done at the same time as
https://github.com/geneontology/go-ontology/issues/21619

**Comment by pgaudet** [comment]
- [x] Merged  'GO:1990939 ATP-dependent microtubule motor activity'  into superclass  'GO:0003777 microtubule motor activity' 
 - [x] Added logical defs for 
 
'GO:0003777 microtubule motor activity'  
intersection_of: GO:0003774 ! motor activity
intersection_of: has_participant GO:0005874 ! microtubule

and

microfilament motor activity:
 GO:0003774 ! motor activity
intersection_of: has_participant GO:0005884 ! actin filament

 - [x]  added relationship: has_part GO:0016887 ! ATP hydrolysis activity to both, but not in the logical definition, since this is not what distinguishes the activity from their common superclass.

**Comment by pgaudet** [comment]
Also, added pubmed references to microtubule terms, PMID:15659646, PMID:32842864

**Comment by pgaudet** [comment]
@sjm41 

For your point 2 in https://github.com/geneontology/go-ontology/issues/18664#issuecomment-780718994 

Now both 
'microfilament motor activity'
'microtubule motor activity'

are children of 'ATPase-dependent activity'. 

Is that OK? Should we create a grouping term, ATP-dependent motor activity? 

@ValWood

**Comment by pgaudet** [comment]
@ValWood @sjm41 
AFAIK everything was done that was requested here  - expect the regulation issue (https://github.com/geneontology/go-ontology/issues/18664#issuecomment-781384093) - I will create a new obsoletion ticket. 

Thanks, Pascale

**Comment by ValWood** [comment]
>Is that OK? Should we create a grouping term, ATP-dependent motor activity?

Personally I  don't think we need an ATP-dependent grouping. They will all group under 
motor activity. They also group naturally because all the GTPase motors are scission motors as far as I am aware, all the microtubule motors and ATPases.

I think it's OK if they are annotated to the type of motor and ATP or GTPase without this orthogonal grouping.

**Comment by pgaudet** [comment]
Perfect - I also dont like too many grouping terms - we only have 2 classes here so far. We can do it later if needed.

**Comment by sjm41** [comment]
@pgaudet
- I agree we don't need the additional 'ATP-dependent motor activity' grouping term. 
- Can you clarify whether 'motor activity' is still a child of 'nucleoside-triphosphatase activity' (GO:0017111)? That bit still seems odd to me given we're specifying this via the separate 'ATPase-dependent activity' parent for the 'microfilament motor activity' and 'microtubule motor activity' terms.

**Comment by pgaudet** [comment]
> Can you clarify whether 'motor activity' is still a child of 'nucleoside-triphosphatase activity' (GO:0017111)

No, I have moved it directly under MF. So, 'microfilament motor activity' and 'microtubule motor activity' are direct children of 'ATP(ase)'dependent activity, and 'GTPase motor activity' is_a 'GTPase activity'.  There is also another sibling, 'proton motive force-driven motor activity'. 

OK ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Yes, that makes more sense, thanks!
