### ISSUE TITLE
Should GO:0033842 be a child of GO:0033207?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#18752]
Seems like "N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase activity" (GO:0033842) should be a child of "beta-1,4-N-acetylgalactosaminyltransferase activity" (GO:0033207)?

==
[Term]
id: GO:0033842
name: N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-N-acetyl-D-galactosamine + N-acetyl-beta-D-glucosaminyl group = UDP + N-acetyl-beta-D-galactosaminyl-(1->4)-N-acetyl-beta-D-glucosaminyl group." [EC:2.4.1.244]
synonym: "beta1,4-N-acetylgalactosaminyltransferase activity" EXACT [EC:2.4.1.244]
synonym: "beta1,4-N-acetylgalactosaminyltransferase III activity" EXACT [EC:2.4.1.244]
synonym: "beta1,4-N-acetylgalactosaminyltransferase IV activity" EXACT [EC:2.4.1.244]
synonym: "beta4GalNAc-T3" RELATED [EC:2.4.1.244]
synonym: "beta4GalNAc-T4" RELATED [EC:2.4.1.244]
synonym: "UDP-N-acetyl-D-galactosamine:N-acetyl-D-glucosaminyl-group beta-1,4-N-acetylgalactosaminyltransferase activity" EXACT [EC:2.4.1.244]
xref: EC:2.4.1.244
xref: MetaCyc:2.4.1.244-RXN
xref: RHEA:20493
is_a: GO:0008376 ! acetylgalactosaminyltransferase activity
is_a: GO:0140103 ! catalytic activity, acting on a glycoprotein

==
[Term]
id: GO:0033207
name: beta-1,4-N-acetylgalactosaminyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of an N-acetylgalactosaminyl residue from UDP-N-acetyl-galactosamine to an acceptor molecule, forming a beta-1,4 linkage." [GOC:mah]
synonym: "beta-1,4-GalNAc transferase activity" EXACT []
is_a: GO:0008376 ! acetylgalactosaminyltransferase activity

**Comment by sjm41** [comment]
Hi Harold - any thoughts/insights on this?

**Comment by hdrabkin** [comment]
@deustp01  what do you think?

**Comment by hdrabkin** [comment]
I notice id: GO:0033207 really has no decent references (like many of the grouping terms)

**Comment by hdrabkin** [comment]
I'm inclined to agree

**Comment by deustp01** [comment]
The chemistry here is way beyond my limited knowledge of glycoprotein biochemistry. Sorry!

**Comment by pgaudet** [comment]
Merge ? 
https://enzyme.expasy.org/EC/2.4.1.244


Accepted Name: N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N- acetylgalactosaminyltransferase.
synonym: Beta-1,4-N-acetylgalactosaminyltransferase.

GO:0033207 name: beta-1,4-N-acetylgalactosaminyltransferase activity

Pascale

**Comment by pgaudet** [comment]
Some proteins are annotated to all 3 

https://www.uniprot.org/uniprot/Q9VAQ8

acetylgalactosaminyltransferase activity Source: FlyBase
beta-1,4-N-acetylgalactosaminyltransferase activity Source: FlyBase
N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase activity Source: FlyBase

**Comment by sjm41** [comment]
Reviewing this again, I agree with Pascale - we should merge GO:0033842 and GO:0033207.

Looking at QuickGO, I see 470 annotations to GO:0033842 and only 39 annotations to GO:0033207.
Of those 39 annotations using GO:0033207:
- 3 IDA annotations from FlyBase
- 1 IDA annotation from WormBase
- 35 IEA annotations  from EnsemblMetazoa (based on the IDA FB/WB source annotations)

Looking at the three IDAs from FB (which correspond to just two genes):
UniProtKB:Q7KN92 	beta4GalNAcTA	 PMID:17498683
UniProtKB:Q86NU9 	beta4GalNAcTB	 PMID:17498683
UniProtKB:Q9VAQ8 	beta4GalNAcTB	 PMID:17498683
I can say that the merge of the two GO terms would be fine.
@vanaukenk - can you check out the WB annotation using GO:0033207 to Q9GUM2?

==

_Some proteins are annotated to all 3
https://www.uniprot.org/uniprot/Q9VAQ8
(mapped to EC:2.4.1.244)
acetylgalactosaminyltransferase activity Source: FlyBase
beta-1,4-N-acetylgalactosaminyltransferase activity Source: FlyBase
N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase activity Source: FlyBase_

Yeah, that's what got me looking at the two GO terms in the first place!
The first annotation (to the parent term from PMID:15563714) appears to be correct, based on the description of the assay in that paper.

**Comment by sjm41** [comment]
Oh, hang on....
I see that GO:0033842, but not GO:0033207, currently has parent of "catalytic activity, acting on a glycoprotein" (GO:0140103).
Consistent with that, I note that GO:0033842 and EC:2.4.1.244 specifically mention 'glycoprotein' in the term name (though not in the definition).

This may reflect why we have the two separate GO terms.
Indeed, PMID:17498683 (the source of the 3 FlyBase annotations to GO:0033207) describes the 2 fly enzymes as working in glycosphingolipid synthesis (so not glycoprotein).

So....I return to my original proposal: GO:0033207 (the more generic term) should be the parent of GO:0033842 (a more specific term, in that it specifies a glycoprotein substrate).

And/or we could make a new specific term for the 2 fly enzymes (and maybe the worm enzyme??) to specify the glycolipid substrate.

Thoughts?

**Comment by sjm41** [comment]
Reviewing this (yet) again:

id: GO:0033842
name: N-acetyl-beta-glucosaminyl-glycoprotein 4-beta-N-acetylgalactosaminyltransferase activity
def: "Catalysis of the reaction: UDP-N-acetyl-D-galactosamine + N-acetyl-beta-D-glucosaminyl group = UDP + N-acetyl-beta-D-galactosaminyl-(1->4)-N-acetyl-beta-D-glucosaminyl group." [EC:2.4.1.244]
xref: EC:2.4.1.244
xref: RHEA:20493

The current EC/RHEA def for this is:
an N-acetyl-beta-D-glucosaminyl **derivative** + UDP-N-acetyl-alpha-D-galactosamine = an N-acetyl-beta-D-galactosaminyl-(1->4)-N-acetyl-beta-D-glucosaminyl derivative + UDP + H+.

That is, it is not specific for a glyco**protein**, as the current GO/EC name suggests.

So, there are now 3 tasks to be done to close this issue:

- [ ] Update GO:0033842 name and def to use 'derivative'
- [ ] Merge GO:0033207 into GO:0033842
- [ ] GO:0033207 currently has one other child (GO:0033208), shown below. The term has no annotations and no db xrefs, so can be obsoleted. (The def does refer to two PMIDs, which appear to be about human B4GALNT2 (Q8NHY0), which is linked (but not annotated) to EC:2.4.1.165 in UniProt, so it's possible that GO:0033207 is the same as GO:0047233/EC:2.4.1.165, but I haven't checked this in depth. Regardless, given there's no annotations, it seems easiest and safest just to obsolete GO:0033207

**Comment by sjm41** [comment]
@pgaudet I've updated the name and def. Could you take care of the merge and obsoletion? thanks.

**Comment by pgaudet** [comment]
Neither EC:2.4.1.165 nor [RHEA:13569](https://www.rhea-db.org/rhea/13569) have any genes associate, so let's obsolete.

**Comment by pgaudet** [comment]
We can restore the GO term - EC has been modified and there is a new RHEA: 

> Hi Pascale,

> Thank you for this ticket that turned out to be an error report. EC 2.4.1.165
turned out to be wrong, as did RHEA:13569. I have now updated EC 2.4.1.165 at
IUBMB and I have found it can be linked to B4GALNT2 (B4GN2_HUMAN) and
RHEA:81947.
RHEA;[81947] an N-acetyl-α-neuraminyl-(2→3)-β-D-galactosyl derivative +
UDP-N-acetyl-α-D-galactosamine = an
N-acetyl-β-D-galactosaminyl-(1→4)-[N-acetyl-α-neuraminyl-(2→3)]-β-D-galactosyl
derivative + UDP + H+

> So RHEA;13569 will be made obsolete, and you should restore GO:0047233.

> Cheers,
Kristian

**Comment by sjm41** [comment]
Reviewing this, everything is done except GO:0033842 still has "is_a: GO:0140103 ! catalytic activity, acting on a glycoprotein"

As mentioned above, the fly proteins annotated to this term act on glycolipids (not glycoproteins), and the GO/EC term name  also refers generically to a "N-acetyl-beta-glucosaminyl-**derivative**".

So I will remove the "catalytic activity, acting on a glycoprotein" parent and then close this (old!) ticket.
