### ISSUE TITLE
Revisions of ‘maintenance of permeability of blood-brain barrier’ and related GO terms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#19155]
While annotating proteins associated with the [Blood-Brain Barrier Endothelial Connections](https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/neurological-gene-0), as a part of the ARUK-UCL project, Mila (@milarolo) has identified a discrepancy between GO term name and definition of ‘maintenance of permeability of blood-brain barrier’. The definition suggests this really is a regulation of impermeability of the barrier. The regulation child terms also need to be revised, as ‘maintenance…’ is a regulatory process in itself. Several BBB transport term revisions are also required. 

### Proposal (numbers correspond to labels shown in Figure 1 below)

- [x] 1a. Rename ‘maintenance of permeability of blood-brain barrier' as ‘maintenance of blood-brain barrier’;
- [x] 1b. Make ‘tissue homeostasis’ its is_a parent;
- [x] 1c. Remove the parent ‘regulation of biological quality’;
- [x] 1d. Revise definition of ‘maintenance (of permeability) of blood-brain barrier’:
- current: "Preserving the permeability barrier between the blood and the brain in a stable functional or structural state. The cells in the brain are packed tightly together preventing the passage of most molecules from the blood into the brain. Only lipid soluble molecules or those that are actively transported can pass through the blood-brain barrier. PMID:20080302"
- proposed: "Maintaining the structure and function of the blood-brain barrier, thus ensuring specific regulated transport of substances (e.g. macromolecules, small molecules, ions) into the brain, and out of the brain into the blood circulation. PMID:20080302. PMID:30280653. GOC:aruk."
- [x] 1e. Revise synonyms.
- [x] 1f. Add a comment explaining that no 'regulation' child terms should be added for this term, because 'maintenance' is in itself 'regulation'.

- [x] 2a. Rename ‘(positive/negative) regulation of maintenance of permeability of blood-brain barrier’ as ‘(positive/negative) regulation of blood-brain barrier permeability’;
- [x] 2b. Make ‘(positive/negative) regulation of vascular permeability’ a direct is_a parent to the ‘(positive/negative) regulation of blood-brain barrier permeability’;
- [x] 2c. Remove ‘regulation’ relationships to ‘maintenance (of permeability) of blood-brain barrier’;
- [x] 2d. Add relationship part_of ‘maintenance of blood-brain barrier’;
- [x] 2e. Revise definition of '(positive/negative) regulation of blood-brain barrier permeability’:
- current: "Any process that modulates the frequency, rate or extent of maintenance of permeability of blood-brain barrier. PMID:22524708."
- proposed: "Any process that modulates/increases/decreases blood-brain barrier permeability, the quality of the blood-brain barrier that allows for a controlled passage of substances (e.g. macromolecules, small molecules, ions) into and out of the brain. PMID:22524708. PMID:30280653. GOC:aruk."
- [x] 2f. Revise synonyms.

- [x] 3a. Make ‘transport across blood-brain barrier’ a child of ‘vascular transport’ (GO:0010232) [not shown in Figure 1], which is defined as “The directed movement of substances, into, out of or within a cell, either in a vascular tissue or in the vascular membrane.”;
- [x] 3b. Make ‘vascular transport’ (GO:0010232) [not shown in Figure 1] a part_of ‘vascular process in circulatory system’, which is defined as “A circulatory process that occurs at the level of the vasculature.”.

- [x] 4a. Add grouping terms ‘(positive/negative) regulation of transport across the blood-brain barrier’;
- [x] 4b.  Make ‘(positive/negative) regulation of lipid transport across the blood-brain barrier (a) child(ren) of the appropriate new grouping term(s); ensure that equivalence axioms/logical definitions exist for all these terms;
- [x] 4c.  Make the new terms: ‘(positive/negative) regulation of transport across the blood-brain barrier’ part_of children of relevant ‘(positive/negative) regulation of vascular permeability’ terms.

![image](https://user-images.githubusercontent.com/16541096/77549419-dc7a4c00-6ec0-11ea-9d00-fa9d2e0d945f.png)
Figure 1. Proposed revisions to BBB maintenance, permeability and transport terms. Labels are explained in the numbered list of items above the figure. The figure can be enlarged by clicking on it. Figure accessed and modified from QuickGO on 25th March 2020.

### Annotation considerations
We (cc @RLovering) considered whether or not the ontology revisions, summarised in points 1 and 2 above, will require any prior annotation reviews. No annotation reviews are required, because although term names, definitions and relationships will be refined, the essence of their meanings will remain unchanged.

### Additionally include the following suggestions in the UBERON tracker based on PMID:30280653
1. Add the synonym ‘neurovascular unit’ to ‘neurovascular bundle’ (UBERON_0016630) 
[see Figure 1 in a recent review from the Zlokovic lab: https://www.ncbi.nlm.nih.gov/pubmed/30280653];
2. Make ‘blood-brain barrier’ a part_of child of ‘neurovascular unit’ 
[see Figure 1 in a recent review from the Zlokovic lab: https://www.ncbi.nlm.nih.gov/pubmed/30280653];
3. The ‘blood brain barrier’ should also have a relationship to either the vascular plexus (UBERON_0005629), or vasculature (UBERON_0002049) 
[see section II. A. ‘BBB formation’ in a recent review from the Zlokovic lab: https://www.ncbi.nlm.nih.gov/pubmed/30280653].
https://github.com/obophenotype/uberon/issues/1579
