### ISSUE TITLE
'establishment of blood-brain barrier' parentage revisions 

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#19160]
While revising ‘maintenance of permeability of blood-brain barrier’ and related GO terms (https://github.com/geneontology/go-ontology/issues/19155) the required revisions related to parentage of the 'establishment of blood-brain barrier' and its child terms were also identified:

- [x] Make ‘establishment of blood-brain barrier’ and part_of child of ‘CNS development’ 

- [x] Remove the part_of link between ‘CNS development’ and ‘establishment of endothelial blood-brain barrier’ 

![image](https://user-images.githubusercontent.com/16541096/77652044-b4e9b900-6f7e-11ea-8cd3-27c617bb6a19.png)

cc @RLovering

**Comment by BarbaraCzub** [comment]
- [ ] also move references from synonyms to definitions
