### ISSUE TITLE
regulation of cellular component movement (GO:0051270) 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19809]
This term (if required)  should have many more annotations/descendants.

For example in  PomBAse it has only 3 annotations

SPAPB1A10.09 | ase1 | antiparallel microtubule cross-linking factor Ase1
SPAC926.03 | rlc1 | myosin II regulatory light chain Rlc1
SPAC24B11.11c | sid2 | NDR kinase Sid2

However, many macroprocesses could be defined as "cellular componet movement"

Chromosome segregation, for example

**Comment by pgaudet** [comment]
There *are* a lot of annotations to descendants - those are the EXP: 


positive regulation of cell migration | (332) | + | -
-- | -- | -- | --
negative regulation of cell migration | (204) | + | -
regulation of cell migration | (170) | + | -
positive regulation of blood vessel endothelial cell migration | (66) | + | -
positive regulation of endothelial cell migration | (64) | + | -
positive regulation of border follicle cell migration | (57) | + | -
negative regulation of cell migration involved in sprouting angiogenesis | (52) | + | -
positive regulation of cell migration involved in sprouting angiogenesis | (51) | + | -
positive regulation of smooth muscle cell migration | (48) | + | -
positive regulation of epithelial cell migration | (47) | + | -
negative regulation of blood vessel endothelial cell migration | (44) | + | -
positive regulation of cell motility | (42) | + | -
regulation of axon extension involved in axon guidance | (38) | + | -
positive regulation of macrophage chemotaxis | (33) | + | -
positive regulation of neutrophil chemotaxis | (33) | + | -
positive regulation of vascular associated smooth muscle cell migration | (33) | + | -
regulation of axon guidance | (33) | + | -
negative regulation of axon extension involved in axon guidance | (29) | + | -
negative regulation of endothelial cell migration | (28) | + | -
negative regulation of vascular associated smooth muscle cell migration | (26) | + | -
positive regulation of distal tip cell migration | (26) | + | -
positive regulation of leukocyte migration | (26) | + | -
positive regulation of monocyte chemotaxis | (26) | + | -
regulation of cell motility | (26) | + | -
positive regulation of neuron migration | (25) | + | -
regulation of dorsal/ventral axon guidance | (25) | + | -
regulation of neuron migration | (25) | + | -
positive regulation of leukocyte chemotaxis | (24) | + | -
positive regulation of motor neuron migration | (24) | + | -
regulation of cardiac muscle cell contraction | (24) | + | -
positive regulation of T cell migration | (23) | + | -
positive regulation of anterior/posterior axon guidance | (22) | + | -
positive regulation of fibroblast migration | (22) | + | -
negative regulation of epithelial cell migration | (21) | + | -
positive regulation of T cell chemotaxis | (21) | + | -
negative regulation of cell motility | (18) | + | -
positive regulation of axon extension involved in axon guidance | (18) | + | -
regulation of bacterial-type flagellum-dependent cell motility | (18) | + | -
negative regulation of neuron migration | (17) | + | -
positive regulation of axon guidance | (17) | + | -
negative regulation of smooth muscle cell migration | (16) | + | -
regulation of cilium beat frequency involved in ciliary motility | (16) | + | -
positive regulation of cellular component movement | (15) | + | -
positive regulation of keratinocyte migration | (14) | + | -
regulation of fibroblast migration | (14) | + | -
regulation of neutrophil chemotaxis | (14) | + | -
regulation of ventricular cardiac muscle cell action potential | (13) | + | -
negative regulation of cellular component movement | (12) | + | -
positive regulation of neutrophil extravasation | (12) | + | -
negative regulation of bacterial-type flagellum-dependent cell motility | (11) | + | -
negative regulation of fibroblast migration | (11) | + | -
positive regulation of endothelial cell chemotaxis | (11) | + | -
positive regulation of flagellated sperm motility | (11) | + | -
positive regulation of leukocyte tethering or rolling | (11) | + | -
positive regulation of microglial cell migration | (11) | + | -
positive regulation of neutrophil migration | (11) | + | -
posterior lateral line neuromast deposition | (11) | + | -
regulation of cellular component movement | (11) | + | -
regulation of endothelial cell migration | (11) | + | -
regulation of motor neuron axon guidance | (11) | + | -
regulation of sensory neuron axon guidance | (11) | + | -
negative regulation of neutrophil chemotaxis | (10) | + | -
regulation of epithelial cell migration, open tracheal system | (10) | + | -
regulation of retinal ganglion cell axon guidance | (10) | + | -
negative regulation of leukocyte migration | (9) | + | -
negative regulation of sensory neuron axon guidance | (9) | + | -
positive regulation of cellular extravasation | (9) | + | -
positive  regulation of endothelial cell chemotaxis by VEGF-activated vascular  endothelial growth factor receptor signaling pathway | (9) | + | -
regulation of blood vessel endothelial cell migration | (9) | + | -
regulation of cilium beat frequency | (9) | + | -
regulation of leukocyte migration | (9) | + | -
negative regulation of macrophage chemotaxis | (8) | + | -
negative regulation of trophoblast cell migration | (8) | + | -
positive regulation of dendritic cell chemotaxis | (8) | + | -
regulation of distal tip cell migration | (8) | + | -
regulation of epithelial cell migration | (8) | + | -
positive regulation of natural killer cell chemotaxis | (7) | + | -
positive regulation of trophoblast cell migration | (7) | + | -
regulation of T cell migration | (7) | + | -
regulation of cardiac muscle cell action potential involved in regulation of contraction | (7) | + | -
regulation of smooth muscle cell migration | (7) | + | -
negative regulation of T cell migration | (6) | + | -
negative regulation of monocyte chemotaxis | (6) | + | -
negative regulation of smooth muscle cell chemotaxis | (6) | + | -
positive regulation of sensory neuron axon guidance | (6) | + | -
regulation of flagellated sperm motility | (6) | + | -
semaphorin-plexin signaling pathway involved in regulation of photoreceptor cell axon guidance | (6) | + | -
negative regulation of endothelial cell chemotaxis | (5) | + | -
negative regulation of endothelial cell chemotaxis to fibroblast growth factor | (5) | + | -
negative regulation of lymphocyte migration | (5) | + | -
neuromast deposition | (5) | + | -
positive regulation of anterograde synaptic vesicle transport | (5) | + | -
positive regulation of cilium-dependent cell motility | (5) | + | -
positive regulation of flagellated sperm motility involved in capacitation | (5) | + | -
positive regulation of granulocyte chemotaxis | (5) | + | -
positive regulation of mononuclear cell migration | (5) | + | -
positive regulation of smooth muscle cell chemotaxis | (5) | + | -
regulation of cilium movement | (5) | + | -
regulation of microtubule-based movement | (5) | + | -
regulation of organelle transport along microtubule | (5) | + | -
negative regulation of flagellated sperm motility | (4) | + | -
negative regulation of leukocyte tethering or rolling | (4) | + | -
negative regulation of wound healing, spreading of epidermal cells | (4) | + | -
positive regulation of Schwann cell migration | (4) | + | -
positive regulation of anterograde dense core granule transport | (4) | + | -
positive regulation of endothelial cell chemotaxis to fibroblast growth factor | (4) | + | -
positive regulation of mast cell chemotaxis | (4) | + | -
regulation of atrial cardiac muscle cell action potential | (4) | + | -
regulation of cell migration involved in sprouting angiogenesis | (4) | + | -
negative regulation of cellular extravasation | (3) | + | -
negative regulation of endothelial cell chemotaxis to vascular endothelial growth factor | (3) | + | -
negative regulation of leukocyte chemotaxis | (3) | + | -
negative regulation of macrophage migration | (3) | + | -
negative regulation of motor neuron migration | (3) | + | -
negative regulation of muscle filament sliding | (3) | + | -
positive regulation of cardiac neural crest cell migration involved in outflow tract morphogenesis | (3) | + | -
positive regulation of glial cell migration | (3) | + | -
positive regulation of mesenchymal stem cell migration | (3) | + | -
positive regulation of metanephric mesenchymal cell migration by platelet-derived growth factor receptor-beta signaling pathway | (3) | + | -
positive regulation of monocyte extravasation | (3) | + | -
positive regulation of retinal ganglion cell axon guidance | (3) | + | -
positive regulation of retrograde axon cargo transport | (3) | + | -
positive regulation of substrate-dependent cell migration, cell attachment to substrate | (3) | + | -
positive  regulation of voltage-gated potassium channel activity involved in  ventricular cardiac muscle cell action potential repolarization | (3) | + | -
positive regulation of wound healing, spreading of epidermal cells | (3) | + | -
regulation of chemokine activity | (3) | + | -
regulation of endothelial cell chemotaxis to fibroblast growth factor | (3) | + | -
regulation of hematopoietic stem cell migration | (3) | + | -
regulation of lymphocyte migration | (3) | + | -
regulation of macrophage chemotaxis | (3) | + | -
regulation of neutrophil migration | (3) | + | -
regulation of photoreceptor cell axon guidance | (3) | + | -
chemorepulsion involved in interneuron migration from the subpallium to the cortex | (2) | + | -
negative regulation of Schwann cell migration | (2) | + | -
negative regulation of anterograde synaptic vesicle transport | (2) | + | -
negative regulation of cell chemotaxis to fibroblast growth factor | (2) | + | -
negative regulation of distal tip cell migration | (2) | + | -
negative regulation of glial cell migration | (2) | + | -
negative regulation of keratinocyte migration | (2) | + | -
negative regulation of natural killer cell chemotaxis | (2) | + | -
positive regulation of B cell chemotaxis | (2) | + | -
positive regulation of T cell extravasation | (2) | + | -
positive regulation of apical constriction involved in ventral furrow formation | (2) | + | -
positive regulation of cardiac muscle cell contraction | (2) | + | -
positive regulation of cell migration by vascular endothelial growth factor signaling pathway | (2) | + | -
positive regulation of eosinophil chemotaxis | (2) | + | -
positive regulation of eosinophil migration | (2) | + | -
positive regulation of hematopoietic stem cell migration | (2) | + | -
positive regulation of hepatic stellate cell migration | (2) | + | -
positive regulation of intraciliary anterograde transport | (2) | + | -
positive regulation of intraciliary retrograde transport | (2) | + | -
positive regulation of lymphocyte migration | (2) | + | -
positive regulation of macrophage migration | (2) | + | -
positive regulation of metanephric mesenchymal cell migration | (2) | + | -
positive regulation of thymocyte migration | (2) | + | -
regulation of T cell chemotaxis | (2) | + | -
regulation of angioblast cell migration involved in selective angioblast sprouting | (2) | + | -
regulation of anterograde synaptic vesicle transport | (2) | + | -
regulation of bacterial-type flagellum-dependent cell motility by regulation of motor speed | (2) | + | -
regulation of cell motility involved in somitogenic axis elongation | (2) | + | -
regulation of intraciliary retrograde transport | (2) | + | -
regulation of leukocyte tethering or rolling | (2) | + | -
regulation of lymphocyte chemotaxis | (2) | + | -
regulation of macrophage migration | (2) | + | -
regulation of muscle filament sliding | (2) | + | -
regulation of muscle filament sliding speed | (2) | + | -
regulation of neutrophil extravasation | (2) | + | -
canonical Wnt signaling pathway involved in positive regulation of endothelial cell migration | (1) | + | -
maintenance of ciliary planar beating movement pattern | (1) | + | -
negative regulation of T cell extravasation | (1) | + | -
negative regulation of border follicle cell migration | (1) | + | -
negative regulation of cell migration in other organism | (1) | + | -
negative regulation of cell motility involved in cerebral cortex radial glia guided migration | (1) | + | -
negative regulation of dendritic cell chemotaxis | (1) | + | -
negative regulation of eosinophil extravasation | (1) | + | -
negative regulation of eosinophil migration | (1) | + | -
negative regulation of hematopoietic stem cell migration | (1) | + | -
negative regulation of hepatic stellate cell contraction | (1) | + | -
negative regulation of hepatic stellate cell migration | (1) | + | -
negative regulation of lymphocyte chemotaxis | (1) | + | -
negative regulation of membrane repolarization during ventricular cardiac muscle cell action potential | (1) | + | -
negative regulation of metanephric mesenchymal cell migration | (1) | + | -
negative regulation of microglial cell migration | (1) | + | -
negative regulation of monocyte extravasation | (1) | + | -
negative regulation of mononuclear cell migration | (1) | + | -
negative regulation of muscle cell chemotaxis toward tendon cell | (1) | + | -
negative regulation of neuroblast migration | (1) | + | -
negative regulation of neutrophil migration | (1) | + | -
negative regulation of plus-end directed microtubule sliding | (1) | + | -
negative regulation of retinal ganglion cell axon guidance | (1) | + | -
negative regulation of ventricular cardiac muscle cell action potential | (1) | + | -
positive regulation of CD8-positive, alpha-beta T cell extravasation | (1) | + | -
positive regulation of CD8-positive, alpha-beta cytotoxic T cell extravasation | (1) | + | -
positive regulation of Schwann cell chemotaxis | (1) | + | -
positive regulation of actin filament-based movement | (1) | + | -
positive regulation of amoeboid sperm motility | (1) | + | -
positive regulation of anterograde axonal transport of mitochondrion | (1) | + | -
positive regulation of astrocyte chemotaxis | (1) | + | -
positive regulation of atrial cardiac muscle cell action potential | (1) | + | -
positive regulation of axo-dendritic protein transport | (1) | + | -
positive regulation of cilium beat frequency involved in ciliary motility | (1) | + | -
positive regulation of cilium movement | (1) | + | -
positive regulation of fibroblast chemotaxis | (1) | + | -
positive regulation of fibronectin-dependent thymocyte migration | (1) | + | -
positive regulation of hepatic stellate cell contraction | (1) | + | -
positive regulation of lateral motor column neuron migration | (1) | + | -
positive regulation of myeloid dendritic cell chemotaxis | (1) | + | -
positive regulation of myofibroblast contraction | (1) | + | -
positive regulation of nuclear migration during mitotic telophase | (1) | + | -
positive regulation of retrograde dense core granule transport | (1) | + | -
positive regulation of vesicle transport along microtubule | (1) | + | -
positive  regulation of voltage-gated potassium channel activity involved in  atrial cardiac muscle cell action potential repolarization | (1) | + | -
regulation of CD8-positive, alpha-beta cytotoxic T cell extravasation | (1) | + | -
regulation of Schwann cell migration | (1) | + | -
regulation of astrocyte chemotaxis | (1) | + | -
regulation of axo-dendritic protein transport | (1) | + | -
regulation of cardiac neural crest cell migration involved in outflow tract morphogenesis | (1) | + | -
regulation of cellular extravasation | (1) | + | -
regulation of dendritic cell chemotaxis | (1) | + | -
regulation of glial cell migration | (1) | + | -
regulation of granulocyte chemotaxis | (1) | + | -
regulation of mast cell chemotaxis | (1) | + | -
regulation of microglial cell migration | (1) | + | -
regulation of monocyte chemotaxis | (1) | + | -
regulation of motor neuron migration | (1) | + | -
regulation of myofibroblast contraction | (1) | + | -
regulation of neuroblast migration | (1) | + | -
regulation of nuclear migration along microtubule | (1) | + | -
regulation of thymocyte migration | (1) | + | -
regulation of trophoblast cell migration | (1) | + | -
regulation  of voltage-gated potassium channel activity involved in ventricular  cardiac muscle cell action potential repolarization | (1)

**Comment by pgaudet** [comment]
Is chromosome segregation really the same type of process ??

**Comment by ValWood** [comment]
No but the parentage of these terms seems odd.

I would not call "cell migration" a "cellular component migration"
But a term fo "cell migration" make *Much* more sense.

Does it really need a "cellular component migration" parent?

**Comment by ValWood** [comment]
For example, our annotation is coming from the parentage of

ase1 GO:0062168    negative regulation of plus-end directed microtubule sliding

but I agree with you that these are totally different things.

**Comment by ValWood** [comment]
rlc1 is from
positive regulation of actin filament-based movement (GO:1903116)

and

GO:1902854    positive regulation of nuclear migration during mitotic telophase

which is quite a random selection of things which  could go under a "cellular component movement" term

**Comment by pgaudet** [comment]
I think the issue arises from the non-regulatory term 'regulation of cellular component movement' refers to, ie 'GO:0006928 movement of cell or subcellular component', which groups cellular and non-cellular movement. We want to split these for the BP refactoring;

- [x] GO:0048870 cell motility: removed parents: 
-is_a: GO:0006928 ! movement of cell or subcellular component
-is_a: GO:0040011 ! locomotion
- 'part of' some 'localization of cell'
-
Need to fix: 
* 'localization of cell' -> obsolete, single annotation 
* 'horizontal cell localization' -> obsolete 1 UniProt annotation (removed, phenotype) 
* 'oocyte localization involved in germarium-derived egg chamber formation' -> move under cell adhesion?

**Comment by pgaudet** [comment]
- [x] GO:0051640 organelle localization : remove parent 'cellular localization'
- [x]'GO:0051305 chromosome movement towards spindle pole' -> change genera in LD from 'establishment of localization in cell' to 'localization'
- [x] GO:0007018 'microtubule-based movement': remove DL ('movement of cell or subcellular component'
 and ('process has causal agent' some microtubule)) & remove subclass: 'movement of cell or subcellular component'
 (keep subclass 'microtubule-based process')

**Comment by pgaudet** [comment]
- [ ] GO:0030036 'actin cytoskeleton organization' > remove parent 'actin filament-based process', since the actin filement is the target, not a participant, in the process
- [ ] same for GO:0000226 'microtubule cytoskeleton organization'

**Comment by pgaudet** [comment]
- [ ] GO:0099111 'microtubule-based transport': remove parent 'movement of cell or subcellular component' (keep LD: transport  and ('process has causal agent' some microtubule)
- [ ] GO:0099118 'microtubule-based protein transport': remove parent 'movement of cell or subcellular component' (keep LD: transport
 and ('process has causal agent' some microtubule)
 and ('has primary input' some protein)

**Comment by ValWood** [comment]
Do we even need the term "actin-filament based process"

if we have
actin filament organization (GO:0007015)
and cytoskeleton ofganization

**Comment by pgaudet** [comment]
probably not - but that may be a different ticket ...

**Comment by pgaudet** [comment]
- [x] GO:0097485 neuron projection guidance: 
 axon guidance is a developmental process (see for example https://pubmed.ncbi.nlm.nih.gov/29759980/)
so I will move GO:0097485 neuron projection guidance out of GO:0006928 movement of cell or subcellular component' and under 'GO:0031175 neuron projection development'

**Comment by pgaudet** [comment]
- [ ] GO:0099129 'cochlear outer hair cell electromotile response': move as is_a 'actin-mediated cell contraction' (see PMID:16887876)

**Comment by pgaudet** [comment]
- [x] cilium movement: change LD genera from  'movement of cell or subcellular component' to 'microtubule-based movement, since this was already asserted.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0006928 movement of cell or subcellular component
and its regulation terms: 
*  GO:0051270 regulation of cellular component movement
*   GO:0051271 negative regulation of cellular component movement
*  GO:0051272 positive regulation of cellular component movement

The reason for obsoletion is that the term mixes cellular and subcellular processes.

- The term 'movement of cell or subcellular component' is in the PIR subset (@hdrabkin can you please let Darren know?) 
- There are 38 EXP annotations (all to regulation terms), see annotations in https://github.com/geneontology/go-annotation/issues/4087
- There are no mappings to these terms. 

Thanks, Pascale
