### ISSUE TITLE
Review subclass relations remaining/missing after regulates-part-of changes

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#20069]
We removed the `regulates o part_of` property chains in #18653.

**Relationships (possibly indirect) which you were not removed by deleting the property chain, but which you may want to remove from the ontology somehow:**

 - [x] http://purl.obolibrary.org/obo/GO_0051963 regulation of synapse assembly SubClassOf http://purl.obolibrary.org/obo/GO_0044087 regulation of cellular component biogenesis
regulation of synapse assembly is_a regulation of cellular component biogenesis
-> created new parent, regulation of cellular component assembly, made GO_0051963 regulation of synapse assembly a descendant
-> fixed 'regulation of biological process assembly' branch: changed genera from biological_process to 'biological regulation'
-> removed statements such as 'relationship: regulates GO:0044085 ! cellular component biogenesis' -> the terms are is_a regulation of biogenesis/assembly, they do  not regulate it
 - [x]  http://purl.obolibrary.org/obo/GO_0090235 SubClassOf http://purl.obolibrary.org/obo/GO_0010564
regulation of metaphase plate congression is_a regulation of cell cycle process OK? Yes 
 - [x]  http://purl.obolibrary.org/obo/GO_0099161 SubClassOf http://purl.obolibrary.org/obo/GO_0023051
regulation of presynaptic dense core granule exocytosis is_a regulation of signaling -> **NO, removed**
 - [x]  http://purl.obolibrary.org/obo/GO_1903932 SubClassOf http://purl.obolibrary.org/obo/GO_0090329 -> **NO, removed**
    GO:1903932  regulation of DNA primase activity is_a    regulation of DNA-dependent DNA replication
 - [x]  http://purl.obolibrary.org/obo/GO_1904259 SubClassOf http://purl.obolibrary.org/obo/GO_0045995
regulation of basement membrane assembly involved in embryonic body morphogenesis 
regulates some 'embryo development' -> **OK **
 - [x]  http://purl.obolibrary.org/obo/GO_1905226 SubClassOf http://purl.obolibrary.org/obo/GO_0043903
regulation of adhesion of symbiont to host epithelial cell
regulation of biological process involved in symbiotic interaction **OK**
 - [x]  http://purl.obolibrary.org/obo/GO_1905557 SubClassOf http://purl.obolibrary.org/obo/GO_0007346
regulation of mitotic nuclear envelope disassembly
regulation of mitotic nuclear division **OK ???**
This is because 'mitotic nuclear envelope disassembly' is a 'mitotic nuclear division' - should it not be part of ? 
 - [x]  http://purl.obolibrary.org/obo/GO_1905558 SubClassOf http://purl.obolibrary.org/obo/GO_0010639
negative regulation of mitotic nuclear envelope disassembly is a 
negative regulation of organelle organization 
-> This is because GO:0051784 negative regulation of nuclear division is_a 'negative regulation of organelle organization'
I think this is wrong. Removed
 - [x]  http://purl.obolibrary.org/obo/GO_1905558 SubClassOf http://purl.obolibrary.org/obo/GO_0045930
negative regulation of mitotic nuclear envelope disassembly
is_a negative regulation of mitotic cell cycle
 - [x]  http://purl.obolibrary.org/obo/GO_1905559 SubClassOf http://purl.obolibrary.org/obo/GO_0010638
positive regulation of mitotic nuclear envelope disassembly **OK**
is_a positive regulation of organelle organization 
 - [x]  http://purl.obolibrary.org/obo/GO_2000535 SubClassOf http://purl.obolibrary.org/obo/GO_0043903
regulation of entry of bacterium into host cell
regulation of biological process involved in symbiotic interaction
Yes, indirect

**Relationships (possibly indirect) which you were removed by deleting the property chain, but which you may want to add back somehow (either directly or by adding a regulates relation):**

 - [x] http://purl.obolibrary.org/obo/GO_0044127 SubClassOf http://purl.obolibrary.org/obo/GO_0043903
regulation of development of symbiont in host
is_a regulation of biological process involved in symbiotic interaction -> OK
 - [ ]  http://purl.obolibrary.org/obo/GO_0046928 SubClassOf http://purl.obolibrary.org/obo/GO_0060341
regulation of neurotransmitter secretion
is_a regulation of cellular localization
shouldn't this be at the level of: secretion is_a cellular localization ? if this relation does not exist, then regulation should not add it
 - [ ]  http://purl.obolibrary.org/obo/GO_0051611 SubClassOf http://purl.obolibrary.org/obo/GO_0060341
regulation of serotonin uptake
is_a  regulation of cellular localization
same as GO_0046928 above
 - [x]  http://purl.obolibrary.org/obo/GO_0051802 SubClassOf http://purl.obolibrary.org/obo/GO_0043903
regulation of cytolysis in other organism involved in symbiotic interaction
is_a regulation of biological process involved in symbiotic interaction should be 
Looks like problem is 'GO:0051883' killing of cells in other organism involved in symbiotic interaction should be 
is_a GO:0044403 biological process involved in symbiotic interaction
 - [ ]  http://purl.obolibrary.org/obo/GO_0051940 SubClassOf http://purl.obolibrary.org/obo/GO_0060341
regulation of catecholamine uptake involved in synaptic transmission
is_a  regulation of cellular localization
same as GO_0046928 above
 - [ ]  http://purl.obolibrary.org/obo/GO_0051941 SubClassOf http://purl.obolibrary.org/obo/GO_0060341
regulation of amino acid uptake involved in synaptic transmission
is_a  regulation of cellular localization
same as GO_0046928 above
 - [ ]  http://purl.obolibrary.org/obo/GO_0150044 SubClassOf http://purl.obolibrary.org/obo/GO_0060341
regulation of amino acid uptake involved in synaptic transmission
is_a  regulation of cellular localization
same as GO_0046928 above
 - [x]  http://purl.obolibrary.org/obo/GO_0060694 SubClassOf http://purl.obolibrary.org/obo/GO_0032374
regulation of cholesterol transporter activity
is a regulation of cholesterol transport
-> no, for other transport we have a part_of relation, which is consistent with ShEx
Fixed BP
 - [x]  http://purl.obolibrary.org/obo/GO_0075184 SubClassOf http://purl.obolibrary.org/obo/GO_0043903
regulation of infection cushion formation
is_a regulation of biological process involved in symbiotic interaction
was already added
 - [ ]  http://purl.obolibrary.org/obo/GO_0099145 SubClassOf http://purl.obolibrary.org/obo/GO_0033157
regulation of exocytic insertion of neurotransmitter receptor to postsynaptic membrane 
is_a regulation of intracellular protein transport -> 
this is_a protein_localization to the cell periphery, so not sure transport is right ?? 
 - [ ]  http://purl.obolibrary.org/obo/GO_0099145 SubClassOf http://purl.obolibrary.org/obo/GO_0051128
regulation of exocytic insertion of neurotransmitter receptor to postsynaptic membrane
is_a regulation of cellular component organization 
probably not ? 
 - [x]  http://purl.obolibrary.org/obo/GO_1903548 SubClassOf http://purl.obolibrary.org/obo/GO_0048519
negative regulation of growth hormone activity  
is_a negative regulation of biological process **no**  shuld be inferred

 - [x]  http://purl.obolibrary.org/obo/GO_1905407 SubClassOf http://purl.obolibrary.org/obo/GO_1903789
regulation of creatine transmembrane transporter activity
is_a  regulation of amino acid transmembrane transport
-> OK ?  is_a modified amino acid transmembrane transporter activity
BUT modified amino acid transport is not an amino acid transport.  Is 'modified amino acid transport' a good grouping class for GO ? We dont care how compound were made before being transported, do we ? 

 - [x]  http://purl.obolibrary.org/obo/GO_1905408 SubClassOf http://purl.obolibrary.org/obo/GO_0051956
negative regulation of creatine transmembrane transporter activity
is_a negative regulation of amino acid transport
No, see GO_1905407 above

 - [x]  http://purl.obolibrary.org/obo/GO_1905409 SubClassOf http://purl.obolibrary.org/obo/GO_0051957
positive regulation of creatine transmembrane transporter activity
is_a positive regulation of amino acid transport
No, see GO_1905407 above

 - [x]  http://purl.obolibrary.org/obo/GO_1905598 SubClassOf http://purl.obolibrary.org/obo/GO_0048261
negative regulation of low-density lipoprotein receptor activity
is_a negative regulation of receptor-mediated endocytosis
-> OK added

 - [x]  http://purl.obolibrary.org/obo/GO_1905700 SubClassOf http://purl.obolibrary.org/obo/GO_2001024
negative regulation of xenobiotic detoxification by transmembrane export across the plasma membrane
is_a negative regulation of response to drug
-> OK added

 - [x]  http://purl.obolibrary.org/obo/GO_1905701 SubClassOf http://purl.obolibrary.org/obo/GO_2001025
positive regulation of xenobiotic detoxification by transmembrane export across the plasma membrane
is_a positive regulation of response to drug
-> OK added

**Comment by pgaudet** [comment]
Hi @ValWood 

We used to have this relation: 
GO_0090235  regulation of metaphase plate congression is_a GO_0010564 regulation of cell cycle process 
but in the non-regulatory branch of the ontology there is no link between metaphase plate congression and cell cycle process ; should there be ? (I see it in QuickGO but not in the ontology).

Thanks, Pascale

**Comment by ValWood** [comment]
Yes, metaphase plate congression is a cell cycle process.

**Comment by pgaudet** [comment]
ok thanks

**Comment by pgaudet** [comment]
Hi @ValWood 

regulation of mitotic nuclear envelope disassembly is_a 
regulation of mitotic nuclear division 
This is because 'mitotic nuclear envelope disassembly' is a 'mitotic nuclear division' - should it not be part of ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think part_of yes

**Comment by pgaudet** [comment]
@ValWood 
Are you OK with me removing 
GO:0051784 negative regulation of nuclear division is_a 'negative regulation of organelle organization' ?

**Comment by ValWood** [comment]
I guess so.

**Comment by pgaudet** [comment]
> I guess so.

I dont want to bully you into saying you ! If you think this relation was appropriate I'll keep it.

**Comment by pgaudet** [comment]
I understand what you mean. 

But more generally, organelle division and organelle organization should be disjoint processes (even if some components may be overlapping?)

**Comment by pgaudet** [comment]
I'll also remove 

 - [ ]  http://purl.obolibrary.org/obo/GO_1905558 SubClassOf http://purl.obolibrary.org/obo/GO_0045930
negative regulation of mitotic nuclear envelope disassembly
is_a negative regulation of mitotic cell cycle
 - [ ]  http://purl.obolibrary.org/obo/GO_1905559 SubClassOf http://purl.obolibrary.org/obo/GO_0010638
positive regulation of mitotic nuclear envelope disassembly
is_a positive regulation of organelle organization 

@ValWood unless you think those should remain

**Comment by pgaudet** [comment]
@ValWood 

>  Is it causing problems?

Not really, just those are 'leftover' from the removal of the regulates-part-of inference chain. 

According to @balhoff under regulation, all subclasses should be inferred based on the relation in the non-regulation part of the ontology. So for example if we decide 'nuclear envelope disassembly' is_a 'organelle organization' then this will be inferred in the regulation branch. 

However if it's a part_of, it should not become a is_a in the regulation branch. (Jim, correct me if this is not right).

Does that seem reasonable ?

**Comment by ValWood** [comment]
OK agreed!

**Comment by pgaudet** [comment]
I will not fix the others - for example one suggestion was to add 

> regulation of neurotransmitter secretion
is_a regulation of cellular localization

but in the non-regulation branch, 
serotonin uptake is_a establishment of localization which is **part_of** cellular localization 

Therefore regulation of uptake is not a regulation of localization. This is consistent.
