### ISSUE TITLE
Obsolete multi-organism process & 'multi-organism' descendant classes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21459]
Please provide as much information as you can:

* **GO term ID and Label**

- [x] GO:0051704 multi-organism process
- [x] GO:0044037   multi-organism cell wall macromolecule metabolic process
- [x] GO:0044703   multi-organism reproductive process -> see https://github.com/geneontology/go-ontology/issues/21459#issuecomment-964356769
- [x] GO:0044706   multi-multicellular organism process -> move directly under ''multicellular organismal process''
- [x] GO:0044764   multi-organism cellular process -> moved, see https://github.com/geneontology/go-ontology/issues/21459#issuecomment-964385817
- [x] GO:0044766   multi-organism transport
- [x] GO:0044800   multi-organism membrane fusion
- [ ] GO:0044803   multi-organism membrane organization -see https://github.com/geneontology/go-ontology/issues/21459#issuecomment-964353168
- [x] GO:1902539   multi-organism macropinocytosis
- [x] GO:1902541   multi-organism micropinocytosis
- [x] GO:1902579   multi-organism localization
- [x] GO:1902581   multi-organism cellular localization
- [x] GO:1902590   multi-organism organelle organization
- [x] GO:1902594   multi-organism nuclear import

* **Reason for deprecation**
This is not a biologically meaningful grouping class. See also #21432

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:
positive regulation of multi-organism process: 6
multi-organism membrane organization: 4
multi-organism cellular process: 1

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
* No

* **Is this term in a subset? (check the AmiGO page for that term)**
GO:0051704 multi-organism process: goslim_pir

* **Any other information**

**Comment by pgaudet** [comment]
GO:0044803 multi-organism membrane organization - removed 3 annotations, and disputed annotated to PMID:19376974 in P2GO

**Comment by pgaudet** [comment]
- [x] GO:0044703 multi-organism reproductive process -> removed GO:0051704 ! multi-organism process parent; keep only GO:0022414 ! reproductive process. 
- [ ] Need to open another ticket to see if other terms need to be changed

**Comment by pgaudet** [comment]
'multi-organism cellular process'

remove LD 'cellular process' and ('bearer of' some 'multi-organismal process quality')

and add 'cellular process' as a subclass. This keeps the children under the term 'multi-organism cellular process': 
conjugation
'genetic transfer'
'maintenance of stationary phase'
'multi-organism membrane organization'
'myxococcal fruiting body development'
'quorum sensing'

**Comment by pgaudet** [comment]
Regarding  GO:0044803 multi-organism membrane organization - removed 3 annotations, and disputed annotated to PMID:19376974 in P2GO


Hi Ruth, 


I just discussed this with @pmasson55  
The annotations to 'viral RNA genome replication' are incorrect; the virus induces host cells to form intracellular vesicles so it can hide its RNA to avoid degradation, and this allows it to not die and replicate. But the genes have nothing directly to do with replication.
We propose to create 2 terms: 
>> For viral proteins: reorganization of host cellular membranes to establish sites of replication
as a child of biological process involved in interaction with host'

>> For host proteins: reorganization of cellular membranes to establish viral sites of replication
as a child of biological process involved in interaction with symbiont'
The paper doesn't show which viral protein induced the host membranes to reorganize. But you could annotate the host proteins to 'reorganization of cellular membranes to establish viral sites of replication' 
would that work? 

Thanks, Pascale

**Comment by RLovering** [comment]
yes of course, very happy to follow the advice above, please let me know when the term is available
Best
Ruth

**Comment by pgaudet** [comment]
- [ ] obsoleted GO:0044803 multi-organism membrane organization
- [ ] removed parent 'GO:0044764 multi-organism cellular process' from ' GO:0046812 host cell surface binding'

**Comment by pgaudet** [comment]
- [x] GO:0030583 myxococcal fruiting body development -> move under developmental process  @pfey03 
- [x] GO:0009372 quorum sensing : remove GO:0044764 multi-organism cellular process; keep detection of cell density and cell-cell signaling

**Comment by pgaudet** [comment]
Will propose obsoletion of 
* GO:0060274 maintenance of stationary phase
*  GO:0060275 maintenance of stationary phase in response to starvation
* GO:0060276 maintenance of stationary phase in response to toxin 
4 annotations in total + 1 InterPro IPR023034

**Comment by pgaudet** [comment]
Will propose obsoletion of GO:0000748 conjugation with mutual genetic exchange
Single annotation to PMID:14871944 that mentions hyphal morphogenesis  but not conjugation

**Comment by pgaudet** [comment]
- [ ] parasexual conjugation with cellular fusion -> add parent 'reproduction' 
- [ ]  GO:0009292 genetic transfer -> move under 'cellular process'

**Comment by pfey03** [comment]
GO:0030583 myxococcal fruiting body development -> move under developmental process - fine with me, far away from sorocarp development that is under  GO:0048856 anatomical structure development

**Comment by pgaudet** [comment]
- [ ] will propose obsoletion of 'conjugation' as a grouping class 
- [ ] will be able to GO:0044764 multi-organism cellular process

**Comment by ValWood** [comment]
Yes we use these terms in extensions, but I agree that they do not really belong in GO as defined because they are describing a population.
The best alternative for us to represent "stationary phase" is
GO:0036227  mitotic G2 cell cycle arrest in response to glucose starvation 
 - [ ] please can you add related synonym "stationary phase"

**Comment by pfey03** [comment]
Can this be used when a protein is necessary to move from mound to ongoing development? So far we annotated to developmental terms in GO and specified the arrest in phenotypes.

**Comment by pgaudet** [comment]
> Can this be used when a protein is necessary to move from mound to ongoing development

This is a different process, it's more like quiescence. The entire Dicty development could be considered a 'quiescent' phase, I am not sure 1. why specifically you would annotate mound formation defects, and 2. why you would not annotate with the Dicty development ontology, which is more accurate in this case?

**Comment by pgaudet** [comment]
@ValWood you prefer to stick to obsoletion? I thought Jurg wanted to keep this term.

**Comment by pfey03** [comment]
It was just a loose question. If a gene/protein is really involved in the signaling for chemotaxis, aggregation or sporulation I annotate these GO terms typically and that's fine. We annotate more details as phenotypes anyway for several years.

**Comment by ValWood** [comment]
I agree with Petra. We will continue to annotate these phenotypes because the community require them.  But here we are not describing the normal role of a gene product, we are describing the consequences of mutants (decreased/increased/abolished phosphorylation etc, attached to alleles, not to genes), it's a completely different data type. This isn't in the scope of GO annotation, but it is still necessary curation for MODs (mainly for researchers actively working on the detailed characterization of a gene who need a record of the consequences of loss of/gain of function consequences of different variants). e.g. https://www.pombase.org/term/FYPO:0002494 

I like @vanaukenk suggestion that these phenotypes can probably be defined logically by uPHENO using  PRO terms, I had wondered about this but had not been able to figure out what would be missing from the design pattern.

**Comment by ValWood** [comment]
This comment was in the wrong ticket!

**Comment by ValWood** [comment]
Jurg did want to keep the term,  but I'm still I'm not convinced it is an actual 'phase' and not a stress response (checkpoint). I think it is OK to keep if we make it available for yeast and bacteria (I thought this was going to be a bacterial specific term).
I still think a name like 'cell dormancy stage' defined as any stage where  'a cell exit from the cell cycle'
might be more appropriate than stationary phase, with 'stationary phase' as a related synonym (because of the population issue).

We can  discuss when we finalize the ageing changes.

**Comment by pgaudet** [comment]
for now, I will move the 2 remaining children of  GO:0044764  multi-organism cellular process and obsolete GO:0044764 
* [GO:0000746 conjugation](http://amigo.geneontology.org/amigo/term/GO:0000746#display-lineage-tab) -> under 'reproduction'
* [GO:0060274 maintenance of stationary phase](http://amigo.geneontology.org/amigo/term/GO:0060274#display-lineage-tab) -> under 'homeostatic process 

These 2 terms will be addressed in separate tickets.
