### ISSUE TITLE
Add missing children to 'ATP-dependent activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21619]
Terms with labels 'ATP-dependent x': 

- [x] ATP-dependent NAD(P)H-hydrate dehydratase activity' <http://purl.obolibrary.org/obo/GO_0047453>
- [x] 'ATP-dependent farnesol kinase activity' <http://purl.obolibrary.org/obo/GO_0102237> -> need to merge into 'GO:0052668 farnesol kinase activity' - https://github.com/geneontology/go-ontology/issues/21619#issuecomment-864008766 renamed ADP:farnesol kinase activity
- [x] 'ATP-dependent microtubule motor activity' <http://purl.obolibrary.org/obo/GO_1990939>  -> was OK 
- [x] 'ATP-dependent microtubule motor activity, minus-end-directed' <http://purl.obolibrary.org/obo/GO_0008569>  -> was OK 
- [x] 'ATP-dependent microtubule motor activity, plus-end-directed' <http://purl.obolibrary.org/obo/GO_0008574>  -> was OK 
- [x] 'ATP-dependent peptidase activity' <http://purl.obolibrary.org/obo/GO_0004176> -> was OK 
- [x] 'ATP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity' <http://purl.obolibrary.org/obo/GO_0046404> -> remove ATP-dependent, this is a kinase
- [x] 'ATP-dependent polynucleotide kinase activity' <http://purl.obolibrary.org/obo/GO_0051734>
- [x] 'ATP-dependent polyribonucleotide 5'-hydroxyl-kinase activity' <http://purl.obolibrary.org/obo/GO_0051736>
- [ ] 'ATP-dependent protein binding' <http://purl.obolibrary.org/obo/GO_0043008> -> obsolete? 
- [x] 'ATP-dependent protein-DNA complex displacement activity' <http://purl.obolibrary.org/obo/GO_0061995>
- [x] 'ATP-dependent protein-nucleic acid complex displacement activity' <http://purl.obolibrary.org/obo/GO_0061994>

Look at separately
- [x] 'ATP-dependent RNA helicase inhibitor activity' <http://purl.obolibrary.org/obo/GO_1990119>
- [ ] 'ATP-dependent chaperone mediated protein folding' <http://purl.obolibrary.org/obo/GO_0061992>
- [x] 'ATP-dependent chromatin remodeling' <http://purl.obolibrary.org/obo/GO_0043044> done in #21732
- [ ] 'ATP-dependent citrate lyase complex' <http://purl.obolibrary.org/obo/GO_0140615> OK complex capable of 'GO:0003878 ATP citrate synthase activity' 
- [x]  'ATP-dependent methionine-importing complex' <http://purl.obolibrary.org/obo/GO_1990197>

**Comment by pgaudet** [comment]
- [ ] ATP-dependent NAD(P)H-hydrate dehydratase activity' http://purl.obolibrary.org/obo/GO_0047453 NOT ATP hydrolysis because there is is no water involved.

**Comment by pgaudet** [comment]
- [ ] 'GO:0102237 ATP-dependent farnesol kinase activity' <http://purl.obolibrary.org/obo/> 0 annotations ->  3-way merge into 'GO:0052668 farnesol kinase activity'   & GO:0052669 CTP:2-trans,-6-trans-farnesol kinase activity
EC:2.7.1.216, since EC describes the reaction with 2,6-trans: CTP + (2E,6E)-farnesol <=> CDP + (2E,6E)-farnesyl phosphate (https://enzyme.expasy.org/EC/2.7.1.216)

**Comment by alanbridge** [comment]
Not sure if it's a good idea to merge the ATP and CTP forms of this reaction. 

(2E,6E)-farnesol + CTP = (2E,6E)-farnesyl phosphate + CDP + H(+)
(2E,6E)-farnesol + ATP = (2E,6E)-farnesyl phosphate + ADP + H(+)

I seem to remember the rat enzyme uses CTP not ATP, plant uses both. I guess we may find species that only use ATP later. Why not do a CTP-dependent and an ATP-dependent GO term?  

'ATP-dependent farnesol kinase activity'
'CTP-dependent farnesol kinase activity'

or even 

'ATP-dependent (2E,6E)-farnesol kinase activity'
'CTP-dependent (2E,6E)-farnesol kinase activity'

**Comment by pgaudet** [comment]
OK - Paul and I thought we should merge because EC describes the CTP version, and states "The enzyme, found in plants and animals, can also use other nucleotide triphosphates as phosphate donor, albeit less efficiently. "

https://enzyme.expasy.org/EC/2.7.1.216

I'll look for more evidence.

**Comment by pgaudet** [comment]
The difference between plant and human seems to be the substrate, not the nucleoide used, according to the same EC entry: "The plant enzyme can also use geraniol and geranylgeraniol as substrates with lower activity, but not farnesyl phosphate (cf. EC 2.7.4.32). "

**Comment by alanbridge** [comment]
I was kind of worried we would have to demerge these later and remap to the 2 Rheas. I scanned the article on rat, fig 5 shows activity only for CTP there: https://reader.elsevier.com/reader/sd/pii/S0003986198906117?token=4FC6B771CD1EB4F58D921BC03E3479BC8241708875C512B62DE0059C634C98E04EA09C7DA9CC387F94125C52723266A3&originRegion=eu-west-1&originCreation=20210618115956. 

I would be interested to know why this kinase is using CTP but I'm in meetings all afternoon so can't follow it up! There must be something to that though. This alone might be a good reason for a CTP-specific term?

**Comment by pgaudet** [comment]
We now have 2 terms for farnesol kinase activity: 

GO:0052668
-name: farnesol kinase activity
+name: CTP:farnesol kinase activity 
RHEA: 51680

----

 id: GO:0102237
-name: ATP-dependent farnesol kinase activity
+name: ATP:farnesol kinase activity
RHEA:61656

both cite the plant paper PMID:21395888

Looks like the tobacco gene is specific for CTP (PMID:10557276) and the Arabidosis gene can use other nucleotides 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/4782928/122561751-843de580-d042-11eb-82c5-544f8e1812bb.png">


So I will keep both terms.

**Comment by alanbridge** [comment]
thanks!

**Comment by pgaudet** [comment]
- [x] 'ATP-dependent RNA helicase inhibitor activity' <http://purl.obolibrary.org/obo/GO_1990119>
- [ ] -> change label to RNA helicase inhibitor activity

**Comment by pgaudet** [comment]
- [ ]  'ATP-dependent methionine-importing complex' <http://purl.obolibrary.org/obo/GO_1990197> 
-> change label to methionine-importing ABC transporter complex
