### ISSUE TITLE
Missing parent: [mannosyltransferases , various]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22675]
<img width="740" alt="Screenshot 2022-01-17 at 13 54 56" src="https://user-images.githubusercontent.com/7359272/149781459-30b21485-dd50-44ac-af50-86f606ac0d5a.png">

It looks like:
- [ ] GO:0102704 should be is_a  GO:0004376
- [ ] GO:0102704 should be is_a GO:0000009
- [x] GO:0004378 should be is_a GO:0000033

I am picking up mappings to the less specific terms which would be  filtered as redundant if these relationships were present.

At least , I assume this is correct because  some terms like
GO:0052925 
dol-P-Man:Man(5)GlcNAc(2)-PP-Dol alpha-1,3-mannosyltransferase activity
are under the respective "alpha-1,3-mannosyltransferase activity"

**Comment by ValWood** [comment]
added
GO:0102704 should be is_a GO:0000009
some done here
https://github.com/geneontology/go-ontology/issues/28262
