### ISSUE TITLE
Missing parent: [Polyadenylation should be part-of  RNA 3' end processing?]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22708]
Polyadenylation should be part-of  RNA 3' end processing?

This relationship was deleted in 2015, but poly adenylation IS part of 3' end processing
2015-05-11 | Deleted | RELATION | is a GO:0031123 (RNA 3'-end processing)

Quote:
"
Image result for polyadenylation and end processing
Introduction: Polyadenylation is the process in which the pre-mRNA is cleaved at the poly(A) site and a poly(A) tail is added – a process necessary for normal mRNA formation."

https://www.frontiersin.org/articles/10.3389/fendo.2013.00053/full
first line of abstract.

(I spotted this because  FYPO phenotype[es are arranged according to GO and  our abnormal polyadenylation terms are not under abnormal  3' end-processing)

Does anyone recollect why this was removed?

**Comment by ValWood** [comment]
OK
https://github.com/geneontology/go-ontology/issues/6189

I think the problem lies in the definition of 
RNA processing as
Any process involved in the conversion of one or more primary RNA transcripts into one or more mature RNA molecules.

but RNA processing often occurs on transcripts that are destined immediately for degradation (as @krchristie said in the ticket where. the parent was removed). However, this does not fix the issue that

many polyadenylated (processed RNAs) are never transcribed but are destined immediately for degradation.

**Comment by ValWood** [comment]
Here is an example of a molecule that is polyadenylated 
For instance https://www.pombase.org/reference/PMID:34389684

Although this does seem to be a standard definition for RNA processing : RNA processing is the term collectively used to describe the sequence of events through which the primary transcript from a gene acquires its mature form.  
I guess we could add "the mature form incudes RNA molecules which are polyadenylated and targeted for immediate  destruction via the  
nonfunctional RNA decay pathways"?

**Comment by ValWood** [comment]
Juan Mata
https://www.bioc.cam.ac.uk/research/mata
who works on RNA decay thinks that polyadenylation should be part of RNA processing, and that the current definition  is correct.

**Comment by pgaudet** [comment]
I think we should 


- [ ] obsolete GO:0043631 RNA polyadenylation (24 EXP) so that people annotate either 
* GO:0006378 mRNA polyadenylation (is_a GO:0031124 mRNA 3'-end processing, so that addresses your point above) 
* GO:0043629 ncRNA polyadenylation
* GO:0039698 polyadenylation of viral mRNA by polymerase stuttering 

- [ ] obsolete     GO:0140235 RNA polyadenylation at postsynapse (process + localization) - 0 annotations
* GO:0043630 ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process: 
- [ ] change parent to  is_a GO:0034661 ncRNA catabolic process
- [ ] change term label to 'ncRNA quality control for aberrantly modified ncRNAs'
- [ ] same for  GO:0098812 nuclear rRNA polyadenylation involved in polyadenylation-dependent rRNA catabolic process
- [ ] This would allow to move  GO:0043629 ncRNA polyadenylation under 'GO:0043628 ncRNA 3'-end processing'

Does that work? 


Thanks, Pascale

**Comment by ValWood** [comment]
HI @pgaudet , I am not sure .... ncRNA polyadenylation and mRNA polyadenylation  uses the same pathway

It seems like a bigger project to sort this out so that the annotations can be represented consistently in GO_CAMs. Perhaps implement  these suggestions, but keep the grouping term  'RNA polyadenylation' for the substrate specific terms because it would seem odd not to have the subtypes united by a common parent representing the pathway.

**Comment by krchristie** [comment]
I believe polyadenylation also occurs in bacteria, so make sure that whatever is done works for bacteria too.

**Comment by ValWood** [comment]
covered by https://github.com/geneontology/go-ontology/issues/24924
(almost the same solution)

**Comment by ValWood** [comment]
Actually https://github.com/geneontology/go-ontology/issues/24924 will resolve so we don't need this ticket

**Comment by ValWood** [comment]
changed closed status
