### ISSUE TITLE
Missing part_of relation for: GO:0098868 bone growth

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22940]
The following part-of relation is missing in GO.

_GO:0098868 bone growth_	
part_of	
_GO:0060348 bone development_

However, GO currently has the following similar part-of relation.
_GO:0060437 lung growth_ 
part_of 
_GO:0030324 lung development_

**Comment by raymond91125** [comment]
Growth (of an organ) should always be part_of Development (of an organ). Is there a way to make the relationships by reasoning? @pgaudet

**Comment by pgaudet** [comment]
Hi, 

How about if we changed the logical definitions of the high level terms: 

- [ ] developmental growth: (had no LD)
- add growth
and 'part of' some 'developmental process'
- remove asserted classes is_a growth and is_a developmental process'
- [ ] organ growth: remove asserted classes is_a growth
- [ ] bone growth: remove asserted classes is_a growth
- [ ] heart growth: from genera from growth to developmental growth
 - keep and ('results in growth of' some heart)
 - remove asserted class is_a organ growth
- [ ] imaginal disc growth
 - remove asserted class is_a organ growth
- [ ] lung growth: from genera from growth to developmental growth
 - keep  and ('results in growth of' some lung)
 - [ ] lprostate gland growth: from genera from growth to developmental growth
 - keep    and ('results in growth of' some 'prostate gland')

**Comment by raymond91125** [comment]
@pgaudet incorporated all changes of your but cannot get the inference bone growth part_of bone development.
Must we manually assert? Thanks.

**Comment by pgaudet** [comment]
Hi @raymond91125 
Right now it's not possible to make a logical definition that will make the required inferences. 

Can you please assert 'x growth' part of 'x development? 


Thanks, Pascale
