### ISSUE TITLE
peroxidase/peroxiredoxin activity issues

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23121]
Current tree looks like this:
```
oxidoreductase activity, acting on peroxide as acceptor
           |__peroxidase activity
               |__bromide peroxidase activity
               |__catalase activity
               |__chloride peroxidase activity
               |__cytochrome-c peroxidase activity
               |__diarylpropane peroxidase activity
               |__fatty acid peroxidase activity
               |__glutathione peroxidase activity
               |__iodide peroxidase activity
               |__L-ascorbate peroxidase activity
               |__manganese peroxidase activity
               |__NADH peroxidase activity
               |__NADPH peroxidase activity
               |__reactive-black-5:hydrogen-peroxide oxidoreductase activity
               |__thiocyanate peroxidase activity
               |__thioredoxin peroxidase activity
               |__tryparedoxin peroxidase activity
           |__peroxiredoxin activity
               |__peroxynitrite reductase activity
               |__thioredoxin peroxidase activity
               |__tryparedoxin peroxidase activity
```

Looks like peroxidase activity used to have specific xref to EC:1.11.1.7/RHEA:56136, but it's now a grouping term equivalent to EC:1.11.1.- (which is it's current xref).

I think the following changes should be considered (let me know if you'd prefer separate tickets):

==

- [x] id: GO:0004601

name: peroxidase activity
def: "Catalysis of the reaction: donor + hydrogen peroxide = oxidized donor + 2 H2O." [GOC:curators]
xref: EC:1.11.1.-

=> this is a grouping terms for all peroxidases (consistent with the xref to EC:1.11.1.-), so change definition to something like "Catalysis of the reaction: donor + a peroxide = oxidized donor + 2 H2O." (see https://en.wikipedia.org/wiki/Peroxidase)
=> 

- [ ] consider adding new child term specifically for EC:1.11.1.7/RHEA:56136

==

- [ ] id: GO:0051920

name: peroxiredoxin activity
def: "Catalysis of the reaction: 2 R'-SH + ROOH = R'-S-S-R' + H2O + ROH." [EC:1.11.1.15, RHEA:10008]
comment: Includes redox chemistry as part of the catalytic reaction (2 R'-SH = R'-S-S-R'), where R' refers to peroxiredoxin itself). Not to be confused with GO:0004601 (peroxidase activity, EC:1.11.1.7), which has a different reaction mechanism.
synonym: "AhpC activity" NARROW []
synonym: "alkyl hydroperoxide reductase C22 activity" NARROW []
synonym: "PRDX activity" EXACT []
synonym: "Prx activity" EXACT []
synonym: "thiol-containing-reductant:hydroperoxide oxidoreductase activity" RELATED [EC:1.11.1.15]
xref: EC:1.11.1.24
xref: MetaCyc:1.11.1.15-RXN
xref: Reactome:R-HSA-1222431 "Peroxynitrite is reduced to nitrite by AhpC"
xref: Reactome:R-HSA-1222755 "Peroxynitrite is reduced to nitrite by Tpx"
xref: Reactome:R-HSA-1500804 "Peroxynitrite is reduced by AhpE"
xref: RHEA:10008
is_a: GO:0016209 ! antioxidant activity
is_a: GO:0016684 ! oxidoreductase activity, acting on peroxide as acceptor

=> this is a grouping term for specific types of peroxiredoxins
=> keep xref to RHEA:10008
- [x] but remove xref to EC:1.11.1.24 (which is RHEA:62620) and references to EC:1.11.1.15 (which is obsolete and transferred to EC:1.11.1.24 anyway) (#22598)
- [x] also remove xref to MetaCyc:1.11.1.15-RXN
- review synonyms and Reactome xrefs
- [x] removed 
* "AhpC activity" NARROW []
* synonym: "alkyl hydroperoxide reductase C22 activity" NARROW []
* thiol-containing-reductant:hydroperoxide oxidoreductase activity"
- [ ] Reactome needs to review their annotations (this is how they become xrefs)

- [x] change "is_a: GO:0016684 ! oxidoreductase activity, acting on peroxide as acceptor" parent to "is_a: GO:0004601 ! peroxidase activity" 
- [x] make new child term for "Thioredoxin-dependent peroxiredoxin activity" with xrefs EC:1.11.1.24 and RHEA:62620

==

- [x] id: GO:0072541

name: peroxynitrite reductase activity
def: "Catalysis of the reaction: 2 R-SH + ONOO- = R-SS-R + NO2- + H2O." [GOC:rs, PMID:11001062]
comment: Note that this activity is usually associated in vivo with an NADPH-dependent disulfide reductase activity, so that catalysis of the reduction of peroxynitrite to nitrite involves the possible creation of oxygen or water, using NADPH as reduction equivalent.
synonym: "peroxynitritase activity" EXACT [GOC:rs]
is_a: GO:0051920 ! peroxiredoxin activity

=> Don't think this should be a child of "peroxiredoxin activity"; change to be child of "peroxidase activity"?

==

- [x] id: GO:0008379

name: thioredoxin peroxidase activity
def: "Catalysis of the reaction: thioredoxin + hydrogen peroxide = thioredoxin disulfide + H2O." [RHEA:63528]
synonym: "thiol peroxidase activity" EXACT []
synonym: "TPx activity" EXACT []
synonym: "TrxPx activity" EXACT []
xref: MetaCyc:RXN0-267
xref: Reactome:R-HSA-2161612 "PGH2 is reduced to PGF2a by FAM213B"
xref: Reactome:R-HSA-3322995 "PRDX3,5 catalyze TXN2 reduced + H2O2 => TXN2 oxidized + 2H2O"
xref: Reactome:R-HSA-3341343 "PRDX1,2,5 catalyze TXN reduced + H2O2 => TXN oxidized + 2H2O"
xref: Reactome:R-HSA-3697882 "PRDX5 reduces peroxynitrite to nitrite using TXN"
xref: Reactome:R-HSA-3697894 "PRDX5 reduces peroxynitrite to nitrite using TXN2"
xref: RHEA:63528
is_a: GO:0004601 ! peroxidase activity
is_a: GO:0051920 ! peroxiredoxin activity

- [x] remove "is_a: GO:0051920 ! peroxiredoxin activity" parent

==

- [x] id: GO:0033196

name: tryparedoxin peroxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: tryparedoxin + hydrogen peroxide = tryparedoxin disulfide + H2O." [GOC:mah]
synonym: "TXNPx activity" EXACT []
xref: MetaCyc:1.11.1.15-RXN
is_a: GO:0004601 ! peroxidase activity
is_a: GO:0051920 ! peroxiredoxin activity

- [x] remove "is_a: GO:0051920 ! peroxiredoxin activity" parent

==

- [x] id: GO:0102039

name: alkylhydroperoxide reductase activity
def: "Catalysis of the reaction: H2O + NAD + an alcohol <=> NADH + H+ + an organic hydroperoxide." [GOC:pz, PMID:12517450]
xref: EC:1.11.1.26
xref: MetaCyc:R4-RXN
is_a: GO:0016668 ! oxidoreductase activity, acting on a sulfur group of donors, NAD(P) as acceptor

- [x] change name to "NADH-dependent peroxiredoxin activity" to match EC
- [x] change parent to "peroxiredoxin activity GO:0051920"
- [x] add RHEA:62628 xref

**Comment by hdrabkin** [comment]
I realize that this is not straightforward because of the number of annotations made to the proposed new  'grouping' terms which would need to be changed. 
GO:0004601 has 358  annotations with experimental evidence
I assume that in most cases, what was annotated is the actual suggested new term new child term specifically for EC:1.11.1.7/RHEA:56136. 

The same holds for id: GO:0051920,, which has 74 annotations with experimental evidence which I assume again would need to be transferred to the new suggested child term.

**Comment by sjm41** [comment]
Thanks Harold.  Just to clarify - I'm not proposing any new 'grouping' terms here, just pointing out that some existing terms _are_ grouping terms, and that their def/xrefs/children need updating to reflect that.

I agree with this:
_I suppose leaving them all temporarily to the term made a grouping term would not make them all incorrect; just not specific enough. However, the annotations would still need to be transferred eventually to the level intended_
Some of the existing annotations may be intended at the 'grouping level', so folks would have to review which EXP they wanted to move to the more specific child.

**Comment by sjm41** [comment]
Hi @hdrabkin Are we OK to proceed with the plan above?

**Comment by deustp01** [comment]
@hdrabkin  I don't see any reason not to proceed with the plan.

An important caveat is that I don't know much about these reactions and sensible ways to classify them.

**Comment by sjm41** [comment]
In https://github.com/geneontology/go-ontology/issues/22598, @kaxelsen points to the fuller info about EC:1.11.1.15 shown on the IUBMB website - copied below.  I think this confirms that GO:0051920 "peroxiredoxin activity GO:0051920" is a grouping term in the GO - so we need to remove its current EC 1.11.1.24 xref and make a new child GO term specifically for  EC 1.11.1.24

(https://www.enzyme-database.org/query.php?ec=1.11.1.15)
EC | 1.11.1.15
Transferred entry: | peroxiredoxin. Now described by:
- EC 1.11.1.24, thioredoxin-dependent peroxiredoxin;  <= need to create this as new child of GO:0051920 (see previous note)
- EC 1.11.1.25, glutaredoxin-dependent peroxiredoxin;  <= not in GO, ignore
- EC 1.11.1.26, NADH-dependent peroxiredoxin;  <= need to change parent and add RHEA:62628 xref (see previous note)
- EC 1.11.1.27, glutathione-dependent peroxiredoxin;  <= not in GO, ignore
- EC 1.11.1.28, lipoyl-dependent peroxiredoxin;  <= not in GO, ignore
- EC 1.11.1.29, mycoredoxin-dependent peroxiredoxin <= not in GO, ignore

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140825
+name: lactoperoxidase activity
+def: "Catalysis of the reaction: 2 a phenolic donor + H2O2 = 2 a phenolic radical donor + 2 H2O." [PMID:19339248, RHEA:56136]
+synonym: "peroxidase activity" BROAD []
+xref: EC:1.11.1.7
+xref: RHEA:56136
+is_a: GO:0004601 ! peroxidase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23121 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-18T14:39:20Z

**Comment by pgaudet** [comment]
Hi @deustp01 

See @sjm41 's sugestion above (in the initial comment) - you may want to review Reactome annotations to GO:0051920. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks for your work on this Pascale!

**Comment by sjm41** [comment]
@pgaudet 
I was just looking at this term again in [RHEA](https://www.rhea-db.org/rhea/63528):
**id: GO:0008379**
name: thioredoxin peroxidase activity
def: "Catalysis of the reaction: thioredoxin + hydrogen peroxide = thioredoxin disulfide + H2O." [RHEA:63528]
xref: RHEA:63528
is_a: GO:0004601 ! peroxidase activity

I see that RHEA classifies this as a specific form (child) of this GO/RHEA (which makes sense):
**id: GO:0140824**
name: thioredoxin-dependent peroxiredoxin activity
def: "Catalysis of the reaction: [thioredoxin]-dithiol + a hydroperoxide = [thioredoxin]-disulfide + an alcohol + H2O." [PMID:12707274, PMID:19820102, RHEA:62620]
xref: EC:1.11.1.24
xref: RHEA:62620
is_a: GO:0051920 ! peroxiredoxin activity


So I think we need to make these two changes:
- [ ] change the def of GO:0008379 to "Catalysis of the reaction: [thioredoxin]-dithiol + hydrogen peroxide = [thioredoxin]-disulfide + H2O." to match RHEA and GO:0140824
- [ ] change the parent of GO:0008379 to GO:0140824 thioredoxin-dependent peroxiredoxin activity
