### ISSUE TITLE
TPv nucleus-vacuole junction assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23242]
nucleus-vacuole junction assembly
has the parent
piecemeal microautophagy of the nucleus](https://www.pombase.org/term/GO:0034727)
but this is not always true.

The nucleus-vacuole junction is not only involved in autophagy.

https://www.pnas.org/doi/10.1073/pnas.1701030114

**Comment by ValWood** [comment]
i.e. it is also involved in 
vacuole fusion , non-autophagic
https://www.yeastgenome.org/locus/S000000739#go

**Comment by pgaudet** [comment]
FYI @ukemi @RLovering @marcfeuermann 

- [ ] I removed the relationship part_of GO:0034727 ! piecemeal microautophagy of the nucleus 
- [ ] I added to the definition (bold face text): The aggregation, arrangement and bonding together of a set of components to form a nucleus-vacuole junction (NVJ), membrane contact sites formed between the vacuole membrane and the outer nuclear membrane. In S. cerevisiae these contacts are mediated through direct physical interaction between Vac8p and Nvj1p. **NVJ play roles in piecemeal microautophagy of the nucleus and in the cytoplasm-to-vacuole targeting pathway.**
- [ ] Added reference mentioned above PMID:28533415

Thanks, Pascale
