### ISSUE TITLE
leukotriene-C(4) hydrolase (GO:0002951)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23253]
id: GO:0002951
name: leukotriene-C(4) hydrolase
def: "Catalysis of the reaction Leukotriene C(4) + H(2)O= leukotriene D(4) + L-glutamate." [EC:3.4.19.14, PMID:9774450]
comment: The mouse enzyme is specific for leukotriene C(4), while the human enzyme also has considerable activity toward glutathione and oxidized glutathione (cf. EC:3.4.19.13). PMID:9774450 cites that the mouse form of this enzyme failed to measure activity towards glutathione.
is_a: GO:0070122 ! isopeptidase activity

- [x] Add ec xref 3.4.19.14

- [x] add rhea xref [RHEA:31563](https://www.rhea-db.org/rhea/31563)

- [x] change to /add parent GO:0008242 omega peptidase activity (that has EC xref: EC:3.4.19.-)

**Comment by sjm41** [comment]
Thanks!  The change log suggests that the RHEA xref was not added as an xef?

**Comment by pgaudet** [comment]
thanks for picking that up ! I made a new PR.
