### ISSUE TITLE
Missing parent: [GO term] GO:0019359	nicotinamide nucleotide biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23285]
* **GO term ID and label for which you request a new superclass**

GO:0019360	nicotinamide nucleotide biosynthetic process from niacinamide
Is a descendant of 
GO:0006769	nicotinamide metabolic process
But currently
GO:0019359	nicotinamide nucleotide biosynthetic process
Is not

see:
<img width="494" alt="Screenshot 2022-05-08 at 14 54 51" src="https://user-images.githubusercontent.com/7359272/167299643-a922a45e-bc66-44a6-a326-46316397d670.png">

**Comment by pgaudet** [comment]
Looks like we have some unnecessary terms in this branch that add to the confusion. There seem to be 2 do novo pathways:

* ''de novo' NAD biosynthetic process from tryptophan' -> vertebrate pathway, see PMID: 17161604
* ''de novo' NAD biosynthetic process from aspartate' -> bacterial pathway, see https://ecocyc.org/gene?orgid=ECOLI&id=NAD-SYNTH-MONOMER#tab=RXNS


- [x] merge 'GO:0019355 nicotinamide nucleotide biosynthetic process from aspartate' into its unique child GO:0034628
    'de novo' NAD biosynthetic process from aspartate ->  there is no 'salvage pathway from aspartate (0 annotations, all annotations are to 'de novo' NAD biosynthetic process from aspartate')

- [x]  obsolete 'nicotinamide nucleotide biosynthetic process from niacinamide': niacinamide is nicotinamide (see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17154). There is no annotations, no reference for this term, no mappings. Nicotinamide is an intermediate in some pathways, other pathways have some nicotinate derivative, see
* * https://ecocyc.org/ECOLI/NEW-IMAGE?object=PYRIDNUCSYN-PWY&redirect=T
* * https://ecocyc.org/ECOLI/NEW-IMAGE?type=PATHWAY&object=PYRIDNUCSYN-PWY
* * https://ecocyc.org/ECOLI/NEW-IMAGE?type=PATHWAY&object=PWY-7761
but this doesn't look like a useful grouping term. It could be merged up or obsoleted.

**Comment by pgaudet** [comment]
- [x] Likewise, I cannot find any evidence that GO:0019356 nicotinate nucleotide biosynthetic process from tryptophan exists - the tryptophan pathway leads to NAD+ , (and also PMID:18429699, PMC5398323 and PMID:32122523), only Nicotinic Acid Salvage Pathway PMC5521000 - obsolete?  No annotations

**Comment by pgaudet** [comment]
@ValWood the reason why the relation is different is because of the 'from niacinamide' in GO:0019360 nicotinamide nucleotide biosynthetic process from niacinamide

- _nicotinamide nucleotide metabolism_ is not necessarily a _nicotinamide metabolism_ this is correct but confusing, and unnecessary, see https://github.com/geneontology/go-ontology/issues/23285#issuecomment-1120738824)

**Comment by sjm41** [comment]
This looks like it's resolved - suggested merges and obsoletions have been done.

So I'll close.
