### ISSUE TITLE
Wrong parent: GDP-D-glucose phosphorylase activity GO:0080048 / GDP-L-galactose phosphorylase activity GO:0080047

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23283]
* **GO term ID and label for which you request a new superclass**
GDP-D-glucose phosphorylase activity GO:0080048 = EC:2.7.7.78
GDP-L-galactose phosphorylase activity GO:0080047 = EC:2.7.7.69

Current parent on both terms is:
1,4-alpha-oligoglucan phosphorylase activity GO:0004645 = EC:2.4.1.1, which is inconsistent with the above xrefs.

* **New superclass (parent) suggested**
guanylyltransferase activity GO:0070568
(which is itself a child of GO:0016779 nucleotidyltransferase activity = EC:2.7.7.-)

**Comment by sjm41** [comment]
Actually, looks like these are term merges:

name: GDP-D-glucose phosphorylase activity
def: "Catalysis of the reaction: GDP-D-glucose + phosphate = D-glucose-1-P + GDP." [PMID:18463094]
xref: EC:2.7.7.78
xref: MetaCyc:RXN-12486
xref: RHEA:30387
is_a: GO:0004645 ! 1,4-alpha-oligoglucan phosphorylase activity

is same as:

id: GO:0010474
name: glucose-1-phosphate guanylyltransferase (GDP) activity
def: "Catalysis of the reaction: GDP + D-glucose 1-phosphate = phosphate + GDP-glucose." [PMID:17462988]
synonym: "GDP:glucose-1-phosphate guanyltransferase activity" EXACT []
is_a: GO:0070568 ! guanylyltransferase activity

==

id: GO:0080047
name: GDP-L-galactose phosphorylase activity
def: "Catalysis of the reaction: GDP-L-galactose + phosphate = L-galactose-1-P + GDP." [EC:2.7.7.69, PMID:18463094]
xref: EC:2.7.7.69
xref: MetaCyc:RXNQT-4141
xref: RHEA:27698
is_a: GO:0004645 ! 1,4-alpha-oligoglucan phosphorylase activity

is same as:

id: GO:0010475
name: galactose-1-phosphate guanylyltransferase (GDP) activity
def: "Catalysis of the reaction: GDP + L-galactose 1-phosphate = phosphate + GDP-galactose." [PMID:17462988]
synonym: "GDP:galactose-1-phosphate guanyltransferase activity" EXACT []
is_a: GO:0070568 ! guanylyltransferase activity

**Comment by pgaudet** [comment]
These are showing reactions in opposite directions, right ? (just to make sure... ) 

yes I'll merge this. 

Thanks, Pascale

**Comment by sjm41** [comment]
_These are showing reactions in opposite directions, right ? (just to make sure... )_
Yep, though the '=' sign in the definitions suggests they are bidirectional anyway.
Thanks for fixing!

**Comment by pgaudet** [comment]
- [x] GO:0010472 name: GDP-galactose:glucose-1-phosphate guanylyltransferase activity: 
added [RHEA:65712](https://www.rhea-db.org/rhea/65712) 
- [x] GO:0010471 GDP-galactose:mannose-1-phosphate guanylyltransferase activity
added [RHEA:65708](https://www.rhea-db.org/rhea/65708)



- [x] GO:0004475: change label to mach definition
-name: mannose-1-phosphate guanylyltransferase activity
+name: mannose-1-phosphate guanylyltransferase (GTP) activity
- [x] GO:0047351 CHnaged label to match sibling classes
-name: guanosine-triphosphate guanylyltransferase activity
+name: GTP guanylyltransferase activity
