### ISSUE TITLE
Updates to GO:0004657 proline dehydrogenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23335]
Current entry (only showing relevant fields):

id: GO:0004657
name: proline dehydrogenase activity
def: "Catalysis of the reaction: L-proline + acceptor = (S)-1-pyrroline-5-carboxylate + reduced acceptor." [EC:1.5.99.8]
synonym: "L-proline dehydrogenase activity" RELATED [EC:1.5.99.8]
synonym: "L-proline:(acceptor) oxidoreductase activity" RELATED [EC:1.5.99.8]
synonym: "L-proline:acceptor oxidoreductase activity" RELATED [EC:1.5.99.8]
xref: EC:1.5.99.8
xref: RHEA:23784
is_a: GO:0016645 ! oxidoreductase activity, acting on the CH-NH group of donors

- [x] Change EC xref to [1.5.5.2](https://enzyme.expasy.org/EC/1.5.5.2)
- [x] Change def and synonym references to [1.5.5.2](https://enzyme.expasy.org/EC/1.5.5.2) or RHEA:23784
- [x] change parent to GO:0016649 "oxidoreductase activity, acting on the CH-NH group of donors, quinone or similar compound as acceptor" (EC:1.5.5.-)
