### ISSUE TITLE
Fix acyl-CoA dehydrogenase activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23497]
**GO:0003995 acyl-CoA dehydrogenase activity:** 
- [x] change parent
 -is_a: GO:0016627 ! oxidoreductase activity, acting on the CH-CH group of donors
+is_a: GO:0052890 ! oxidoreductase activity, acting on the CH-CH group of donors, with a flavin as acceptor
- [x] remove synonyms that correspond to more specific activities
-synonym: "acyl-CoA:(acceptor) 2,3-oxidoreductase activity" RELATED [EC:1.3.99.3]
-synonym: "acyl-CoA:acceptor 2,3-oxidoreductase activity" RELATED [EC:1.3.99.3]
-synonym: "fatty acyl coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
-synonym: "fatty-acyl-CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
-synonym: "general acyl CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
-synonym: "long-chain acyl coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
-synonym: "long-chain acyl-CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
-synonym: "medium-chain acyl-CoA dehydrogenase activity" NARROW [EC:1.3.99.3]
-synonym: "medium-chain acyl-coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
- [x] remove all references to EC:1.3.99.3 (deprecated)
- [x] Changed def from Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor." to "Catalysis of the reaction: acyl-CoA + oxidized [electron-transfer flavoprotein]= 2,3-dehydroacyl-CoA + reduced [electron-transfer flavoprotein]"

**Comment by pgaudet** [comment]
**GO:0004085 butyryl-CoA dehydrogenase activity**

- [x] changed parents 
-is_a: GO:0052890 ! oxidoreductase activity, acting on the CH-CH group of donors, with a flavin as acceptor
+is_a: GO:0003995 ! acyl-CoA dehydrogenase activity

**Comment by pgaudet** [comment]
**GO:0004361 glutaryl-CoA dehydrogenase activity**

- [x] changed def 
-def: "Catalysis of the reaction: glutaryl-CoA + acceptor = crotonoyl-CoA + CO2 + reduced acceptor." [EC:1.3.8.6]
+def: "3-methylbutanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = 3-methyl-(2E)-butenoyl-CoA + reduced [electron-transfer flavoprotein]." [RHEA:13389]

**Comment by pgaudet** [comment]
**GO:0004466 long-chain-acyl-CoA dehydrogenase activity**

- [x] changed def and def xref 
-def: "Catalysis of the reaction: acyl-CoA + ETF = 2,3-dehydroacyl-CoA + reduced ETF." [EC:1.3.8.8]
+def: "Catalysis of the reaction: a long-chain 2,3-saturated fatty acyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = a long-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]." [RHEA:17721]

**Comment by pgaudet** [comment]
**GO:0008470  isovaleryl-CoA dehydrogenase activity** 

- [x] Changed def & added defxref
-def: "Catalysis of the reaction: 3-methylbutanoyl-CoA + ETF = 3-methylbut-2-enoyl-CoA + reduced ETF." [EC:1.3.8.4]
+def: "Catalysis of the reaction: 3-methylbutanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = 3-methyl-(2E)-butenoyl-CoA + reduced [electron-transfer flavoprotein]." [PMID:25450250, PMID:7640268, RHEA:12276]

- [x] Added RHEA:12276 xref

**Comment by pgaudet** [comment]
[propionyl-CoA dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0043820)
obsolete & replace by [acryloyl-CoA reductase (NADH) activity](http://purl.obolibrary.org/obo/GO_0043958)

corresponds to the same reaction, according to https://www.uniprot.org/uniprotkb/G3KIM8/entry
