### ISSUE TITLE
GO:0033483 gas homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24224]
Hello, 

For the BP refactoring, we will split cellular and organism-level processes, as described in the [2022 bp refactoring plan - top level](https://docs.google.com/document/d/1k8yuWTMSkYVTnt2hRbrPVH8Ud3gDwC5IrGu4PqHkKds/edit). 

This ticket describes changes to the GO:0033483 gas homeostasis branch: 

- [x] obsolete GO:0033483 gas homeostasis: no annotations, unnecessary grouping term
- [x] GO:0033484 nitric oxide homeostasis -> move under GO:0055082 cellular chemical homeostasis
- [x] GO:0032364 oxygen homeostasis -> move under GO:0055082 cellular chemical homeostasis

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0033483 gas homeostasis. The reason for obsoletion is that this is an unnecessary grouping terms. Children have been moved under 'cellular chemical homeostasis'.  There are no annotations to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24224


Thanks, Pascale
