### ISSUE TITLE
Review 'Nuclease activity (GO:0004518)' parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24408]
Copying from comments from @pgaudet and @sjm41 in #15357:

While working on https://github.com/geneontology/go-ontology/issues/15308, I came across a wiki page that states that 'most nucleases are hydrolases' .. implying that they are not all nucleases:
https://en.wikipedia.org/wiki/Nuclease

Nuclease activity (GO:0004518) has the following comment: "Note that 'tRNA nucleotidyltransferase activity ; GO:0009022', also known as 'ribonuclease PH', and 'DNA-(apurinic or apyrimidinic site) lyase activity ; GO:0003906' do not have parentage in the 'nuclease activity' branch of the ontology because both GO and the Enzyme Commission define nuclease activity as a type of hydrolysis."

I propose to add more specific parents to children terms, based on the comment above.

> I think we'll need to remove the current parent-child relationship between 'hydrolase activity, acting on ester bonds (GO:0016788)' and 'nuclease activity (GO:0004518)'. Right?

Yes, nuclease activity would be directly under MF. More specific children could be hydrolases or others as appropriate.

![Screenshot 2022-11-21 at 14 04 14](https://user-images.githubusercontent.com/16306861/203074682-cc523732-d19c-48de-8af4-81d41e38c564.png)

**Comment by pgaudet** [comment]
equivalent terms: 
* GO:0008852  exodeoxyribonuclease I activity obsolete + replace by:  GO:0008310 single-stranded DNA 3'-5' exodeoxyribonuclease activity
* GO:0008853  exodeoxyribonuclease III activity   merge into  GO:0008311 double-stranded DNA 3'-5' exodeoxyribonuclease activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  GO:0008852 exodeoxyribonuclease I activity and GO:0008853 exodeoxyribonuclease III activity. The reason for obsoletion is that these terms are equivalent to  GO:0008310 single-stranded DNA 3'-5' exodeoxyribonuclease activity and  GO:0008311 double-stranded DNA 3'-5' exodeoxyribonuclease activity, respectively. 

Mappings to GO:0008852 and GO:0008853 will be moved to GO:0008310 and GO:0008311.

There is EXP annotation to each of these terms by EcoCyc. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24408

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
'GO:0016797 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 3'-phosphomonoesters' and 
'GO:0016796 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 5'-phosphomonoesters'. The reason for obsoletion is that these are unnecessary grouping classes that correspond to EC's with a single child. 

There are no EXP annotations or mappings to these terms. These terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24408


Thanks, Pascale

**Comment by pgaudet** [comment]
Change labels to simplify: 

- [ ] GO:0004521 ! endoribonuclease activity -> RNA endonuclease activity
- [ ] GO:0016892 ! endoribonuclease activity, producing 3'-phosphomonoesters -> RNA endonuclease activity, producing 3'-phosphomonoesters  
- [ ] GO:0016891 ! endoribonuclease activity, producing 5'-phosphomonoesters ->  RNA endonuclease activity, producing 5'-phosphomonoesters
- [ ] 

- [ ] GO:0035312  5'-3' exodeoxyribonuclease activity -> 5'-3' DNA exonuclease activity
- [ ] GO:0008296  3'-5'-DNA exonuclease activity
- [ ] GO:0000175  3'-5'-exoribonuclease activity -> 3'-5'-RNA exonuclease activity
- [ ] GO:0004529 exodeoxyribonuclease activity -> GO:0004529 ! DNA exonuclease activity
- [ ] GO:0016896 ! exoribonuclease activity, producing 5'-phosphomonoesters -> RNA exonuclease activity, producing 5'-phosphomonoesters
- [ ] GO:0004534 5'-3' exoribonuclease activity -> 5'-3' RNA exonuclease activity
- [ ] GO:0008310 single-stranded DNA 3'-5' exodeoxyribonuclease activity -> single-stranded DNA 3'-5' DNA exonuclease activity
- [ ] GO:0008311 double-stranded DNA 3'-5' exodeoxyribonuclease activity -> double-stranded DNA 3'-5' DNA exonuclease activity
- [ ] GO:0016897 exoribonuclease activity, producing 3'-phosphomonoesters -> RNA exonuclease activity, producing 3'-phosphomonoesters
- [ ] GO:0045145 single-stranded DNA 5'-3' exodeoxyribonuclease activity -> single-stranded DNA 5'-3' DNA exonuclease activity

**Comment by pgaudet** [comment]
Changed labels: 

- [ ] GO:0004532  exoribonuclease activity >>>  RNA exonuclease activity
- [ ] GO:0004540  ribonuclease activity >>>  RNA nuclease activity

**Comment by sjm41** [comment]
Looking at this issue today, I believe all of the remaining issues are associated with some RNA endonuclease terms that used to be classified by EC as hydrolasea (under EC:3.1.27.-) but were transferred to the lyase class (under EC:4.6.1.-):

https://enzyme.expasy.org/EC/3.1.27.-

ENZYME class: 3.1.27.-

3.-.-.-: Hydrolases
3.1.-.-: Acting on ester bonds
3.1.27.-: Endoribonucleases producing other than 5'-phosphomonoesters

3.1.27.1	Transferred entry: 4.6.1.19 -> GO:0033897
3.1.27.2	Transferred entry: 4.6.1.22 -> (no GO term)
3.1.27.3	Transferred entry: 4.6.1.24 -> GO:0046589
3.1.27.4	Transferred entry: 4.6.1.20 -> GO:0033899
3.1.27.5	Transferred entry: 4.6.1.18 -> GO:0004522
3.1.27.6	Transferred entry: 4.6.1.21 -> GO:0008847
3.1.27.7	ribonuclease F
3.1.27.8	ribonuclease V
3.1.27.9	Transferred entry: 4.6.1.16 -> GO:0000213
3.1.27.10	Transferred entry: 4.6.1.23 -> GO:0033902

**Comment by sjm41** [comment]
This is where those 7 RNA endonuclease terms in the current GO hierarchy (marked with asterisk):

```
hydrolase activity, acting on ester bonds (GO:0016788) [EC:3.1.-.-]
 |__nuclease activity (GO:0004518)
     |__RNA nuclease activity (GO:0004540)
         |__ribonuclease T1 activity* (GO:0046589) [EC:4.6.1.24]
         |__RNA endonuclease activity (GO:0004521)
             |__ribonuclease T2 activity* (GO:0033897) [EC:4.6.1.19]
             |__RNA endonuclease activity, producing 3'-phosphomonoesters (GO:0016892) [EC:3.1.27.-]
                 |__Enterobacter ribonuclease activity* (GO:0008847) [EC:4.6.1.21]
                 |__ribonuclease A activity* (GO:0004522) [EC:4.6.1.18]
                 |__ribonuclease F activity (GO:0033900) [EC:3.1.27.7]
                 |__ribonuclease U2 activity* (GO:0033899) [EC:4.6.1.20]
                 |__ribonuclease V activity (GO:0033901) [EC:3.1.27.8]
                 |__tRNA-intron endonuclease activity* (GO:0000213) [EC:4.6.1.16]
         |__rRNA endonuclease activity* (GO:0033902) [EC:4.6.1.23]
         |__tRNA-specific ribonuclease activity (GO:0004549)
             |__tRNA-intron endonuclease activity* (GO:0000213) [EC:4.6.1.16]
```


To fix the parentage issue,  I suggest we change the hierarchy to look like this:

```
hydrolase activity, acting on ester bonds [EC:3.1.-.-]
 |__nuclease activity (GO:0004518)
     |__RNA nuclease activity (GO:0004540)
         |__RNA endonuclease activity (GO:0004521)
             |__RNA endonuclease activity, producing 3'-phosphomonoesters (GO:0016892) [EC:3.1.27.-]
                 |__ribonuclease F activity (GO:0033900) [EC:3.1.27.7]
                 |__ribonuclease V activity (GO:0033901) [EC:3.1.27.8]
```

and

```
phosphorus-oxygen lyase activity [EC:4.6.1.-]
    |__RNA endonuclease activity, lyase mechanism (NTR)
         |__ribonuclease T1 activity* (GO:0046589) [EC:4.6.1.24]
         |__ribonuclease T2 activity* (GO:0033897) [EC:4.6.1.19]
         |__Enterobacter ribonuclease activity* (GO:0008847) [EC:4.6.1.21]
         |__ribonuclease A activity* (GO:0004522) [EC:4.6.1.18]
         |__ribonuclease U2 activity* (GO:0033899) [EC:4.6.1.20]
         |__tRNA-intron endonuclease activity* (GO:0000213) [EC:4.6.1.16]
         |__rRNA endonuclease activity* (GO:0033902) [EC:4.6.1.23]
```

Individual tasks:
- [ ] Make new grouping term for 'RNA endonuclease activity, lyase mechanism'
- [ ] Change parentage of the 7 EC:4.6.1.- RNA endonucleases terms to use that NTR
- [ ] Update GO:0033902 to use EC:4.6.1.23 as def xref
- [ ] add EC:4.6.1.- as a second EC xref on GO:0016849 phosphorus-oxygen lyase activity (it already has EC:4.6.-.-, but both ECs are correct xrefs)

TO DECIDE:
1. Should we re-label 'RNA endonuclease activity' (GO:0004521) as 'RNA endonuclease activity, hydrolytic mechanism'?
2. Do we want/need a general 'RNA endonuclease activity' parent that groups both mechanisms? (would be easier not to....)

**Comment by sjm41** [comment]
First, some tidying up (to help with the bigger task):

---

- [ ] Rename 'endodeoxyribonuclease activity, producing 5'-phosphomonoesters' (GO:0016888) to 'DNA endonuclease activity, producing 5'-phosphomonoesters' to be consistent with names of equivalent sister terms

---

- [ ] Move the following RNA endonuclease terms to the positions they should have been in if respecting their former EC:3.1.27.- designations (which will then group all the problematic terms together):
- ribonuclease T1 activity* (GO:0046589) [EC:4.6.1.24] (previously 3.1.27.3)
- ribonuclease T2 activity* (GO:0033897) [EC:4.6.1.19] (previously 3.1.27.1)
- rRNA endonuclease activity* (GO:0033902) [EC:4.6.1.23]

---

- [ ] Obsolete 'GO:0016796 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 5'-phosphomonoesters'
- this has xref EC:3.1.15.-, which has only one child in EC (EC 3.1.15.1 = venom exonuclease), which is not in GO
- but in GO, the two direct children of GO:0016796 are GO:0016896 (EC:3.1.13.-) and GO:0016895 (EC:3.1.11.-), which clearly conflicts with the EC hierarchy
- it has no direct annotations
- it's also an unnecessary grouping term in GO

---

- [ ] Obsolete 'GO:0016797 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 3'-phosphomonoesters'
- this has xref EC:3.1.16.-, which has only one child in EC (EC 3.1.16.1 = spleen exonuclease), which is not in GO
- GO:0016797 has no child terms in GO
- it has 2 direct annotations - ISM annotations from GeneDB based on InterPro:IPR006055 (which appears to be obsolete)

---

- [ ] Obsolete 'GO:0016893 endonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 5'-phosphomonoesters'
- this has xref EC:3.1.30.-, which has only two children in EC (EC 3.1.30.1 = Aspergillus nuclease S1 and EC 3.1.30.2 = Serratia marcescens nuclease), which are not in GO
- but in GO, the two direct children of GO:0016796 are GO:0016888 (EC:3.1.21.-) and GO:0016891 (EC:3.1.26.-), which clearly conflicts with the EC hierarchy
- it has no direct annotations
- it's also an unnecessary grouping term in GO

---

- [ ] Obsolete 'GO:0016894 endonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 3'-phosphomonoesters'
- this has xref EC:3.1.31.1, which is 'micrococcal nuclease', and is the only child of the EC grouping class EC:3.1.31.- (this is probably an error, and the intention was to use EC:3.1.31.- as the xref) 
- but in GO, the two direct children of GO:0016796 are GO:0016889 (EC:3.1.22.-) and GO:0016892 (EC:3.1.27.-), which clearly conflicts with the EC hierarchy
- it has 1,557 direct annotations, but these are all via EC:3.1.31.-
- it's also an unnecessary grouping term in GO
- the alternative option here would be to convert this term name and def to specifically reflect EC:3.1.31.1 = 'micrococcal nuclease', but that seems like a gene product and thus out of scope for GO

---

**Comment by sjm41** [comment]
I've now reworked the nuclease branch consistent with this plan:
>Need to keep/add hydrolysis/lyase parentage to individual GO terms/groups to be consistent with EC classification, whilst also preserving the 'nuclease activity' branch so that users can find all nucleases (or sub-types thereof) irrespective of whether the individual mechanisms.

Main changes:
- changed parent of 'nuclease activity' to 'catalytic activity, acting on a nucleic acid'
- add parent of 'phosphorus-oxygen lyase activity' to the seven EC:4.6.1.- RNA endonucleases terms mentioned above
- added parent of 'hydrolase activity, acting on ester bonds' to child groups/terms of 'nuclease activity' where appropriate/possible, to preserve EC hydrolase classification 
- removed several notes of the type "X does not have parentage in the 'nuclease activity' branch of the ontology because both GO and the Enzyme Commission define nuclease activity as a type of hydrolysis."
- made 'DNA-(apurinic or apyrimidinic site) lyase activity ; GO:0003906' a child of 'DNA endonuclease activity'

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: 

GO:0016796 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 5'-phosphomonoesters
GO:0016797 exonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 3'-phosphomonoesters
GO:0016893 endonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 5'-phosphomonoesters
GO:0016894 endonuclease activity, active with either ribo- or deoxyribonucleic acids and producing 3'-phosphomonoesters

The reason for obsoletion is that these are unnecessary grouping terms. There are no manual annotations to these terms. These terms are not present in any subsets.

As well as 
GO:0008946 oligonucleotidase activity
GO:0034610 oligodeoxyribonucleotidase activity
GO:0034611 oligoribonucleotidase activity

**Comment by deustp01** [comment]
What is the suggested replacement for GO:0034611 oligodeoxyribonucleotidase activity? Perhaps its parent [GO:0016896](https://www.ebi.ac.uk/QuickGO/term/GO:0016896) RNA exonuclease activity, producing 5'-phosphomonoesters?

**Comment by deustp01** [comment]
Clean-up suggestions for GO:0034611 oligoribonucleotidase activity at Reactome are fine. Reactome fixed.

**Comment by sjm41** [comment]
The following DNA endonuclease terms should have a parent of 'hydrolase activity, acting on ester bonds' added to preserve EC 'hydrolase' classification:

deoxyribonuclease (pyrimidine dimer) activity
- xref is EC:3.1.25.1

restriction endodeoxyribonuclease activity
- 3 of the 4 child terms have EC:3.1.21.- xrefs

retroviral 3' processing activity
- the def xref (PMID:22580823) talks about water molecules as nucleophile
