### ISSUE TITLE
Review children of GO:0004312 fatty acid synthase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24752]
Seems the children of GO:0004312 fatty acid synthase activity are a bit of a mess, as indicated by the mismatched EC xrefs (bold).

Here's the current tree:

acyltransferase activity (EC:2.3.-.-)
. . acyltransferase activity, transferring groups other than amino-acyl groups (EC:2.3.1.-)
. . . . fatty acid synthase activity (EC:2.3.1.85)
. . . . . . (3R)-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity (**EC:4.2.1.59**, recently removed)
. . . . . . 3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity (**EC:1.1.1.100**)
. . . . . . 3-oxoacyl-[acyl-carrier-protein] synthase activity (EC:2.3.1.41)
. . . . . . acyl-carrier-protein] S-acetyltransferase activity (EC:2.3.1.38)
. . . . . . acyl-carrier-protein] S-malonyltransferase activity (EC:2.3.1.39)
. . . . . . acyl-[acyl-carrier-protein] hydrolase activity (**EC:3.1.2.14**)
. . . . . . . . dodecanoyl-[acyl-carrier-protein] hydrolase activity (**EC:3.1.2.21**)
. . . . . . . . myristoyl-[acyl-carrier-protein] hydrolase activity (**EC:3.1.2.14**)
. . . . . . . . oleoyl-[acyl-carrier-protein] hydrolase activity (**EC:3.1.2.14**)
. . . . . . . . palmitoyl-[acyl-carrier-protein] hydrolase activity (**EC:3.1.2.14**)
. . . . . . enoyl-[acyl-carrier-protein] reductase (NADH) activity (**EC:1.3.1.9**)
. . . . . . enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity (**EC:1.3.1.10**)
. . . . . . fatty acid elongase activity (no EC)

Below are the action items IMO:

id: GO:0004317
name: (3R)-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-hydroxypalmitoyl-[acyl-carrier protein] = 2-hexadecenoyl-[acyl-carrier protein] + H2O." [PMID:8088535, RHEA:41908]
xref: RHEA:41908
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0004316
name: 3-oxoacyl-[acyl-carrier-protein] reductase (NADPH) activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-3-hydroxyacyl-[acyl-carrier protein] + NADP+ = 3-oxoacyl-[acyl-carrier protein] + NADPH + H+." [RHEA:17397]
xref: EC:1.1.1.100 {source="skos:exactMatch"}xref: MetaCyc:3-OXOACYL-ACP-REDUCT-RXN
xref: MetaCyc:RXN-10659 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-11476 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-11480 {source="skos:narrowMatch"}
xref: RHEA:17397 {source="skos:exactMatch"}
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0016297
name: acyl-[acyl-carrier-protein] hydrolase activity
namespace: molecular_function
alt_id: GO:0010281
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + H2O = [acyl-carrier protein] + a fatty acid." [EC:3.1.2.14, MetaCyc:RXN-7902]
xref: EC:3.1.2.14
xref: MetaCyc:RXN-7902
xref: RHEA:30131
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016790 ! thiolester hydrolase activity
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0004318
name: enoyl-[acyl-carrier-protein] reductase (NADH) activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NAD+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADH + H+." [EC:1.3.1.9]
xref: EC:1.3.1.9
xref: MetaCyc:ENOYL-ACP-REDUCT-NADH-RXN
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016628 ! oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0004319
name: enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NADP+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADPH + H+." [EC:1.3.1.10]
xref: EC:1.3.1.10
xref: MetaCyc:ENOYL-ACP-REDUCT-NADPH-RXN
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016628 ! oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0009922
name: fatty acid elongase activity
namespace: molecular_function
def: "Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer + 2-C)." [GOC:tb]
xref: MetaCyc:ICOSANOYL-COA-SYNTHASE-RXN
is_a: GO:0004312 ! fatty acid synthase activity
This def does not seem to be a subclass of "fatty acid synthase activity", which is defined as "Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+."
- [ ] change parent to "acyltransferase activity, transferring groups other than amino-acyl groups (EC:2.3.1.-)"??

id: GO:0004315
name: 3-oxoacyl-[acyl-carrier-protein] synthase activity
namespace: molecular_function
alt_id: GO:0033817
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + malonyl-[acyl-carrier protein] = 3-oxoacyl-[acyl-carrier protein] + CO2 + [acyl-carrier protein]." [RHEA:22836]
xref: EC:2.3.1.179 {source="skos:narrowMatch"}
xref: EC:2.3.1.41 {source="skos:exactMatch"}
xref: MetaCyc:2.3.1.179-RXN
xref: MetaCyc:3-OXOACYL-ACP-SYNTH-RXN
xref: RHEA:22836
is_a: GO:0004312 ! fatty acid synthase activity
This def does not seem to be a subclass of "fatty acid synthase activity", which is defined as "Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+."
- [x] change parent to "acyltransferase activity, transferring groups other than amino-acyl groups (EC:2.3.1.-)"??

id: GO:0004313
name: [acyl-carrier-protein] S-acetyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: acetyl-CoA + [acyl-carrier protein] = CoA + acetyl-[acyl-carrier protein]." [RHEA:41788]
xref: EC:2.3.1.38
xref: MetaCyc:ACP-S-ACETYLTRANSFER-RXN
xref: RHEA:41788
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016418 ! S-acetyltransferase activity
This def does not seem to be a subclass of "fatty acid synthase activity", which is defined as "Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+."
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

id: GO:0004314
name: [acyl-carrier-protein] S-malonyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: malonyl-CoA + [acyl-carrier protein] = CoA + malonyl-[acyl-carrier protein]." [EC:2.3.1.39]
xref: EC:2.3.1.39
xref: MetaCyc:MALONYL-COA-ACP-TRANSACYL-RXN
is_a: GO:0004312 ! fatty acid synthase activity
is_a: GO:0016419 ! S-malonyltransferase activity
This def does not seem to be a subclass of "fatty acid synthase activity", which is defined as "Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+."
- [x] remove is_a: GO:0004312 ! fatty acid synthase activity

**Comment by sjm41** [comment]
@pgaudet Thanks for the explanation and fixing all these.

I see there is one you didn't change - what were your thoughts on GO:0009922?:

id: GO:0009922
name: fatty acid elongase activity
namespace: molecular_function
def: "Catalysis of the reaction: fatty acid (C-16 or longer) + 2-C = fatty acid (C-16 or longer + 2-C)." [GOC:tb]
xref: MetaCyc:ICOSANOYL-COA-SYNTHASE-RXN
is_a: GO:0004312 ! fatty acid synthase activity
This def does not seem to be a subclass of "fatty acid synthase activity", which is defined as "Catalysis of the reaction: acetyl-CoA + n malonyl-CoA + 2n NADPH + 2n H+ = long-chain fatty acid + n+1 CoA + n CO2 + 2n NADP+."
- [ ] change parent to "acyltransferase activity, transferring groups other than amino-acyl groups (EC:2.3.1.-)"??
