### ISSUE TITLE
Transfered ECs still used in dbxrefs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24927]
- [x] 1.1.99.11 Transferred entry:  1.1.5.14    
- [x] 1.14.13.74  Transferred entry:  1.14.14.85    Done in #24838
- [x] 1.14.13.85  Transferred entry:  1.14.14.135       Done in #24841
- [x] 1.14.99.33  Transferred entry:  1.14.19.39     1 EC > 1 EC  (new EC not used)
- [x] 1.3.1.30  Transferred entry:  1.3.1.22     New EC used for a different GO term ->> see #25314 
- [x] 1.6.5.11  Transferred entry:  1.6.5.9      1 EC > 1 EC  (new EC not used)
- [ ] 1.8.99.3  Transferred entry:  1.8.99.5      1 EC > 1 EC  (new EC not used) fixed, see https://github.com/geneontology/go-ontology/issues/25448
- [ ] 2.4.1.164 Transferred entry:  2.4.1.150      New EC used for a different GO term >> obsolete https://github.com/geneontology/go-ontology/issues/27410
- [x] 2.4.99.1  Transferred entry:  2.4.3.1      see #25189
- [x] 2.4.99.2  Transferred entry:  2.4.3.2    see #25189
- [x] 2.4.99.3  Transferred entry:  2.4.3.3      see #25189
- [x] 2.4.99.4  Transferred entry:  2.4.3.4      see #25189
- [x] 2.4.99.5  Transferred entry:  2.4.3.5      see #25189
- [x] 2.4.99.6  Transferred entry:  2.4.3.6      see #25189
- [x] 2.4.99.7  Transferred entry:  2.4.3.7     see #25189
- [x] 2.4.99.8  Transferred entry:  2.4.3.8      see #25189
- [x] 2.4.99.9  Transferred entry:  2.4.3.9      see #25189
- [x] 2.4.99.10 Transferred entry:  2.4.99.6       see #25189
- [x] 2.4.99.11 Transferred entry:  2.4.99.1     see #25189
- [x] 2.7.7.58  Transferred entry:  6.2.1.71     1 EC > 1 EC (new EC not used)
- [x] 2.7.7.n1  Transferred entry:  2.7.7.108      Done in #25168

To check 
- [x] 3.2.1.47  Transferred entry:  3.2.1.22      - see https://github.com/geneontology/go-ontology/issues/25227
- [ ] 3.2.1.66  Transferred entry:  3.2.1.40     > Obsolete [quercitrinase activity](http://purl.obolibrary.org/obo/GO_0050245); replace by [alpha-L-rhamnosidase activity](http://purl.obolibrary.org/obo/GO_0030596); move RHEA:17465 to GO_0030596 (no annotations)
- [x] 3.3.1.2 Transferred entry:  3.13.2.2    Done in #25361
- [ ] 3.3.2.5 Transferred entry:  3.3.2.2     > Obsolete [alkenylglycerophosphoethanolamine hydrolase activity](http://purl.obolibrary.org/obo/GO_0047409) and replace by [alkenylglycerophosphocholine hydrolase activity](http://purl.obolibrary.org/obo/GO_0047408) (genes annotated to GO:0047409 are also annotated to GO:0047408)
- [x] 3.4.21.87 Transferred entry:  3.4.23.49 >> update xref in [serine-type endopeptidase activity](http://purl.obolibrary.org/obo/GO_0004252)
- [x] 3.5.3.19  Transferred entry:  3.5.1.116    >> fixed xref on [ureidoglycolate hydrolase activity](http://purl.obolibrary.org/obo/GO_0004848) + changed parent to [hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides](http://purl.obolibrary.org/obo/GO_0016811)
- [ ] 3.5.4.14  Transferred entry:  3.5.4.5    
- [x] 4.1.2.30  Transferred entry:  1.14.14.32
- [ ] 4.2.1.101 Transferred entry:  4.1.2.61  
- [x] 4.2.1.58  Transferred entry:  4.2.1.59      > was already removed; fixed hierarchy and old MetaCyc reactions in the [(3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity](http://purl.obolibrary.org/obo/GO_0019171) branch
- [x] 4.99.1.5  Transferred entry:  4.8.1.2    > updated [aliphatic aldoxime dehydratase activity](http://purl.obolibrary.org/obo/GO_0034013) and moved under GO:0141122 nitrogen-oxygen hydrolyase activity
- [x] 4.99.1.6  Transferred entry:  4.8.1.3      > updated [indoleacetaldoxime dehydratase activity](http://purl.obolibrary.org/obo/GO_0047720)  and moved under GO:0141122 nitrogen-oxygen hydrolyase activity
- [x] 4.99.1.7  Transferred entry:  4.8.1.4     > [phenylacetaldoxime dehydratase activity](http://purl.obolibrary.org/obo/GO_0018814)   and moved under GO:0141122 nitrogen-oxygen hydrolyase activity
- [ ] 5.4.3.4 Transferred entry:  5.4.3.3    : Obsolete     GO:0047702 beta-lysine 5,6-aminomutase activity (corresponds to EC:5.4.3.3); replace by  GO:0047826 D-lysine 5,6-aminomutase activity (corresponds to EC:5.4.3.4) (no annotations)

Merged reactions: 
- [ ] 4.4.1.6 Transferred entry:  4.4.1.13   DONE https://github.com/geneontology/go-ontology/issues/27410
- [ ] 4.4.1.8 Transferred entry:  4.4.1.13

**Comment by sjm41** [comment]
FYI, I've come across two of these in the last week where I needed the transferred/valid EC on the GO term, so would be great to complete this list!

**Comment by pgaudet** [comment]
- [x] 1.1.99.11 Transferred entry: 1.1.5.14.

Matches a single GO term, GO:0047904 'fructose 5-dehydrogenase activity'
GO:0047904 Definition: Catalysis of the reaction: D-fructose + A = 5-dehydro-D-fructose + AH(2).
RHEA:22304 definition: a ubiquinone + keto-D-fructose = 5-dehydro-D-fructose + a ubiquinol
EC: 1.1.5.14 definition: a ubiquinone + keto-D-fructose <=> 5-dehydro-D-fructose + a ubiquinol 

Note that both RHEA and EC match, but the GO definition is more general
Single annotation (IDA) UniProtKB: [M1VMF7](https://www.uniprot.org/uniprot/M1VMF7). This entry maps the new EC and the correct RHEA
-	Changed definition to match RHEA and EC
-	Updated EC cross references
-	Cleaned up synonyms
-	Changed parent from ‘GO:0016614 ! oxidoreductase activity, acting on CH-OH group of donors’ to ‘GO:0016901 oxidoreductase activity, acting on the CH-OH group of donors, quinone or similar compound as acceptor’

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms, with replaced_by as indicated: 

Obsolete GO:0050245 quercitrinase activity (EC:3.2.1.66 Transferred to EC:3.2.1.40 ; replace by GO:0030596 alpha-L-rhamnosidase activity (EC:3.2.1.40)  (no annotations)

Obsolete GO:0047409 alkenylglycerophosphoethanolamine hydrolase activity (EC:3.3.2.5 transferred to EC:3.3.2.2);  replace by GO:0047408 alkenylglycerophosphocholine hydrolase activity (EC:3.3.2.2) (genes annotated to GO:0047409 are also annotated to GO:0047408)

Obsolete GO:0047702 beta-lysine 5,6-aminomutase activity (EC:5.4.3.4 Transferred to EC:5.4.3.3; replace by GO:0047826 D-lysine 5,6-aminomutase activity (EC:5.4.3.3) (no annotations)

The reason for obsoletion is that the EC numbers associated with the GO terms to be obsoleted have been replaced by ECs that are associated with the terms proposed to replace the obsolete terms. Other cross-references will be moved as appropriate. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24927

Thanks, Pascale

**Comment by pgaudet** [comment]
Looks like all these are done.
