### ISSUE TITLE
plasmanylethanolamine desaturase activity (GO:0050207) fixes

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24969]
id: GO:0050207
name: plasmanylethanolamine desaturase activity
def: "Catalysis of the reaction: O-1-alkyl-2-acyl-sn-glycero-3-phosphoethanolamine + donor-H2 + O2 = O-1-alk-1-enyl-2-acyl-sn-glycero-3-phosphoethanolamine + acceptor + 2 H2O." [RHEA:22956]
xref: EC:1.14.19.77
xref: MetaCyc:PLASMANYLETHANOLAMINE-DESATURASE-RXN
xref: RHEA:22956
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

- [x] Current parent corresponds to (has xref of) EC:1.14.-.-  Change this to more specific term (corresponding to EC:1.14.19.-): GO:0016717 "oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water"

- [x] Tweak definition to match EC/Rhea:
1-(1,2-saturated alkyl)-2-acyl-sn-glycero-3-phosphoethanolamine + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 <=> 1-O-(1Z-alkenyl)-2-acyl-sn-glycero-3-phosphoethanolamine + 2 Fe(III)-[cytochrome b5] + 2 H2O

- [x] Add additional parent of GO:0051213 dioxygenase activity

**Comment by sjm41** [comment]
Unclear whether this activity is classed as a type of dioxygenase or not - see https://github.com/geneontology/go-ontology/issues/27381#issuecomment-2690485539
So removing that parent.
