### ISSUE TITLE
short-branched-chain-acyl-CoA dehydrogenase activity / EC:1.3.8.1 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25073]
id: GO:0016937 [2 EXP annotations]
name: short-branched-chain-acyl-CoA dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor, where the acyl group is a short branched chain fatty acid residue." [GOC:mah]
xref: RHEA:47196
is_a: GO:0003995 ! acyl-CoA dehydrogenase activity

RHEA:47196 says that this corresponds to EC:1.3.8.1 :
EC 1.3.8.1
Name: short-chain acyl-CoA dehydrogenase.
Alternative Name(s):butanoyl-CoA dehydrogenase, butyryl dehydrogenase, short-chain acyl CoA dehydrogenase, unsaturated acyl-CoA reductase.
Reaction: a short-chain 2,3-saturated fatty acyl-CoA + H(+) + oxidized [electron-transfer flavoprotein] <=> a short-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]

But we already have EC:1.3.8.1 on this term:
id: GO:0004085 [4 EXP annotations]
name: butyryl-CoA dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: butanoyl-CoA + electron-transfer flavoprotein = 2-butenoyl-CoA + reduced electron-transfer flavoprotein." [EC:1.3.8.1]
synonym: "3-hydroxyacyl CoA reductase activity" RELATED [EC:1.3.8.1]
synonym: "butanoyl-CoA:(acceptor) 2,3-oxidoreductase activity" RELATED [EC:1.3.8.1]
synonym: "butanoyl-CoA:acceptor 2,3-oxidoreductase activity" RELATED [EC:1.3.8.1]
synonym: "butyryl coenzyme A dehydrogenase activity" RELATED [EC:1.3.8.1]
synonym: "butyryl dehydrogenase activity" RELATED [EC:1.3.8.1]
synonym: "enoyl-coenzyme A reductase activity" RELATED [EC:1.3.8.1]
synonym: "ethylene reductase activity" RELATED [EC:1.3.8.1]
synonym: "short-chain acyl CoA dehydrogenase activity" RELATED [EC:1.3.8.1]
synonym: "short-chain acyl-coenzyme A dehydrogenase activity" RELATED [EC:1.3.8.1]
synonym: "short-chain-acyl-CoA dehydrogenase activity" RELATED [EC:1.3.8.1]
synonym: "unsaturated acyl coenzyme A reductase activity" RELATED [EC:1.3.8.1]
synonym: "unsaturated acyl-CoA reductase activity" RELATED [EC:1.3.8.1]
xref: EC:1.3.8.1
xref: KEGG_REACTION:R01178
xref: MetaCyc:BUTYRYL-COA-DEHYDROGENASE-RXN
xref: UM-BBD_reactionID:r0013
is_a: GO:0003995 ! acyl-CoA dehydrogenase activity

This is RHEA:24004, which RHEA also links this to EC:1.3.8.1.

Possible tasks:
- [ ] add RHEA:24004 to GO:0004085 butyryl-CoA dehydrogenase activity
- [ ] If "branched chain" is a critical part of the GO:0016937 def, then remove RHEA:47196 xref (as that doesn't specify "branched chain")
- [ ] Alternatively, if "branched chain" isn't critical, then: 1. add EC:1.3.8.1 to GO:0016937,  2. remove "branched chain" from the term and def of GO:0016937, 3. make 'butyryl-CoA dehydrogenase activity' a child of 'GO:0016937'.

relates to https://github.com/geneontology/go-ontology/issues/23497

**Comment by sjm41** [comment]
Just noticed that https://www.rhea-db.org/rhea/47196 confirms that RHEA:24004 is a specific form of RHEA:47196, ie. supporting this change:
```
_acyl-CoA dehydrogenase activity
|__short-branched-chain-acyl-CoA dehydrogenase activity (RHEA:47196)
|__butyryl-CoA dehydrogenase activity (RHEA:24004)
```
to this:
```
_acyl-CoA dehydrogenase activity
|__short-branched-chain-acyl-CoA dehydrogenase activity (RHEA:47196)
    |__butyryl-CoA dehydrogenase activity (RHEA:24004)
```

But as I said, this depends on whether the 'branched-chain' bit is an important distinction here.

@kaxelsen can you say if RHEA:47196/EC:1.3.8.1 are really equivalent to GO:0016937:

EC:1.3.8.1: a short-chain 2,3-saturated fatty acyl-CoA + H(+) + oxidized [electron-transfer flavoprotein] <=> a short-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]
GO:0016937: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor, where the acyl group is a short branched chain fatty acid residue."

**Comment by raymond91125** [comment]
I don't think it's possible to definitively say what the meaning of short-branched-chain is in GO:0016937 short-branched-chain-acyl-CoA dehydrogenase activity. Thus we can only go with the fact that it's XREFed to RHEA:47196 and thus perhaps branch chain is 'optional' and it is parallel to long and medium chain acyl-CoA dehydrogenases. I don't think RHEA:47196 excludes branched-chain R group either.

**Comment by sjm41** [comment]
Thanks. This looks good to me, I think you can close this.

**Comment by raymond91125** [comment]
Thanks, @sjm41

**Comment by sjm41** [comment]
Just noticed that the changes above resulted in EC:1.3.8.1 being an xref on both these GO terms:

id: GO:0016937
name: short-chain-acyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor, where the acyl group is a short chain fatty acid residue." [GOC:mah]
xref: EC:1.3.8.1
xref: RHEA:47196

id: GO:0004085
name: butyryl-CoA dehydrogenase activity
def: "Catalysis of the reaction: butanoyl-CoA + electron-transfer flavoprotein = 2-butenoyl-CoA + reduced electron-transfer flavoprotein." [EC:1.3.8.1]
xref: EC:1.3.8.1
xref: RHEA:24004
is_a: GO:0016937 ! short-chain-acyl-CoA dehydrogenase activity

It should be removed from the more specific GO:0004085 term because https://enzyme.expasy.org/EC/1.3.8.1 says:
Name: short-chain acyl-CoA dehydrogenase 
Reaction: a short-chain 2,3-saturated fatty acyl-CoA + H(+) + oxidized [electron-transfer flavoprotein] <=> a short-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]

The def of GO:0016937 could also be updated to match the EC/RHEA def.
