### ISSUE TITLE
Terms relating to EC:1.3.1.9 enoyl-[acyl-carrier-protein] reductase (NADH)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25307]
EC:1.3.1.9
Accepted Name: enoyl-[acyl-carrier-protein] reductase (NADH)
Alt_names: enoyl-ACP reductase, NADH-enoyl acyl carrier protein reductase, NADH-specific enoyl-ACP reductase
Reaction: a 2,3-saturated acyl-[ACP] + NAD(+) <=> a (2E)-enoyl-[ACP] + H(+) + NADH

This EC  is currently an xref on these two terms:

id: GO:0016631
name: enoyl-[acyl-carrier-protein] reductase activity
xref: EC:1.3.1.9
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NAD(P)+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NAD(P)H + H+." [EC:1.3.1.9, GOC:rb]

id: GO:0004318
name: enoyl-[acyl-carrier-protein] reductase (NADH) activity
xref: EC:1.3.1.9
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NAD+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADH + H+." [EC:1.3.1.9]

Tasks:
- [x] Remove EC:1.3.1.9 from GO:0016631, since the GO term is for NAD/NADP whereas the EC reaction is NAD-specific (and EC:1.3.1.9 is correctly on the "GO:0004318 enoyl-[acyl-carrier-protein] reductase (NADH) activity" term
- [x] add RHEA:10240 as xref to GO:0004318
- [x] As defined, it looks like GO:0016631 should be a parent term of GO:0004318 as well as these two other related GO terms:

id: GO:0047117
name: enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity
xref: EC:1.3.1.39
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NADP+ = trans-D2-enoyl-[acyl-carrier protein] + NADPH + H+." [EC:1.3.1.39, MetaCyc:1.3.1.39-RXN]

id: GO:0004319
name: enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity
xref: EC:1.3.1.10
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NADP+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADPH + H+." [EC:1.3.1.10]

**Comment by raymond91125** [comment]
Thanks for the clear instructions.
