### ISSUE TITLE
Def and other updates: GO:0044726 - maintenance of DNA methylation at imprinted genes

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25333]
The term  **"maintenance of DNA methylation at imprinted genes" (GO:0044726)** appears to have been created originally created as "protection of DNA demethylation of female pronucleus"

In December 2022, in this ticket: **"Epigenetics: Changes to methylation terms"** #24543, the label was changed but the definition was not updated.

- GO:0044726 protection of DNA demethylation of female pronucleus
- CHANGE LABEL TO: maintenance of DNA methylation at imprinted genes
- MOVE TO is_a 'maintenance of DNA methylation'

Now we have this stanza:

> [Term]
> id: GO:0044726
> name: maintenance of DNA methylation at imprinted genes
> namespace: biological_process
> def: "The protection of the maternal genome from DNA demethylation in the zygote following fertilization." [GOC:sp, PMID:22868271]
> synonym: "protection of DNA demethylation of female pronucleus" NARROW []
> is_a: GO:0045814 ! negative regulation of gene expression, epigenetic
> relationship: part_of GO:0044725 ! chromatin reprogramming in the zygote
> property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24543" xsd:anyURI
> created_by: jl
> creation_date: 2012-10-24T14:10:36Z
> 

I think this is a problem since the definition specifies protection of only the maternal genome from DNA demethylation. This is overly narrow even looking at the paper used to define this term, which says this: 

> In zygotes, a global loss of DNA methylation occurs selectively in the paternal pronucleus before the first cell division, concomitantly with the appearance of modified forms of 5-methylcytosine. The adjacent **maternal pronucleus and certain paternally-imprinted loci are protected from this process**. Nakamura et al. recently clarified the molecular mechanism involved: PGC7/Stella/Dppa3 binds to dimethylated histone 3 lysine 9 (H3K9me2), thereby blocking the activity of the Tet3 methylcytosine oxidase in the maternal genome as well as at certain imprinted loci in the paternal genome.

Therefore, I think we need to adjust the definition. Here's a proposal:

New def: "The protection of the maternal genome and certain paternally imprinted loci from DNA demethylation (of 5-methylcytosine) in the zygote following fertilization."
additional references: GOC:krc, PMID:24492710

**Comment by krchristie** [comment]
Actually the term name chosen in December 2022 seems problematic as well as the maintenance of DNA methylation appears not to be specific to imprinted genes in the maternal pronucleus. In the maternal pronucleus, **ALL** 5-methylcytosine is protected, **NOT** just maternally imprinted genes. 

A more accurate label would be "maintenance of 5-methylcytosine modifications in DNA"

**Comment by pgaudet** [comment]
Thanks for pointing this out @krchristie 
I just discussed this branch with @colinlog today, here are the changes we propose: 


- [ ] **GO:0043045 'DNA methylation involved in embryo development' :** change label to 'epigenetic regulation of embryonic gene expression'
- [ ] change def from "The covalent transfer of a methyl group to C-5 of cytosine that contributes to the epigenetic regulati
on of embryonic gene expression." [GOC:go_curators, PMID:12138111] to 
+def: "A epigenetic process that happens during embryonic development that modulates gene expression potential at later stages of development of the organism, including the adult. Epigenetic regulation takes place via 
chromatin remodeling either by modifying higher order chromatin fiber structure, nucleosomal histones, or cy
tosine DNA methylation." [GOC:go_curators, PMID:12138111, PMID:22868271]
- [ ] GO:0044725 'chromatin reprogramming in the zygote' change label to 'epigenetic programming in the zygotic pronuclei'
- [ ] **GO:0044726 'maintenance of DNA methylation at imprinted genes':** change label to epigenetic programing of female pronucleus
- [ ] change def from "The protection of the maternal genome from DNA demethylation in the zygote following fertilization." [GOC:sp, PMID:22868271] to 
- "The global reprogramming of epigenetic modifications in the female pronucleus of the newly fertilized zygote. The maternal genome is protected from global DNA demethylation before the first division of the zygote, and instead undergoes “passive”, replication-dependent demethylation during early embryogenesis, arising from inhibition of the DNA maintenance methyltransferase Dnmt1." [GOC:sp, PMID:22868271]
- [ ] GO:0044727 'DNA demethylation of male pronucleus' : change label to 'epigenetic programing of male pronucleus'
- [ ] Change def from "The active DNA demethylation of the paternal genome that takes place before the first cell division." [GOC:sp, PMID:22868271]  to  "The global reprogramming of epigenetic modifications in the male pronucleus of the newly fertilized zygote. The most major change in the paternal genome is DNA demethylation, which takes place before the first cell division." [GOC:sp, PMID:22868271]
- [ ] GO:0071514 'genomic imprinting': change label to 'establishment of genomic imprinting'

**Comment by pgaudet** [comment]
Revisiting this while [looking at annotations to GO:0006349 regulation of gene expression by genomic imprinting ](https://docs.google.com/spreadsheets/d/10yTI_nqzUXZPS2WOjCnrfRCgZb3odVysClOKDp5eDjI/edit#gid=0)

@colinlog ad I propose to revert this change : 
GO:0071514 'genomic imprinting': change label to 'establishment of genomic imprinting'
and go back to the label genomic imprinting. 

Thanks, Pascale
