### ISSUE TITLE
   GO:0006351     DNA-templated transcription  parentage?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25419]
I was wondering why DNA-templated transcription
isn't part_of "gene expression"?

**Comment by ValWood** [comment]
@pgaudet  should I add this? I can't think of a reason why not?

**Comment by pgaudet** [comment]
Yes, please add this - I think it was accidentally removed here https://github.com/geneontology/go-ontology/issues/24383

**Comment by pgaudet** [comment]
We could discuss this at an ontology call, I'd like to have @cmungall 's and @balhoff take on this . but this LD would not classify the term under gene expression: 

'macromolecule biosynthetic process'
 and ('process has causal agent' some 'deoxyribonucleic acid')
 and ('has primary output' some transcript)

This is a bit unusual

**Comment by pgaudet** [comment]
I just added this, and added this topic to the next ontology call (June 26)

**Comment by pgaudet** [comment]
- [x] Changed GO:0010467 gene expression is_a macromolecule biosynthetic process (from is_a macromolecule metabolic process)
- [x] GO:0006351 DNA-templated transcription: added part_of gene_expression (kept LD as 
 'macromolecule biosynthetic process'
 and ('process has causal agent' some 'ribonucleic acid')
 and ('has primary output' some transcript)
- [x] GO:0001172 RNA-templated transcription: added part_of gene_expression (kept LD as 
 'macromolecule biosynthetic process'
 and ('process has causal agent' some 'deoxyribonucleic acid')
 and ('has primary output' some transcript)

- [x] GO:0006390 mitochondrial transcription and GO:0042793 plastid transcription: removed  "has primary output' some transcript" from LD, since this is already in the parent's LD (DNA.templated transcription)
