### ISSUE TITLE
Issues with 'glucose dehydrogenase activity' (GO:0004344) and children

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25441]
I noticed a few issues with this term and its children:
```
|__glucose dehydrogenase activity GO:0004344 (EC:1.1.99.35, RHEA:24540)
	|__glucose 1-dehydrogenase (NAD+) activity GO:0047934 (EC:1.1.1.118, RHEA:14293)
	|__glucose 1-dehydrogenase (NADP+) activity GO:0047935 (EC:1.1.1.119, RHEA:14405)
	|__glucose 1-dehydrogenase [NAD(P)] activity GO:0047936 (EC:1.1.1.47)
	|__glucose dehydrogenase (FAD, quinone) activity GO:0140762 (EC:1.1.5.9, RHEA:47372)
	|__quinoprotein glucose dehydrogenase activity GO:0008876 (EC:1.1.5.2, RHEA:22152)
```

- [x] Add additional parent "GO:0016901 oxidoreductase activity, acting on the CH-OH group of donors, quinone or similar compound as acceptor (EC:1.1.5.-)" to glucose dehydrogenase (FAD, quinone) activity GO:0140762 (EC:1.1.5.9, RHEA:47372)

- [x] Tweak name of GO:0047936 to "glucose 1-dehydrogenase [NAD(P)+] activity" (ie. add the '+') to match its GO definition and EC xref

- [x] Following on from that, add GO:0047936 as parent of GO:0047934 and GO:0047935 (and remove their GO:0004344 parent)

- [ ] Remove EC:1.1.99.35 xref from 'glucose dehydrogenase activity GO:0004344' because (i) this is a grouping term in GO for more specific terms with EC xrefs with different prefixes 1.1.1.- and 1.1.5.-, and (ii) EC says that "soluble quinoprotein glucose dehydrogenase (EC:1.1.99.35)" is an enzyme/activity described only in Acinetobacter calcoaceticus. (It seems OK to keep the RHEA:24540 xref, though I see RHEA does equate EC:1.1.99.35 with RHEA:24540 - so we'd be inconsistent with RHEA mapping in that respect)

Final tree would look like this:
```
|__glucose dehydrogenase activity GO:0004344 (RHEA:24540)
	|__glucose 1-dehydrogenase [NAD(P)+] activity GO:0047936 (EC:1.1.1.47)
		|__glucose 1-dehydrogenase (NAD+) activity GO:0047934 (EC:1.1.1.118, RHEA:14293)
		|__glucose 1-dehydrogenase (NADP+) activity GO:0047935 (EC:1.1.1.119, RHEA:14405)
	|__glucose dehydrogenase (FAD, quinone) activity GO:0140762 (EC:1.1.5.9, RHEA:47372)
	|__quinoprotein glucose dehydrogenase activity GO:0008876 (EC:1.1.5.2, RHEA:22152)
```

**Comment by sjm41** [comment]
Hi @pgaudet Can I nudge this ticket? thanks!

**Comment by sjm41** [comment]
I fixed tasks 1-3.
I didn't do task 4 in the end, as the EC:1.1.99.35 reaction def does match the GO/RHEA def, and the 'EC:1.1.99.-' class is for "Oxidoreductases -> Acting on the CH-OH group of donors -> With other acceptors", which seems OK.

**Comment by pgaudet** [comment]
Thanks Steven!
