### ISSUE TITLE
Review children of 'GO:0140101 catalytic activity, acting on a tRNA

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25516]
Some children of GO:0140101 catalytic activity, acting on a tRNA, describe activities that use a changed tRNA as an amino acid donor. These should NOT be children of 'GO:0140101 catalytic activity, acting on a tRNA

- [x] Added a comment to the term: Note that this term excludes activities for which a charged tRNA acts as an amino acid donor.

**Comment by pgaudet** [comment]
Remove parent 'GO:0140101 catalytic activity, acting on a tRNA'  
- [x] GO:0050071 'phosphatidylglycerol lysyltransferase activity'

Other changes: 

- [x] GO:0004125 L-seryl-tRNASec selenium transferase activity: fix label to match tRNA notation, to 'L-seryl-tRNA(Sec) selenium transferase activity'
- [x] GO:0043905 Ser-tRNA(Thr) hydrolase activity: fix label to match tRNA notation, to 'L-seryl-tRNA(Thr) hydrolase activity'
- [x] GO:0008479 queuine tRNA-ribosyltransferase activity, change label to match EC  tRNA-guanosine(34) queuine transglycosylase activity
- [x] GO:0009022 phosphate-dependent exonuclease activity, change label to 'tRNA nucleotidyltransferase activity' to be more clear
- [ ] GO:0098621 phosphoseryl-selenocysteinyl-tRNA selenium transferase activity,  fix label to match tRNA notation, to 'O-phosphoseryl-tRNA(Sec) selenium transferase activity'
- [x] GO:0043766 Sep-tRNA:Cys-tRNA synthase activity, change def to match RHEA, from "Catalysis of the reaction: O-phospho-L-seryl-tRNACys + sulfide = L-cysteinyl-tRNACys + phosphate." [PMID:15790858, PMID:16380427, PMID:17110438] to "Catalysis of the reaction: H+ + hydrogen sulfide + O-phospho-L-seryl-tRNA(Cys) = L-cysteinyl-tRNA(Cys) + phosphate." [PMID:15790858, PMID:16380427, PMID:17110438, RHEA:25686]
