### ISSUE TITLE
3-demethylubiquinol 3-O-methyltransferase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25680]
Currently we have:
```
3-demethylubiquinol-n 3-O-methyltransferase activity (GO:0061542) (no EC/RHEA) <- 3 EXP annotations
    |_3-demethylubiquinone-9 3-O-methyltransferase activity (GO:0008689) (EC:2.1.1.64, RHEA:17049) <- 0 EXP annotation
    |_3-demethylubiquinol-10 3-O-methyltransferase activity (GO:0044596) (no EC, RHEA:44412) <- 0 EXP annotation
    |_3-demethylubiquinol-6 3-O-methyltransferase activity (GO:0061543) (no EC/RHEA) <- 1 EXP annotation
    |_3-demethylubiquinol-8 3-O-methyltransferase activity (GO:0099119) (no EC/RHEA) <- 1 EXP annotation
```
![Screenshot 2023-07-05 at 13 01 20](https://github.com/geneontology/go-ontology/assets/16306861/f50728b5-85da-4712-a764-bdffcddc5b4e)

EC:2.1.1.64 says:
Name: 3-demethylubiquinol 3-O-methyltransferase
Reaction: a 3-demethylubiquinol + S-adenosyl-L-methionine <=> a ubiquinol + H(+) + S-adenosyl-L-homocysteine

Comments: Ubiquinones from different organisms have a different number of prenyl units (for example, ubiquinone-6 in Saccharomyces, ubiquinone- 9 in rat and ubiquinone-10 in human), and thus the natural substrate for the enzymes from different organisms has a different number of prenyl units.However, the enzyme usually shows a low degree of specificity regarding the number of prenyl units.

So, I suggest:
- [x] Remove EC:2.1.1.64 from GO:0008689
- [x] Add EC:2.1.1.64 and RHEA:44380 to the parent term GO:0061542
- [x] Add is_a S-adenosylmethionine-dependent methyltransferase activity (GO:0008757) to the parent term and remove from GO:0008689 and GO:0044596
- [ ] Consider obsoleting the 4 child terms given this is essentially the same activity on different species-specific substrates.

**Comment by sjm41** [comment]
Hi @pgaudet I've fixed the xref and parentage issues here, but leaving the obsoletion proposal with you.

**Comment by pgaudet** [comment]
GO:0008689 3-demethylubiquinone-9 3-O-methyltransferase activity
GO:0044596 3-demethylubiquinol-10 3-O-methyltransferase activity 
GO:0061543 3-demethylubiquinol-6 3-O-methyltransferase activity 
GO:0099119 3-demethylubiquinol-8 3-O-methyltransferase activity
