### ISSUE TITLE
hydroxypyruvate reductase activity/glycerate dehydrogenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25789]
Looking at these two terms:

```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
    |_hydroxypyruvate reductase activity
    |_glycerate dehydrogenase activity
```

Despite their different names, these represent the same activity and only differ in their use of NAD/NADP as the acceptor:

id: GO:0016618
name: hydroxypyruvate reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-glycerate + NADP+ = hydroxypyruvate + NADPH + H+." [EC:1.1.1.81]
synonym: "beta-hydroxypyruvate reductase activity" RELATED [EC:1.1.1.81]
synonym: "D-glycerate dehydrogenase activity" RELATED [EC:1.1.1.81]
synonym: "D-glycerate:NADP+ 2-oxidoreductase activity" RELATED [EC:1.1.1.81]
synonym: "NADH:hydroxypyruvate reductase activity" RELATED [EC:1.1.1.81]
xref: EC:1.1.1.81
xref: MetaCyc:HYDROXYPYRUVATE-REDUCTASE-RXN
xref: MetaCyc:RXN0-300
xref: RHEA:18657
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0008465
name: glycerate dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-glycerate + NAD+ = hydroxypyruvate + NADH + H+." [EC:1.1.1.29]
synonym: "hydroxypyruvate dehydrogenase activity" BROAD [EC:1.1.1.29]
xref: EC:1.1.1.29
xref: MetaCyc:GLYCERATE-DEHYDROGENASE-RXN
xref: RHEA:17905
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

That's fine in itself, but EC actually says that EC:1.1.1.81 (GO:0016618) can use either NAD/NADP and also differs from the GO def in a couple of other ways (https://enzyme.expasy.org/EC/1.1.1.81).

So, I think the tasks here are:

**hydroxypyruvate reductase activity (GO:0016618)**

- [x] Change D-glycerate to R-glycerate in the def
- [x] Change hydroxypyruvate to 3-hydroxypyruvate in the def
- [x] Change NADP to NAD(P) in the def
- [x] Change name to 'hydroxypyruvate reductase (NAD(P)) activity'?
- [x] Remove RHEA:18657 xref (as this is specific to NADP version)
- [x] Remove MetaCyc:RXN0-300 xref (also specific to NADP version)

**glycerate dehydrogenase activity (GO:0008465)**
- [x] Change hydroxypyruvate to 3-hydroxypyruvate in the def
- [x] make this a child of hydroxypyruvate reductase activity (GO:0016618)
- [x] change name to glycerate dehydrogenase (NAD) activity?

**hydroxypyruvate reductase (NADP) activity (NTR)**
- [x] def: "Catalysis of the reaction: (R)-glycerate + NADP+ = 3-hydroxypyruvate + NADPH + H+." [RHEA:18657]
- [x] add RHEA:18657 & MetaCyc:RXN0-300 as xrefs
- [x] child of hydroxypyruvate reductase activity (GO:0016618)

Final tree would look like:
```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
    |_hydroxypyruvate reductase (NAD(P)) activity
        |_glycerate dehydrogenase (NAD) activity
        |_hydroxypyruvate reductase (NADP) activity
```

**Comment by pgaudet** [comment]
Hi @sjm41 

I have many questions: 
- Why did you make glycerate dehydrogenase activity (GO:0008465) a child of hydroxypyruvate reductase activity (GO:0016618)? (the chemistry is not obvious to me)
- I think 'hydroxypyruvate reductase [NAD(P)] activity'(GO:0016618) should have either [NAD(P)+] or [NAD(P)H], but not nothing? 
<img width="307" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/9ae9ed5f-5d04-4596-b064-07c0f5efd825">
- in the screenshot above, I am not sure why none of the terms are the same WRT to the H+/H next to NAD/P
- More generally, I have been wondering whether we should add (NAD/P) in the term labels consistently, even if EC doesn't (I cannot figure out what their rules are for adding the NAD/P in the label or not. 

Thanks, Pascale

**Comment by deustp01** [comment]
Is [RHEA:17905](https://www.rhea-db.org/rhea/17905) relevant here?

**Comment by pgaudet** [comment]
- I now see that  EC https://enzyme.expasy.org/EC/1.1.1.81 (corresponding to ) has synonym: D-glycerate dehydrogenase 
but should we not use 'hydroxypyruvate' for all terms in that brach, for consistency? 

- For RHEA:17905: maybe it should be the defxref for [glycerate dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0008465)? Rather than the EC?

**Comment by sjm41** [comment]
hydroxypyruvate reductase activity (GO:0016618) is EC:1.1.1.81:
(R)-glycerate + NAD(P)+ = 3-hydroxypyruvate + H+ + NAD(P)H

glycerate dehydrogenase activity (GO:0008465) is EC:1.1.1.29 (RHEA:17905):
(R)-glycerate + NAD(+) <=> 3-hydroxypyruvate + H(+) + NADH

So, the second reaction is the NAD-specific version of the first reaction.

The confusing thing is the EC names (which were inherited as GO term names, and which don't mention the NAD specificity):
- GO:0016618/EC:1.1.1.81 is "hydroxypyruvate reductase" (i.e. right to left)
- GO:0008465/EC:1.1.1.29 is "glycerate dehydrogenase" (i.e. left to right)

We didn't previously have the NADP-specific version (RHEA:18657), so I added that as "hydroxypyruvate reductase (NADPH) activity (GO:0120509)"


After several edits, I ended up with this:

```
hydroxypyruvate reductase [NAD(P)] activity (GO:0016618) [EC:1.1.1.81]
    |_glycerate dehydrogenase (NAD+) activity (GO:0008465) [EC:1.1.1.29/RHEA:17905]
    |_hydroxypyruvate reductase (NADPH) activity (GO:0120509) [RHEA:18657]
```

I can see that preserving the EC names here is confusing/inconsistent in the tree (and for the NAD labels), so we could certainly change that as an exceptional case where we don't use EC enzyme names.
I will go ahead and use the 'hydroxypyruvate reductase' label for all.

Yes, I also see I messed up with the NAD bit in the GO:0016618 name - that should have been "hydroxypyruvate reductase [NAD(P)H] activity". Sorry about that - I will fix.

**Comment by sjm41** [comment]
> More generally, I have been wondering whether we should add (NAD/P) in the term labels consistently, even if EC doesn't
I've also been wondering about that recently! I'll add the issue to our list....

**Comment by sjm41** [comment]
New version:

```
hydroxypyruvate reductase [NAD(P)H] activity (GO:0016618) [EC:1.1.1.81]
    |_hydroxypyruvate reductase (NADH) activity (GO:0008465) [EC:1.1.1.29/RHEA:17905]
    |_hydroxypyruvate reductase (NADPH) activity (GO:0120509) [RHEA:18657]
```
