### ISSUE TITLE
Changes to GO:0036524 protein deglycase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25834]
id: GO:0036524
name: protein deglycase activity
namespace: molecular_function
def: "Catalysis of the removal of a sugar or dicarbonyl from a lysine residue of a glycated protein." [GOC:bf, GOC:PARL, PMID:14568004, PMID:25416785, PMID:26873906]
synonym: "protein deglycating enzyme" RELATED [PMID:26873906]
xref: MetaCyc:RXN-17630
xref: MetaCyc:RXN-17632
xref: MetaCyc:RXN-17634
is_a: GO:0016836 ! hydro-lyase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein

- [x] add EC:3.5.1.124 xref
- [x] change the 'GO:0016836 ! hydro-lyase activity' parent to 'GO:0016811 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides' (xref: EC:3.5.1.-)
- [x] add 'glyoxylase III' synonym from EC entry
- [x] Change def to better match EC/RHEA, maybe "Catalysis of the removal of lactate or glycolate from glycated L-arginine, L-lysine, or L-cysteine residues within proteins."
- [ ] The three current MetaCyc xrefs are for specific substrates (corresponding to RHEA:49548, RHEA:49552, RHEA:49556) and RHEA maps a further 3 reactions to EC:3.5.1.124 (https://www.rhea-db.org/rhea/?query=ec:3.5.1.124). So, we should either (i) remove the 3 MetaCyc xrefs; (ii) keep the MetaCyc xrefs and add the 6 RHEA xrefs, making them all 'narrow match' xrefs; or (iii) make the 6 child terms.

**Comment by sjm41** [comment]
Changed def to:
Catalysis of the removal of a sugar or dicarbonyl from a glycated L-arginine, L-lysine or L-cysteine residue within proteins that have been attacked and modified by glyoxal or 2-oxopropanal.

Which matches the EC comment "acts on glycated L-arginine, L-lysine, and L-cysteine residues within proteins that have been attacked and modified by glyoxal or 2-oxopropanal."

**Comment by sjm41** [comment]
@pgaudet I wasn't sure what to do about the 5th task above, so will wait for your view!

**Comment by sjm41** [comment]
Current term looks like this:

id: GO:0036524
name: protein deglycase activity
namespace: molecular_function
def: "Catalysis of the removal of a sugar or dicarbonyl from a glycated L-arginine, L-lysine or L-cysteine residue within proteins that have been attacked and modified by glyoxal or 2-oxopropanal." [EC:3.5.1.124, GOC:bf, GOC:PARL, PMID:14568004, PMID:25416785, PMID:26873906]
synonym: "glyoxylase III" EXACT [] {source="EC:3.5.1.124"}
synonym: "protein deglycating enzyme" RELATED [PMID:26873906]
xref: EC:3.5.1.124
xref: MetaCyc:RXN-17630
xref: MetaCyc:RXN-17632
xref: MetaCyc:RXN-17634
is_a: GO:0016811 ! hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
is_a: GO:0140096 ! catalytic activity, acting on a protein
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25834" xsd:anyURI
created_by: bf
creation_date: 2016-08-04T10:23:33Z

**Comment by sjm41** [comment]
I will make the three MetaCyc xrefs narrowMatch, and add the six corresponding RHEAS (RHEA:49548, RHEA:49552, RHEA:49556, RHEA:57188, RHEA:57192, RHEA:57196) also as narrowMatch.
