### ISSUE TITLE
Update GO:0016719 name, def and MetaCyc xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25964]
id: GO:0016719
name: carotene 7,8-desaturase activity
namespace: molecular_function
def: "Catalysis of the reaction: neurosporene + donor-H2 + O2 = lycopene + acceptor + 2 H2O." [RHEA:30955]
synonym: "carotene,hydrogen-donor:oxygen oxidoreductase activity" RELATED []
synonym: "zeta-carotene desaturase activity" RELATED [EC:1.3.5.6]
xref: EC:1.3.5.6
xref: MetaCyc:1.14.99.30-RXN
xref: RHEA:30955
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

But name & def for the given EC/Rhea xref is:
Name: 9,9'-di-cis-zeta-carotene desaturase
Reaction: 9,9'-di-cis-zeta-carotene + 2 a quinone <=> 7,7',9,9'-tetra-cis-lycopene + 2 a quinol

Also, the given MetaCyc xref is obsolete.

I guess the mismatch is a hangover from the previous transfer of EC:1.14.99.30 to EC:1.3.5.6:
https://enzyme.expasy.org/EC/1.14.99.30

So tasks here are:

- [x] Change name to '9,9'-di-cis-zeta-carotene desaturase'
- [x] Change def to match EC/Rhea (as given above)
- [x] Change MetaCyc xref to 'MetaCyc:RXN-12242'
- [x] Change parent to 'GO:0016635 oxidoreductase activity, acting on the CH-CH group of donors, quinone or related compound as acceptor' (to match EC classification)

(there are no EXP annotations to GO:0016719)
