### ISSUE TITLE
GO:0047388 [glutamine synthetase]-adenylyl-L-tyrosine phosphorylase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25974]
id: GO:0047388
name: [glutamine synthetase]-adenylyl-L-tyrosine phosphorylase
namespace: molecular_function
def: "Catalysis of the reaction: adenylyl-[L-glutamate:ammonia ligase (ADP-forming)] + H2O = AMP + [L-glutamate:ammonia ligase (ADP-forming)]." [MetaCyc:3.1.4.15-RXN]
comment: Formerly EC:3.1.4.15.
synonym: "adenylyl(glutamine synthetase) hydrolase activity" EXACT []
synonym: "adenylyl-[glutamate-ammonia ligase] hydrolase activity" EXACT []
synonym: "adenylyl-glutamate-ammonia ligase hydrolase activity" EXACT []
synonym: "adenylyl-glutamine-synthetasehydrolase activity" EXACT []
synonym: "adenylyl-L-glutamate:ammonia ligase (ADP-forming) adenylylhydrolase activity" EXACT []
xref: EC:2.7.7.89
xref: KEGG_REACTION:R03474
xref: MetaCyc:3.1.4.15-RXN
xref: RHEA:43716
is_a: GO:0008081 ! phosphoric diester hydrolase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein

As noted in the comment above, EC:3.1.4.15 was transferred to EC:2.7.7.89 - the EC xref was updated on this GO term, but the GO name, definition, parentage and MetaCyc xref were not updated.

- [x] Change name to '[glutamine synthetase]-adenylyl-L-tyrosine phosphorylase activity' to match current EC
- [x] Change def to match current EC/RHEA: [glutamine synthetase]-O(4)-(5'-adenylyl)-L-tyrosine + phosphate <=> [glutamine synthetase]-L-tyrosine + ADP
- [x] Change MetaCyc xref to MetaCyc:GSDEADENYLATION-RXN
- [x] Change parent to GO:0016779 nucleotidyltransferase activity (= EC:2.7.7.-)

**Comment by sjm41** [comment]
Thanks @raymond91125 
But can you also add MetaCyc:GSDEADENYLATION-RXN as a dbxref, and change '<=> ' to '=' in the def (though maybe Pascale has already done the latter in #23923)

**Comment by pgaudet** [comment]
I am not sure MetaCyc should the definition xref - at least not the only definition xref 

@cmungall @balhoff any guidance on this ?

**Comment by sjm41** [comment]
I don't know the history of this term, but maybe it was first introduced solely based on the MetaCyc reaction?
Regardless, I agree the current definition xref should be EC/RHEA. (and we should just have MetaCyc:GSDEADENYLATION-RXN as a dbxref)

**Comment by pgaudet** [comment]
ok, I like that too

**Comment by pgaudet** [comment]
@raymond91125 please change the def cross reference to the RHEA:43716

**Comment by pgaudet** [comment]
Thanks !
