### ISSUE TITLE
GO:0102772  sphingolipid long-chain base 4-hydroxylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25981]
id: GO:0102772
name: sphingolipid long-chain base 4-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: O2 + H+ + a dihydroceramide + NAD(P)H = H2O + a phytoceramide + NAD(P)." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-14250
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

MetaCyc:RXN-14250 is linked to EC:1.14.18.5 (which corresponds to RHEA:55808)

So:
- [x] Change name to match EC name, i.e. "sphingolipid C4-monooxygenase activity"
- [x] Change def to match EC/RHEA: a dihydroceramide + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 <=> a phytoceramide + 2 Fe(III)-[cytochrome b5] + H2O
- [x] Add EC:1.14.18.5 and  RHEA:55808 xrefs
- [x] Change parent to GO:0016716 (= xref: EC:1.14.18.-)

(This GO term has been used in 0 annotations to date, but adding the EC and RHEA xrefs will add annotations via IEA at least)

**Comment by sjm41** [comment]
Thanks @raymond91125 !
Can you also add the EC xref? And I think the '<=>' in the def should be changed to '=' (see #23923)

**Comment by raymond91125** [comment]
Is EC dbxref in the definition not sufficient?

**Comment by sjm41** [comment]
I'm afraid not. Certain programs/pipelines look specifically at the xref line of the GO file for the corresponding EC. (And anyway, we put the EC as a dbxref slot in all other cases). Thanks!

**Comment by pgaudet** [comment]
@raymond91125 
> Is EC dbxref in the definition not sufficient?

Note that this was also discussed among editors, and have agreed that we need the definition cross references in the db cross references: 

From https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions#Guidelines_for_individuals_and_groups_dbxref_abbreviations: 

> Definition database cross-references also need to be added as General database cross-references.

**Comment by raymond91125** [comment]
got it. thanks.
