### ISSUE TITLE
GO:0047671 anthranilate adenylyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25980]
id: GO:0047671
name: anthranilate adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: anthranilate + ATP = N-adenylylanthranilate + diphosphate + H+." [PMID:2995633, RHEA:35091]
synonym: "anthranilic acid adenylyltransferase activity" RELATED [EC:2.7.7.55]
synonym: "ATP:anthranilate adenylyltransferase activity" EXACT []
synonym: "ATP:anthranilate N-adenylyltransferase activity" RELATED [EC:2.7.7.55]
xref: EC:6.3.2.40
xref: KEGG_REACTION:R00979
xref: MetaCyc:RXN-13989
xref: RHEA:35091
is_a: GO:0070566 ! adenylyltransferase activity

- [x] Update def to match EC:6.3.2.40/RHEA:35091 def: anthranilate + 2 ATP + L-phenylalanine + S-adenosyl-L-methionine <=> 2 AMP + cyclopeptine + 2 diphosphate + 2 H(+) + S-adenosyl-L-homocysteine

- [x] Update name to match EC:6.3.2.40 name: "cyclopeptine synthase"

- [x] Remove EC:2.7.7.55-based synonyms

- [x] Change parent to GO:0016881 acid-amino acid ligase activity (xref: EC:6.3.2.-)

**Comment by sjm41** [comment]
Thanks @raymond91125 
Sorry, I made a couple of errors in my proposals - Can you add 'activity' at the end of the new term name? And also change '<=>' to '=' in the definition (as per #23923)
