### ISSUE TITLE
tRNA (guanosine-2'-O-)-methyltransferase activity GO:0009020

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26085]
We currently have this:
```
tRNA (guanosine-2'-O-)-methyltransferase activity GO:0009020 (18,156 annotations)
|_tRNA (guanosine 34-2'-O)-methyltransferase activity GO:0106340 (zero annotations)
```

But GO:0009020 is defined by EC:2.1.1.34, RHEA:20077, and those xrefs specify guanosine18.

Following the actions in #26018, we should:

- [ ] ~rename and redefine GO:0009020 following the EC/RHEA reactions (ie make it specific for guanosine18)~
- [ ] ~change parent of GO:0106340 to GO:0016423 ! tRNA (guanine) methyltransferase activity~

- [x] Obsolete tRNA (guanosine-2'-O-)-methyltransferase activity GO:0009020
- [x] Create new term GO:0141100  tRNA (guanosine(18)-2'-O)-methyltransferase activity

id: GO:0009020
name: tRNA (guanosine-2'-O-)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing 2'-O-methylguanosine." [EC:2.1.1.34, RHEA:20077]
synonym: "S-adenosyl-L-methionine:tRNA (guanosine-2'-O-)-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "S-adenosyl-L-methionine:tRNA guanosine-2'-O-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "transfer ribonucleate guanosine 2'-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA (Gm18) 2'-O-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA (Gm18) methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA (guanosine 2')-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA guanosine 2'-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA guanosine-2'-O-methyltransferase activity" RELATED [EC:2.1.1.34]
xref: EC:2.1.1.34
xref: MetaCyc:2.1.1.34-RXN
xref: RHEA:20077
is_a: GO:0016423 ! tRNA (guanine) methyltransferase activity
is_a: GO:0106050 ! tRNA 2'-O-methyltransferase activity

id: GO:0106340
name: tRNA (guanosine 34-2'-O)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + guanosine 34 in tRNA= S-adenosyl-L-homocysteine + 2'-O-methylguanosine 34 in tRNA." [PMID:25404562]
is_a: GO:0009020 ! tRNA (guanosine-2'-O-)-methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25257" xsd:anyURI
created_by: hjd
creation_date: 2020-11-05T22:52:49Z

**Comment by pgaudet** [comment]
Hi @sjm41 

We need to obsolete GO:0009020 tRNA (guanosine-2'-O-)-methyltransferase activity because it's been annotated, sometimes to mean tRNA (guanosine 34-2'-O)-methyltransferase activity.

**Comment by sjm41** [comment]
OK, understood! (was hoping there was less work for you here....)

**Comment by pgaudet** [comment]
Also, fixed labels to be consistent: 

- [ ] GO:0016423  tRNA (guanine) methyltransferase activity >>  tRNA (guanosine) methyltransferase activity
- [ ] GO:0052905 tRNA (guanine(9)-N(1))-methyltransferase activity >>>  tRNA (guanosine(9)-N(1))-methyltransferase activity 
- [ ] GO:0052906 tRNA (guanine(37)-N(1))-methyltransferase activity > tRNA (guanosine(37)-N(1))-methyltransferase activity
- [ ] GO:0106340 tRNA (guanosine 34-2'-O)-methyltransferase activity >> tRNA (guanosine(34)-2'-O)-methyltransferase activity
