### ISSUE TITLE
Check all tRNA methyltransferase terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26109]
EC and RHEA have made a lot of updates since the GO terms were created, and there are a lot of discrpancies. 

- [ ] 'tRNA methyltransferase activity' >> OK grouping class
- [ ] 'tRNA (adenine) methyltransferase activity' >> OK grouping class
- [ ] 'tRNA (cytidine) methyltransferase activity' >> OK grouping class
- [ ] 'tRNA (guanosine) methyltransferase activity' >> OK grouping class, checked see #26085
- [ ] 'tRNA (uracil) methyltransferase activity'
- [ ] 'tRNA (5-methylaminomethyl-2-thiouridylate)-methyltransferase activity' OK 
- [ ] 'tRNA (adenine-C2-)-methyltransferase activity'
- [ ] 'tRNA (adenine-N1-)-methyltransferase activity' >> to obsolete, see #26104
- [ ] 'tRNA (adenine-57, 58-N(1)-) methyltransferase activity' fixed #26105
- [ ] 'tRNA (adenine-N6-)-methyltransferase activity'
- [ ] 'tRNA m2A37 methyltransferase activity'
- [ ] 'tRNA m6t6A37 methyltransferase activity'
- [ ] 'tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity'
- [ ] tRNA (cytosine-2'-O-)-methyltransferase activity >> obsolete, see #26018
- [ ] 'tRNA (cytidine(32)-2'-O)-methyltransferase activity' >> fixed see #26018
- [ ] 'tRNA (cytidine(34)-2'-O)-methyltransferase activity'
- [ ] 'tRNA (cytidine(56)-2'-O)-methyltransferase activity'  >> fixed see #26018
- [ ] 'tRNA (cytidine-3-)-methyltransferase activity'
- [ ] 'tRNA (cytidine-5-)-methyltransferase activity'
- [ ]  tRNA (guanosine-2'-O-)-methyltransferase activity >> obsoleted, see #26085
- [ ] 'tRNA (guanine-N2-)-methyltransferase activity' >> to obsolete, see #26104
- [ ] 'tRNA (guanine-N7-)-methyltransferase activity'
- [ ] 'tRNA (guanosine(18)-2'-O)-methyltransferase activity' >> new, see #26085
- [ ] 'tRNA (guanosine(34)-2'-O)-methyltransferase activity' >> fixed, see #26085
- [ ] 'tRNA (guanosine(37)-N1-)-methyltransferase activity' >> fixed, see #26085
- [ ] 'tRNA (guanosine(9)-N1-)-methyltransferase activity' >> fixed, see #26085
- [ ] 'tRNA (m5U54) methyltransferase activity'
- [ ] '5,10-methylenetetrahydrofolate-dependent tRNA (m5U54) methyltransferase activity'
- [ ] 'S-adenosylmethionine-dependent tRNA (m5U54) methyltransferase activity'
- [ ] 'tRNA (uracil-2'-O-)-methyltransferase activity'
- [ ] 'tRNA 5-carboxymethoxyuridine methyltransferase activity'
- [ ] 'tRNA 2'-O-methyltransferase activity'
- [ ] 'tRNA (uracil-2'-O-)-methyltransferase activity'

**Comment by pgaudet** [comment]
- [x] 'GO:0052735 tRNA (cytidine-3-)-methyltransferase activity' >> changed label to 'tRNA (cytidine-N3)-methyltransferase activity'
- [x] 'GO:0016428 tRNA (cytidine-5-)-methyltransferase activity' >> changed label to 'tRNA (cytidine-N5)-methyltransferase activity'

**Comment by pgaudet** [comment]
WAITING FOR FEEDBACK: 

- [ ] [tRNA (adenine-N6)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0016430) - 1 EXP  >> emailed RHEA helpdesk to confirm that the reaction exists. >> No associations to RHEA, EC, MetaCyc, paper cited do not mention modification at N6

**Comment by pgaudet** [comment]
[tRNA (adenine-N6)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0016430) - 1 EXP >> emailed RHEA helpdesk to confirm that the reaction exists. >> No associations to RHEA, EC, MetaCyc, paper cited do not mention modification at N6


I emailed: 
This is the most comprehensive review of tRNA modifications I found: https://pubmed.ncbi.nlm.nih.gov/33658722/ (see Fig 2). There is also PMID:24581449. I don’t see m6A in either. 
It seems like m6A is limited to mRNA, see PMID:31501426, PMID:24981863
Thanks, Pascale

----

@kaxelsen looked at the evidence and confirms that tRNAs do not seem to have that modification. He will obsolete the reaction in RHEA as well as EC:2.1.1.55.
Thanks, Pascale
