### ISSUE TITLE
Updates to GO:0004741 [pyruvate dehydrogenase (lipoamide)] phosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26194]
id: GO:0004741
name: [pyruvate dehydrogenase (lipoamide)] phosphatase activity
namespace: molecular_function
alt_id: GO:0019906
def: "Catalysis of the reaction: [pyruvate dehydrogenase (lipoamide)] phosphate + H2O = [pyruvate dehydrogenase (lipoamide)] + phosphate." [EC:3.1.3.43]
synonym: "[pyruvate dehydrogenase (lipoamide)] phosphatase, intrinsic catalyst activity" EXACT []
synonym: "phosphopyruvate dehydrogenase phosphatase activity" RELATED [EC:3.1.3.43]
synonym: "pyruvate dehydrogenase (lipoamide) phosphatase activity" EXACT []
synonym: "pyruvate dehydrogenase (lipoamide)-phosphatase activity" RELATED [EC:3.1.3.43]
synonym: "pyruvate dehydrogenase (lipoamide)-phosphate phosphohydrolase activity" RELATED [EC:3.1.3.43]
synonym: "pyruvate dehydrogenase phosphatase activity" RELATED [EC:3.1.3.43]
xref: EC:3.1.3.43
xref: MetaCyc:3.1.3.43-RXN
xref: RHEA:12669
is_a: GO:0004721 ! phosphoprotein phosphatase activity

- [x] Update definition to match EC/RHEA: O-phospho-L-seryl-[pyruvate dehydrogenase E1 alpha subunit] + H2O = L-seryl-[pyruvate dehydrogenase E1 alpha subunit] + phosphate
- [x] Change name to match current EC: [pyruvate dehydrogenase (acetyl-transferring)]-phosphatase activity
- [x] Change parent to protein serine/threonine phosphatase activity GO:0004722
- [x] Remove all EC-based synonyms (because EC doesn't show them any more)?
