### ISSUE TITLE
Review regulation of mitophagy children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26202]
Check the origins of these terms.

They sound like just  "regulation of mitophagy" rather than specific subprocesses. Mitophagy is activated in response to damaged mitochondria, or starvation.
Depolorization would be a readout for damage?

This one looks like it has **regulation of regulation:**
  **regulation** of parkin-mediated **stimulation** of mitophagy in response to mitochondrial depolarization

GO:0098779    positive regulation of mitophagy in response to mitochondrial depolarization | 481 annotations
-- | --
GO:1904924    negative regulation of mitophagy in response to mitochondrial depolarization | 60 annotations (1 EXP)
GO:0061735    DNM1L-mediated stimulation of mitophagy in response to mitochondrial depolarization |  
GO:0061734    parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization | 217 annotations
GO:1905089    regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization | 96 annotations
GO:1905091    positive regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization | 40 annotations
GO:1905090    negative regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization | 56 annotations
GO:1904925    positive regulation of autophagy of mitochondrion in response to mitochondrial depolarization

**Comment by ValWood** [comment]
@marcfeuermann @pgaudet

**Comment by ValWood** [comment]
1. GO:0098779  negative regulation of mitophagy in response to mitochondrial depolarization
has a single annotation from
https://europepmc.org/article/MED/24709290

This does seen to have a role in apoptosis. 
"During apoptosis, Omi/HtrA2 is released into the cytoplasm where it participates in cell death. While confined in the inter-membrane space of the mitochondria, Omi/HtrA2 has a pro-survival function that may involve the regulation of protein quality control (PQC) and mitochondrial homeostasis."

However  the annotated paper for this term
From the abstract:
Here we report that the mitochondrial Mulan E3 ubiquitin ligase is a specific substrate of Omi/HtrA2. During exposure to H(2)O(2), Omi/HtrA2 degrades Mulan, and this regulation is lost in cells that carry the inactive protease. 
This causes a significant decrease of mitofusin 2 (Mfn2) protein, and increased mitophagy.
Deregulation of this pathway, as it occurs in mnd2 mutant mice, causes mitochondrial dysfunction and mitophagy, and could be responsible for the motor neuron disease and the premature aging phenotype observed in these animals.

Here apoptosis appears to be a consequence of inactivation of Omi/HtrA2 rather than 
"regulation" of apoptosis. @pgaudet Do you agree?

**Comment by marcfeuermann** [comment]
Hi Val,
You opened another Pandora Box. We have worked on the autophagy ontology many times (and even published 2 articles). It is a very complex process and cleaning its ontology is a nether ending story. I have to admit that we did not dig deeply in the mitophagy part. By searching in the literature I've discovered the following (see PMID: 25009776):

**Type 1 mitophagy** removes functional mitochondria to provide metabolic precursors during nutrient deprivation or to remove mitochondria in excess of metabolic needs.

By contrast in **Type 2 mitophagy**, mitochondrial depolarization (mtDepo) initiates autophagic sequestration After mtDepo, PINK1 (PTEN induced putative kinase 1) accumulates on mitochondria to promote PRKN (parkin) binding, ubiquitination of outer membrane proteins, and subsequent autophagosome formation. In this way, Type 2 mitophagy removes potentially harm-inducing dysfunctional/damaged mitochondria.

**Type 3 mitophagy**: Topologically, the internalization of MDV by invagination of the surface of multivesicular bodies followed by vesicle scission into the lumen is a form of microautophagy, or micromitophagy.

I would not mind to create the 3 children and their corresponding regulation terms... and obsolete (or merge) all the other existing mitophagy-related terms.  The terms you've mentioned above seem to correspond to regulation of Type 2 mitophagy (not sure all annotations should be regulation...)

About your second point, I agree, apoptosis is a consequence.
That's it on my side. I hope this can be helpful. Good luck.
Best regards,
Marc.

**Comment by ValWood** [comment]
OK this is much clearer. I will follow this schema.
but add "Type 3 mitophagy" as a synonym of https://www.ebi.ac.uk/QuickGO/term/GO:0000424 micromitophagy

Does that sound correct?

**Comment by marcfeuermann** [comment]
Yes Val, Type 3 and micromitophagy are synonyms.
We should be able to cover mitophagy with these 3 types. It should indeed be a lot clearer.

**Comment by ValWood** [comment]
plus
i) remove  existing refs for GO:0000424  definition (replace with above, check)
ii) revise def to "microautophagy of the mitochondrion"
iii) fix comment spelling " generally"

**Comment by ValWood** [comment]
Addressing the new pandora's box:

Current:

<img width="847" alt="Screenshot 2024-08-05 at 10 01 31" src="https://github.com/user-attachments/assets/b9c92b3f-3a67-4365-b001-a826a4a28310">


Problems to resolve:

1. Some  terms, i.e. "regulation of autophagy of mitchondrion in response to"
are not under mitophagy
2. Some regulation terma have no non-regulation counterpart
3. Some regulation terms are redundant

mitophagy
The selective autophagy process in which a mitochondrion is degraded by macroautophagy. 

- [ ] GONEW  type 1 mitophagy 
The selective autophagy process in which a functional mitochondrion is degraded by macroautophagy to provide metabolic precursors during nutrient deprivation or to remove mitochondria in excess of metabolic needs.
PMID: 25009776

- [ ] GO:0061734  parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
This term is positioned as a "regulation term", however it has its own regulation children, and the 6 manual annotations  describe genes directly involved in mitophagy (type 2) because they include PARK, PRKN MFN2. 

RENAME  as "GO NEW type 2 mitophagy" and position directly under "mitopphagy"
The selective autophagy process in which a mitochondrion is degraded by macroautophagy in a process initiated by mitochondrial depolarization (mtDepo) followed by Parkin binding, and ubiquitination of outer membrane proteins, to remove potentially harm-inducing dysfunctional/damaged mitochondria.
PMID: 25009776

- [ ] Add Type 3 mitophagy  as a synonym of “micromitophagy” PMID: 25009776
(Topologically, the internalization of MDV by invagination of the surface of multivesicular bodies followed by vesicle scission into the lumen is a form of microautophagy, or micromitophagy.)
@macfeuermann should this be narrow or exact? I'm a bit confused by microautophagy


- [ ] RENAME 
GO:1905089    regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
as 
GO:1905089  regulation of type 2 mitophagy

- [ ] RENAME 
GO:1905090    negative regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
->  GO:1905090  negative regulation of type 2 mitophagy

- [ ] RENAME 
GO:1905091    positive regulation of parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization
-> GO:1905091 positive regulation of type 2 mitophagy

- [ ] OBSOLETE/MERGE
GO:1904923 regulation of autophagy of mitochondrion in response to mitochondrial depolarization
-> GO:1905089  regulation of type 2 mitophagy

- [ ] OBSOLETE/MERGE
GO:0098779 positive regulation of mitophagy in response to mitochondrial depolarization
-> GO:1905091 positive regulation of type 2 mitophagy

- [ ] OBSOLETE/MERGE
GO:1904924    negative regulation of mitophagy in response to mitochondrial depolarization
-> GO:1905090  negative regulation of type 2 mitophagy

(these have the same meaning)

- [ ] OUTSTANDING QUESTION
how does
GO:0035695    mitophagy by internal vacuole formation fit?
since ONLY ONE EXP SPATA18 PMID:21264228
(is this also equivalent to microautophagy?)

**Comment by ValWood** [comment]
https://github.com/geneontology/go-announcements/issues/829

**Comment by ValWood** [comment]
Based on the comment:
mitophagy by internal vacuole formation
In this mechanism of mitochondrion degradation, the mitochondrion is directly engulfed by a lysosome-like vacuole. It is therefore distinct from canonical autophagy, which is mediated by a double-membrane autophagosome.

I will leave this term distinct.
