### ISSUE TITLE
GO terms mapped to EC:1.3.8.5

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26437]
The following 2 GO terms both have an EC:1.3.8.5 xref:

id: GO:0003853
name: 2-methylacyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: 2-methylbutanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = (2E)-2-methylbut-2-enoyl-CoA + reduced [electron-transfer flavoprotein]." [PMID:10989435, PMID:6401712, RHEA:43780]
xref: EC:1.3.8.5
xref: RHEA:43780
is_a: GO:0003995 ! acyl-CoA dehydrogenase activity
=> 3 EXP annotations (2x Human ACADSB, 1x potato 2MBCD)

id: GO:0102035
name: isobutyryl-CoA:FAD oxidoreductase activity
def: "Catalysis of the reaction: H+ + isobutyryl-CoA + FAD = methacrylyl-CoA + FADH2." [GOC:pz, PMID:3988734]
xref: EC:1.3.8.5
is_a: GO:0003995 ! acyl-CoA dehydrogenase activity
=> 0 EXP annotations

===

https://enzyme.expasy.org/EC/1.3.8.5 says:
Name: short-chain 2-methylacyl-CoA dehydrogenase 
Reaction: 2-methylbutanoyl-CoA + H(+) + oxidized [electron-transfer flavoprotein] <=> (2E)-2-methylbut-2-enoyl-CoA + reduced [electron-transfer flavoprotein]

There seems to be a mismatch in specificity between the name (short-chain 2-methylacyl) and the reaction (2-methylbutanoyl-CoA) here?

[RHEA does map EC:1.3.8.5 ](https://www.rhea-db.org/rhea?query=ec%3A1.3.8.5) to both reactions:

RHEA:43780 | 2-methylbutanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = (2E)-2-methylbut-2-enoyl-CoA+ reduced [electron-transfer flavoprotein]

RHEA:44180 | 2-methylpropanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = (2E)-2-methylpropenoyl-CoA+ reduced [electron-transfer flavoprotein]

 (Note: 'isobutyryl-CoA' has synonym '2-methylpropanoyl-CoA', and 'methacrylyl-CoA' has synonym  '2E)-2-methylpropenoyl-CoA' in CHEBI)

@kaxelsen Can you comment on this please?

===

Possible tasks (pending Kristian's input):

- [ ] Remove EC:1.3.8.5 from GO:0102035 -> No, EC:1.3.8.5 describes an enzyme that can act on both substrates here (see Kristian's reply below)
- [x] add RHEA:44180 to GO:0102035
- [x] Update GO:0102035 name and def to match RHEA:44180
- [x] Update GO:0003853 name to '2-methylbutanoyl-CoA dehydrogenase activity' to match GO/EC/RHEA def
- [x] change parent of both GO terms to the more specific "short-chain-acyl-CoA dehydrogenase activity" (GO:0016937) since 2-methylbutanoyl-CoA and 2-methylpropanoyl-CoA both have a chain length of <C6.

**Comment by kaxelsen** [comment]
> There seems to be a mismatch in specificity between the name (short-chain 2-methylacyl) and the reaction (2-methylbutanoyl-CoA) here?

No, it is fine. The chains can be branched as long as they are still aliphatic. Regarding the name, the EC 1.3.8.5 has the highest activity with 2-methylbutanoyl-CoA but also has activity with other short-chain 2-methylacyl-CoA cf pmid:[11013134](https://pubmed.ncbi.nlm.nih.gov/11013134)

**Comment by sjm41** [comment]
Thanks @kaxelsen. Yes, I see in pmid:[11013134](https://pubmed.ncbi.nlm.nih.gov/11013134) that the enzyme acts on both 2-methylbutyryl-CoA (aka 2-methylbutanoyl-CoA) and isobutyryl-CoA (aka 2-methylpropanoyl-CoA), so it should remain an xref on both GO terms mentioned above.

**Comment by sjm41** [comment]
@pgaudet Looking at this again, with the wider aim of not having duplicate ECs on different GO terms, I think we should merge the following two EC:1.3.8.5-based GO terms:

id: GO:0003853
name: 2-methylbutanoyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: 2-methylbutanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = (2E)-2-methylbut-2-enoyl-CoA + reduced [electron-transfer flavoprotein]." [PMID:10989435, PMID:6401712, RHEA:43780]
xref: EC:1.3.8.5
xref: KEGG_REACTION:R03169
xref: MetaCyc:2-METHYLACYL-COA-DEHYDROGENASE-RXN
xref: RHEA:43780
is_a: GO:0016937 ! short-chain fatty acyl-CoA dehydrogenase activity

id: GO:0102035
name: 2-methylpropanoyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: 2-methylpropanoyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = (2E)-2-methylpropenoyl-CoA + reduced [electron-transfer flavoprotein]." [PMID:3988734, RHEA:44180]
xref: EC:1.3.8.5
xref: MetaCyc:MEPROPCOA-FAD-RXN
xref: RHEA:44180
is_a: GO:0016937 ! short-chain fatty acyl-CoA dehydrogenase activity

Merged GO term would look like something like this:

id: GO:0102035
name: short-chain 2-methyl fatty acyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: a short-chain 2-methyl fatty acyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = a short-chain (2E)-2-methyl-2-enoyl-CoA + reduced [electron-transfer flavoprotein]." [MetaCyc:RXN-21774]
xref: EC:1.3.8.5 [exactMatch]
xref: MetaCyc:RXN-21774 [exactMatch]
is_a: GO:0016937 ! short-chain fatty acyl-CoA dehydrogenase activity
