### ISSUE TITLE
xref issues on acyl-CoA hydrolase activity child terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26441]
id: GO:0052817
name: very long chain acyl-CoA hydrolase activity
def: "Catalysis of the reaction: H2O + a very long chain acyl-CoA = a very long chain carboxylate + CoA. A very long chain has chain length greater than C18." [EC:3.1.2.19]
synonym: "very long-chain acyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "very long-chain acyl-thioester hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "very long-chain hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "very long-chain-acyl-CoA hydrolase activity" RELATED [EC:3.1.2.19]
is_a: GO:0047617 ! acyl-CoA hydrolase activity

- [x] Add RHEA:67072
- [x] change def and name to match RHEA:67072 (and update chain length def as per #26445)
- [x] replace EC:3.1.2.19 def xref with RHEA:67072 (see GO:0047380 below)
- [x] Remove synonyms attribution to EC:3.1.2.19 (see GO:0047380 below)

---

id: GO:0052816
name: long-chain acyl-CoA hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + a long-chain acyl-CoA = a long-chain carboxylate + CoA. A long chain is a chain of greater than 12 carbons in length." [EC:3.1.2.19]
synonym: "long-chain acyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "long-chain acyl-thioester hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "long-chain hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "long-chain-acyl-CoA hydrolase activity" RELATED [EC:3.1.2.19]
is_a: GO:0047617 ! acyl-CoA hydrolase activity
created_by: ai
creation_date: 2011-10-25T05:31:11Z

- [x] Add RHEA:67680
- [x] change def and name to match RHEA:67680 (and update chain length def as per #26445)
- [x] replace EC:3.1.2.19 def xref with RHEA:67680 (see GO:0047380 below)
- [x] Remove synonyms attribution to EC:3.1.2.19 (see GO:0047380 below)

---

id: GO:0052815
name: medium-chain acyl-CoA hydrolase activity
def: "Catalysis of the reaction: H2O + a medium-chain acyl-CoA = a medium-chain carboxylate + CoA. A medium chain is a chain of between eight and twelve carbons in length." [EC:3.1.2.19]
synonym: "medium-chain acyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "medium-chain acyl-thioester hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "medium-chain hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "medium-chain-acyl-CoA hydrolase activity" RELATED [EC:3.1.2.19]
is_a: GO:0047617 ! acyl-CoA hydrolase activity

- [x] Add RHEA:68184
- [x] change def and name to match RHEA:68184 (and update chain length def as per #26445)
- [x] replace EC:3.1.2.19 def xref with RHEA:68184 (see GO:0047380 below)
- [x] Remove synonyms attribution to EC:3.1.2.19 (see GO:0047380 below)

---

id: GO:0047380
name: ADP-dependent medium-chain-acyl-CoA hydrolase activity
def: "Catalysis of the reaction: H2O + a medium-chain acyl-CoA = a medium-chain carboxylate + CoA. Requires ADP." [EC:3.1.2.19, MetaCyc:3.1.2.19-RXN]
synonym: "ADP-dependent medium-chain acyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "ADP-dependent medium-chain acyl-CoA hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "ADP-dependent medium-chain acyl-thioester hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "ADP-dependent medium-chain hydrolase activity" RELATED [EC:3.1.2.19]
synonym: "ADP-dependent myristoyl-CoA thioesterase activity" NARROW [EC:3.1.2.19]
synonym: "ADP-dependent-medium-chain-acyl-CoA hydrolase activity" RELATED [EC:3.1.2.19]
xref: EC:3.1.2.19
xref: MetaCyc:3.1.2.19-RXN
is_a: GO:0052815 ! medium-chain acyl-CoA hydrolase activity

- [ ] add RHEA:68184 here as a broad xref??  RHEA maps RHEA:68184 (no mention of ADP-dependency) to EC:3.1.2.19 ("ADP-dependent medium-chain-acyl-CoA hydrolase")
(I guess the question is, are there ADP-**independent** medium-chain-acyl-CoA hydrolase activities?) Do you know @kaxelsen ?

---

id: GO:0047379
name: ADP-dependent short-chain-acyl-CoA hydrolase activity
def: "Catalysis of the reaction: H2O + a short-chain acyl-CoA = a short-chain carboxylate + CoA." [EC:3.1.2.18, MetaCyc:3.1.2.18-RXN]
synonym: "ADP-dependent propionyl coenzyme A hydrolase activity" NARROW [EC:3.1.2.18]
synonym: "ADP-dependent propionyl-CoA hydrolase activity" NARROW [EC:3.1.2.18]
synonym: "ADP-dependent propionyl-CoA thioesterase activity" NARROW [EC:3.1.2.18]
synonym: "ADP-dependent short-chain acyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.18]
synonym: "ADP-dependent short-chain acyl-CoA hydrolase activity" RELATED [EC:3.1.2.18]
synonym: "ADP-dependent short-chain acyl-CoA thioesterase activity" RELATED [EC:3.1.2.18]
synonym: "ADP-dependent-short-chain-acyl-CoA hydrolase activity" RELATED [EC:3.1.2.18]
xref: EC:3.1.2.18
xref: MetaCyc:3.1.2.18-RXN

- [ ] add RHEA:68180 here as a broad xref??  RHEA maps RHEA:68180 (no mention of ADP-dependency) to EC:3.1.2.18 ("ADP-dependent short-chain-acyl-CoA hydrolase")
- [ ] add new parent to this term for 'short-chain acyl-CoA hydrolase activity' (exact xref RHEA:68180), to mirror how the two medium-chain terms are currently handled (see above)??
(I guess the question is, are there ADP-**independent** short-chain-acyl-CoA hydrolase activities?) Do you know @kaxelsen ?

**Comment by pgaudet** [comment]
Hi @sjm41 

Should we obsolete GO:0047380 (no annotations) and GO:0047379 (1 annotation, paper does not mention ADP). 

There are reference cited in the BRENDA records:
https://pubmed.ncbi.nlm.nih.gov/2901416/
https://pubmed.ncbi.nlm.nih.gov/2570608/

but I cannot tell which genes these paper describe. 

I propose we obsolete these for now and restore if needed. 

Unless @kaxelsen has more evidence for this reaction?

**Comment by pgaudet** [comment]
We could create 'short chain' - looks like many terms need to be reclassified: 

<img width="460" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/1fcf38ab-398f-472c-b6ce-b1f3f4392bbb">


Also, in seems that base on its children, 'GO:0016289 CoA hydrolase activity' means the same as 'GO:0047617 acyl-CoA hydrolase activity'. 

What do you think ?

**Comment by sjm41** [comment]
Right. 'GO:0016289 CoA hydrolase activity' says "Catalysis of the reaction: X-CoA + H2O = X + CoA; X may be any group.", but then 'X' is 'CoA' in all the child terms.

That said, I see there are a couple of things to consider/fix:
1. GO:0047617 acyl-CoA hydrolase activity has def "Catalysis of the reaction: acyl-CoA + H2O = CoA + a carboxylate." But based on the xrefs (EC:3.1.2.20, RHEA:16781) and children,  the name should be changed to "fatty acyl-CoA hydrolase activity" and the def should be "Catalysis of the reaction: a fatty acyl-CoA + H2O = a fatty acid + CoA + H+".

2. Then, I think 'GO:0016289 CoA hydrolase activity' could be renamed 'acyl-CoA hydrolase activity' with def "an acyl-CoA + H2O = a carboxylate + CoA + H+" with xref [RHEA:70423](https://www.rhea-db.org/rhea/70423)

Talk later....

**Comment by kaxelsen** [comment]
@sjm41 
> * add RHEA:68184 here as a broad xref??  RHEA maps RHEA:68184 (no mention of ADP-dependency) to EC:3.1.2.19 ("ADP-dependent medium-chain-acyl-CoA hydrolase")
>       (I guess the question is, are there ADP-**independent** medium-chain-acyl-CoA hydrolase activities?) Do you know @kaxelsen ?

No, I'm not very well into acyl-CoA hydrolases. Both EC 3.1.2.18 and EC 3.1.2.19 are defined based on pmid:[2901416](https://pubmed.ncbi.nlm.nih.gov/2901416) describing "A novel type of short- and medium-chain acyl-CoA hydrolases in brown adipose tissue mitochondria", but only EC 3.1.2.19 has links to Swiss-Prot, and they are all 5 to enterobacteria

**Comment by pgaudet** [comment]
I only find 
https://www.uniprot.org/uniprotkb/Q7NUH6/entry
which has an automatic annotation to EC 3.1.2.19 - but how did that get predicted? 

Discussion with @sjm41 : we will obsolete and keep xrefs on the appropriate parent

**Comment by sjm41** [comment]
Clarifying info from Lucila Aimo regarding acyl vs fatty acyl:
- RHEA:70423, the R represents any acyl chain, including fatty acyl chains
- RHEA:16781, the R represents a fatty acyl chain (a fatty acid is a carboxylic acid with an aliphatic chain). This reaction does not include phenyls, nor cholesteryl, nor acetyl, formyl or any acyl that is not a fatty acid.

In other words:
- If the R group on the acyl-CoA is an aliphatic chain (ie. a hydrocarbon chain with no rings), then the molecule is classed as a fatty acyl-coA.
- But if the R group contains a ring (e.g. phenylacetyl-CoA, RHEA:70427), or contains atoms other than H/C (e.g. malonyl-CoA, RHEA:40219), or has no carbons (e.g. formyl-CoA, RHEA:19741), or has only 1 carbon meaning there is no ‘chain' (acetyl-CoA, RHEA:20289) then it is not a fatty-acyl-CoA, though it is still an acyl-CoA.

**Comment by pgaudet** [comment]
Sounds good!

**Comment by pgaudet** [comment]
Are there 2 or 3 terms to obsolete? you have GO:0047380 twice in the list.

**Comment by pgaudet** [comment]
GO:0047379 ADP-dependent short-chain-acyl-CoA hydrolase activity >> replace by new term 'short-chain fatty acyl-CoA hydrolase activity' 
GO:0047380 ADP-dependent medium-chain-acyl-CoA hydrolase activity >> replace by parent GO:0052815 medium-chain acyl-CoA hydrolase activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141126
+name: short-chain fatty acyl-CoA hydrolase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a small-chain fatty acyl-CoA + H2O = a medium-chain fatty acid + CoA + H+. A small-chain fatty acid has an aliphatic tail of less than 6 carbons." [RHEA:68180]
+comment: While there is not universal consensus on the lengths of short-, medium-, long- and very-long-chain fatty acids, the GO uses the definitions in ChEBI (see CHEBI:26666, CHEBI:59554, CHEBI:15904 and CHEBI:27283).
+xref: EC:3.1.2.18 {source="skos:relatedMatch"}
+xref: RHEA:68180
+is_a: GO:0047617 ! fatty acyl-CoA hydrolase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26441" xsd:anyURI
+created_by: pg
+creation_date: 2023-12-08T09:05:55Z

**Comment by sjm41** [comment]
Thanks @pgaudet ! But can you change 'small' and 'medium' to 'short' in the def?
That is:
+def: "Catalysis of the reaction: a **short**-chain fatty acyl-CoA + H2O = a **short**-chain fatty acid + CoA + H+. A **short**-chain fatty acid has an aliphatic tail of less than 6 carbons." [RHEA:68180]

**Comment by pgaudet** [comment]
Also changed 'very-long-chain acyl-CoA dehydrogenase activity' to very-long-chain FATTY acyl-CoA dehydrogenase activity : isn't this right ?

**Comment by sjm41** [comment]
Yep. I just starting to look at the acyl-CoA dehydrogenase branch systematically to see if other similar changes are needed there (as done for acyl-CoA hydrolase branch here). So might be another ticket coming....

**Comment by pgaudet** [comment]
ah yes thanks! I am spreading out...

**Comment by pgaudet** [comment]
Will do the last 2 obsoletions here: https://github.com/geneontology/go-ontology/issues/26597

**Comment by sjm41** [comment]
Looks like I mistakingly made "3-hydroxyisobutyryl-CoA hydrolase activity (GO:0003860)" a child of "short-chain fatty acyl-CoA **dehydrogenase** activity (GO:0016937)" instead of the intended "short-chain fatty acyl-CoA **hydrolase** activity ( GO:0141126)".
I will fix this now.

**Comment by sjm41** [comment]
Also just noticed this outstanding task mentioned above:
> For some reason, I couldn't add RHEA:70423 xref to GO:0016289 "acyl-CoA hydrolase activity" - can you see if you can do that without getting an error?

I'll try to do this again now.

**Comment by sjm41** [comment]
>>For some reason, I couldn't add RHEA:70423 xref to GO:0016289 "acyl-CoA hydrolase activity" - can you see if you can do that without getting an error?
>I'll try to do this again now.

Nope, failed again.  Here's the error:
```
FAIL Rule ../sparql/one-to-one-xrefs-by-subject-violation.sparql: 1 violation(s)
c,one_to_one_prefix
http://purl.obolibrary.org/obo/GO_0016289,RHEA:
```

@pgaudet Do you see what the issue is here??

**Comment by pgaudet** [comment]
No, this is really weird. I am trying here: https://github.com/geneontology/go-ontology/pull/27911

**Comment by balhoff** [comment]
The xrefs from the obsolete term GO:0047901 are being transferred to its replacement during the build. This causes the multiple xrefs error. This is a really confusing system, and I recently opened an issue to fix it: #27821

**Comment by sjm41** [comment]
Aha, thanks @balhoff 

@pgaudet All the term xrefs on this obsolete term should just be removed, right?

id: GO:0047901
name: obsolete formyl-CoA hydrolase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: formyl-CoA + H2O = CoA + formate + H+." [EC:3.1.2.10, RHEA:19741]
comment: This term was obsoleted because the enzyme that catalyzes this reaction has not been identified.
synonym: "formyl coenzyme A hydrolase activity" RELATED [EC:3.1.2.10]
xref: EC:3.1.2.10
xref: KEGG_REACTION:R00521
xref: MetaCyc:FORMYL-COA-HYDROLASE-RXN
xref: RHEA:19741
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26443" xsd:anyURI
is_obsolete: true
replaced_by: GO:0016289

**Comment by sjm41** [comment]
Looked at the obsoletion doc.....

5. Cross-references
Check if there are cross-references to Reactome, RHEA, EC, MetaCyc xref to the term. If there are, notify the various groups in the obsoletion email.
These cross-references should be removed.
There is no need to edit Reactome xrefs are imported automatically from a file supplied by Reactome.
Definition cross-references to RHEA, EC, MetaCyc should be also be removed. Replace by GOC:curators if no reference is left.

So, I will go ahead and remove the term and def xrefs on GO:0047901, and then try re-adding RHEA:70423 xref to GO:0016289.

**Comment by sjm41** [comment]
Success!

id: GO:0016289
name: acyl-CoA hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: an acyl-CoA + H2O = a carboxylate + CoA + H+." [RHEA:70423]
synonym: "CoA hydrolase activity" BROAD []
xref: RHEA:70423
is_a: GO:0016790 ! thiolester hydrolase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26441" xsd:anyURI


id: GO:0047901
name: obsolete formyl-CoA hydrolase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: formyl-CoA + H2O = CoA + formate + H+." [GOC:curators]
comment: This term was obsoleted because the enzyme that catalyzes this reaction has not been identified.
synonym: "formyl coenzyme A hydrolase activity" RELATED []
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26443" xsd:anyURI
is_obsolete: true
replaced_by: GO:0016289
