### ISSUE TITLE
glutaryl-CoA hydrolase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26443]
id: GO:0044466
name: glutaryl-CoA hydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: glutaryl-CoA + H2O = CoA + glutarate." [GOC:pm, PMID:16141203]
synonym: "glutaryl-CoA thioesterase activity" EXACT []
xref: EC:3.1.2.3
is_a: GO:0047617 ! acyl-CoA hydrolase activity
created_by: jl
creation_date: 2012-01-17T04:16:43Z

But EC:3.1.2.3 is 'succinyl-CoA hydrolase' and is already correctly a xref for GO:0004778 succinyl-CoA hydrolase activity

- [ ] There doesn't appear to be an EC for this reaction, so just remove EC:3.1.2.3 xref.
- [ ] Add RHEA:40575
- [ ] Update def to match RHEA:40575

- [ ] Also, chain length of glutaryl-CoA is 5C, so parent can be changed to a more specific 'short-chain-acyl-CoA hydrolase activity' parent, which is consistent with its [MetaCyc classification](https://biocyc.org/compound?orgid=META&id=GLUTARYL-COA#tab=ONT).  But need to wait for resolution of 'short-chain-acyl-CoA hydrolase activity' issue raised in #26441 before doing that.

**Comment by pgaudet** [comment]
Hi @sjm41 

Glutaryl-CoA seems to represent a specific substrate - looking at RHEA:40575, the papers cited talk about acyl-CoA thioesterase and succinyl-CoA thioesterase. This terms seems out of scope for GO; what do you think ? 

Thanks, Pascale

**Comment by sjm41** [comment]
QuickGO says there are only 5 annotations to this term, all of which are EC2GO via the erroneous EC:3.1.2.3 association. So looks like nobody is really using this term. I think it can go.  I'll re-assign this ticket to you to do that.
Thanks!

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0044466 glutaryl-CoA hydrolase activity. The reason for obsoletion is that this term represents a specific substrate of GO:0047617 acyl-CoA hydrolase activity, and therefore is outside the scope of GO. 

There are no annotations or mappings to this term; this term is not present in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26443

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsolete [formyl-CoA hydrolase activity](http://purl.obolibrary.org/obo/GO_0047901)
No annotations, no entry linked to the RHEA and EC xrefs. Citing a 1963 paper: https://www.ncbi.nlm.nih.gov/pubmed/14063284
