### ISSUE TITLE
Fix branch 'suppression by virus of host gene expression' >> change labels to 'symbiont-mediated'...

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26747]
- [x] 'suppression by virus of host gene expression'  >> host transcription shut-off
& children 
- [x] 'suppression by virus of host mRNA processing'
- [x] 'suppression by virus of host transcription'
- [x] 'suppression by virus of host mRNA transcription via inhibition of RNA polymerase II activity'
- [x] 'suppression by virus of host transcription initiation from RNA polymerase II promoter' >> PMID: 21178485 
- [x] 'induction by virus of catabolism of host mRNA'  >> symbiont-mediated degradation of host mRNA

note that these processes probably only occur in viruses; can add a note in the definition

@genegodbold If you have references, please add

**Comment by genegodbold** [comment]
**Bacteria messing with host translation**
- **Burkholderia lethal factor 1** (BLF1) from _Burkholderia pseudomallei_: BLF1 deamidates glutamine339 of host eIF4A (eukaryotic initiation factor 4A). This inactivates RNA helicase activity required to unwind secondary structure of mRNA, which in turn, leads to inhibition of protein synthesis in human cells [PMID:22817745].
- **Cholix toxin** from _Vibrio cholera_: Cholix toxin transfers an ADP-ribose moiety from NAD to the eukaryotic ribosomal elongation factor 2 (EF-2), preventing translation from that ribosome [PMID:25494717]. 
- **LegK4** from _Legionella pneumophila_: LegK4 is an effector kinase of Legionella that phosphorylates host cytosolic protein chaperone Hsp70 on Thr495 within its substrate-binding domain. Phosphorylation inhibits its ATPase activity and also its ability to fold proteins. This results in a global inhibition of translation [PMID:30827827].
- **Substrate of Icm/Dot I** (SidI; lpg2504) from _Legionella pneumophila_:  SidI inhibits protein translation both in vitro and in cells infected with L. pneumophila. SidI binds host elongation factors eEF1A and also eEF1Bgamma. As little as 30 ng SidI was able to block translation in an in vitro system. The following SidI mutants, when expressed in yeast, were not toxic: Glu482Lys, Arg453Leu and Arg453Pro. They weren't completely devoid of the ability to inhibit protein synthesis as indicated by the in vitro translation system [PMID:19386084].

**Comment by genegodbold** [comment]
**Viruses messing with host translation**
- **BGLF5** from Epstein-Barr virus: BGLF5 is a viral alkaline nuclease that promotes the localization of the cellular polyA-binding protein (PABPC) to the nucleus. PABPC normally functions to enhance mRNA stability in the cytoplasm. The depletion of cytoplasmic PABPC is expected to impair the stability of cellular transcripts that have reached the cytoplasm [PMID:19468299]. BGLF5 can degrade cellular and viral mRNAs regardless of whether they are polyadenylated to "shutoff" protein translation [PMID:22696660]. BGLF5 induces host translation shutoff by degradation of host mRNAs. Expression of BGLF5 in insect Sf9 cells is sufficient to globally reduce synthesis of new polypeptide chains compared to controls. One of the consequences of translational shutoff is a block in the synthesis of HLA-I and HLA-II and a resulting diminution of antigen-presenting complexes at the surface of infected cells [PMID:17360652]. 
-

**Comment by genegodbold** [comment]
There are SO many of these with SO many mechanisms.

**Comment by pgaudet** [comment]
Obsolete 'GO:0046778 modification by virus of host mRNA processing': no annotations, no mappings. Unnecessary grouping class.

**Comment by pgaudet** [comment]
obsolete 'GO:0046783 modification by virus of host polysomes' >> represents a localization, not a process. 
No annotations, no mappings

**Comment by pgaudet** [comment]
Obsolete [modulation by symbiont of host translation](http://purl.obolibrary.org/obo/GO_0044073) 
No annotations, no references, no mappings
same as [symbiont-mediated perturbation of host translation](http://purl.obolibrary.org/obo/GO_0019057) (was: modulation by virus of host translation)

**Comment by pgaudet** [comment]
Dear all 

The proposal has been made to obsolete the following viral terms: 

- GO:0046778 modification by virus of host mRNA processing': no annotations, no mappings. Unnecessary grouping class.
- GO:0046783 modification by virus of host polysomes
- GO:0019056 modulation by virus of host transcription
- GO:0044073 modulation by symbiont of host translation
- GO:0044074 negative regulation by symbiont of host translation

**Comment by pgaudet** [comment]
Another reference for symbiont-mediated degradation of host mRNA from @genegodbold 
> Viral host shutoff protein (Vhs, UL41) from HHV-1: UL41 is an endoribonuclease that cuts host mRNA and thereby shuts off host cell protein translation [PMID12163576][PMID16477041]. UL41 selectively targets cyclic GMP-AMP synthase (cGAS) mRNA for destruction.
