### ISSUE TITLE
Obsoletion request: GO:0052594 aminoacetone:oxygen oxidoreductase(deaminating) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26778]
Obsolete GO terms that represent specific substrate of primary amine oxidase activity ; GO:0008131:

- [x] GO:0052594 aminoacetone:oxygen oxidoreductase(deaminating) activity:   Maps to RHEA:28186, which has no associated proteins and no references; no annotations (was mapped to EC:1.4.3.21, see #26777)
- [x] GO:0052596  phenethylamine:oxygen oxidoreductase (deaminating) activity:  no annotations (was mapped to EC:1.4.3.21, see #26777)
- [x] GO:0052596 phenethylamine:oxygen oxidoreductase (deaminating) activity:  no annotations (was mapped to EC:1.4.3.21, see #26777)
