### ISSUE TITLE
epoxide hydrolase activity (GO:0004301)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27074]
Currently we have this:
```
ether hydrolase activity (EC:3.3.2.-)
|__epoxide hydrolase activity (EC:3.3.2.10, RHEA:19037)
    |__epoxide hydrolase A activity (EC:3.3.2.-)
    |__epoxide hydrolase B activity (EC:3.3.2.-)
    |__juvenile hormone epoxide hydrolase activity (EC:3.3.2.-)
    |__limonene-1,2-epoxide hydrolase activity (EC:3.3.2.8, RHEA:10700)
    |__phenanthrene-epoxide hydrolase activity (EC:3.3.2.-)
        |__phenanthrene-1,2-epoxide hydrolase activity (none)
        |__phenanthrene-3,4-epoxide hydrolase activity (none)
        |__phenanthrene-9,10-epoxide hydrolase activity (none)
              |__phenanthrene-9,10-epoxide hydrolase (9R,10R-forming) activity (EC:3.3.2.-)
              |__phenanthrene-9,10-epoxide hydrolase (9S,10S-forming) activity (EC:3.3.2.-)
|__cis-stilbene-oxide hydrolase activity (EC:3.3.2.9, RHEA:23900)
|__hepoxilin-epoxide hydrolase activity (EC:3.3.2.7, RHEA:16665)
```

- [x] Remove partial EC:3.3.2.- xrefs from all terms except 'ether hydrolase activity'
- [x] Change parent of 'cis-stilbene-oxide hydrolase activity' and 'hepoxilin-epoxide hydrolase activity' to the more specific 'epoxide hydrolase activity' (I checked this with Anne at RHEA - she agrees and is making the corresponding changes to the RHEA relationships)
- [x] Change GO def of 'epoxide hydrolase activity' from "Catalysis of the reaction: an epoxide + H2O = a glycol." to "Catalysis of the reaction: an epoxide + H2O = an ethanediol" (to match def at EC/RHEA)
