### ISSUE TITLE
S-nitrosoglutathione reductase activity (GO:0080007)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27135]
I was reviewing the changes to GO:0080007 in #23357 as they affected a fly gene (Fdh, FBgn0011768).
Current GO:0080007 term entry is:
```
id: GO:0080007
name: S-nitrosoglutathione reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: glutathione N-hydroxysulfenamide + NADH + H+ = S-nitrosoglutathione + NAD+." [PMID:11260719, PMID:27094420, PMID:30795534]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity
is_a: GO:0051903 ! S-(hydroxymethyl)glutathione dehydrogenase activity
```
Meaning the current tree looks like this:
```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616) [EC:1.1.1.-]
|__alcohol dehydrogenase [NAD(P)+] activity (GO:0018455) [EC:1.1.1.71]
    |__alcohol dehydrogenase (NAD+) activity (GO:0004022) [EC:1.1.1.1]
        |__*S-nitrosoglutathione reductase activity (GO:0080007) [no EC/RHEA]*
|__S-(hydroxymethyl)glutathione dehydrogenase activity (GO:0051903) [EC:1.1.1.284]
    |__S-(hydroxymethyl)glutathione dehydrogenase NAD activity (GO:0106322) [EC:1.1.1.284, RHEA:19985]
    |__S-(hydroxymethyl)glutathione dehydrogenase NADP activity (GO:0106321) [EC:1.1.1.284, RHEA:19981]
    |__*S-nitrosoglutathione reductase activity (GO:0080007) [no EC/RHEA]*
```

As noted in the previous ticket, the different activities ascribed to the GSNOR (aka FDH, ADH5-class III) enzyme are complicated, but the recent PMID:30795534 review sums up the situation well - from Fig 1 legend: 
"Reaction mechanisms of alcohol dehydrogenase/S-nitrosoglutathione reductase (ADH3/GSNOR) in formaldehyde and S-nitrosoglutathione catabolism.
(A) In the dehydrogenase mode, GSNOR using NAD+ as a coenzyme catalyzes the oxidation of S-hydroxymethylglutathione (HMGSH), spontaneously formed from formaldehyde and glutathione to S-formylglutathione, which was further hydrolyzed to glutathione and formate by S-formylglutathione hydrolase.
(B) In the reductase mode, GSNOR catalyzes the reduction of S-nitrosoglutathione (GSNO) using NADH to an unstable intermediate N-hydroxysulfinamide (GSNHOH). Depending on the local concentration of GSH, GSNHOH is either decomposed to glutathione disulfide (GSSG) and hydroxylamine at high GSH levels, or at low GSH levels spontaneously converts to glutathione sulfinamid (GSONH2), which can be hydrolyzed to glutathione sulfinic acid (GSOOH) and ammonia."

Reaction A is GO:0106322 "S-(hydroxymethyl)glutathione dehydrogenase NAD activity" (EC:1.1.1.284/RHEA:19985), def: "Catalysis of the reaction: S-(hydroxymethyl)glutathione + NAD+ = S-formylglutathione + NADH + H+."

Reaction B is GO:0080007 "S-nitrosoglutathione reductase activity", which, as shown above, has no RHEA.
However, there is a RHEA for the NADP version of this reaction (RHEA:63500), and I have just requested they also make the NAD version.

Importantly, the EC:1.1.1.284 entry (which of course represents the **enzyme**, not the activities), says:
Name: S-(hydroxymethyl)glutathione dehydrogenase
Reaction: NADP(+) + S-(hydroxymethyl)glutathione <=> H(+) + NADPH + S-formylglutathione
Reaction: NAD(+) + S-(hydroxymethyl)glutathione <=> H(+) + NADH + S-formylglutathione
Comment: Also specifically reduces S-nitrosylglutathione*

* Seems 'S-nitrosylglutathione' is a old synonym for S-nitrosoglutathione (GSNO) - e.g. see PMID:8284942 - so, this EC corresponds to both Reaction A and B mentioned above.

So I think we need to make the following changes:

- [x] Change GO:0080007 name to "S-nitrosoglutathione reductase (NADH) activity"
- [x]  Remove both current is_a parents on GO:0080007 and replace with "is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor" (EC:1.1.1.-)
- [x] Rewrite GO:0080007 def to use the chemical names in the related RHEA:63500 entry and put the NAD/NADH on the correct sides of the equation (!). That is: "Catalysis of the reaction: S-nitrosoglutathione + NADH + H(+) = sulfinamide glutathione + NAD(+). [PMID:11260719, PMID:27094420, PMID:30795534]"
- [x] Add this comment GO:0080007: "Sulfinamide glutathione (GSNHOH) is an unstable intermediate. At high GSH levels, it is decomposed to glutathione disulfide (GSSG) and hydroxylamine. At low GSH levels, GSNHOH  spontaneously converts to glutathione sulfinamid (GSONH2), which can be hydrolyzed to glutathione sulfinic acid (GSOOH) and ammonia. (PMID:30795534)"
- [x] Make new GO term for the NADP reaction (RHEA:63500) - annotated to 319 proteins in UniProt. Name = "S-nitrosoglutathione reductase (NADPH) activity"
- [ ] Add newly requested RHEA to GO:0080007 when available.
- [x] Tweak name of "S-(hydroxymethyl)glutathione dehydrogenase activity" to "S-(hydroxymethyl)glutathione dehydrogenase [NAD(P)H] activity"
- [x] Make EC:1.1.1.284 a BroadMatch xref on all these terms.

Final tree would look like this:
```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616) [EC:1.1.1.-]
|__S-(hydroxymethyl)glutathione dehydrogenase  [NAD(P)H] activity (GO:0051903) [EC:1.1.1.284]
    |__S-(hydroxymethyl)glutathione dehydrogenase NAD activity (GO:0106322) [EC:1.1.1.284, RHEA:19985]
    |__S-(hydroxymethyl)glutathione dehydrogenase NADP activity (GO:0106321) [EC:1.1.1.284, RHEA:19981]
|__S-nitrosoglutathione reductase (NADH) activity (GO:0080007) [EC:1.1.1.284, new RHEA]
|__S-nitrosoglutathione reductase (NADPH) activity (NTR) [EC:1.1.1.284, RHEA:63500]
```

Note: I don't know if we also want/need a "S-nitrosoglutathione reductase [NAD(P)H] activity" grouping term here?

**Comment by pgaudet** [comment]
Hi @sjm41 

As described in the doc here: https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#NAD/NADP_cofactors
'NAD(P)H' terms should be used for cases where the cofactor is not known. If we always know the cofactor, them we dont add the grouping term.  Is this the case here?

**Comment by sjm41** [comment]
OK. Given that (i) we currently only have one "S-nitrosoglutathione reductase activity" term in the GO, which is for NAD; and (ii) there's no EC/RHEA corresponding to NAD(P) reaction that could potentially use either, I conclude that we don't need a "S-nitrosoglutathione reductase [NAD(P)H] activity" grouping term here. (At least, not at the moment.)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160163
+name: S-nitrosoglutathione reductase (NADPH) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: H(+) + NADPH + S-nitrosoglutathione = NADP(+) + sulfinamide glutathione." [RHEA:63500]
+xref: EC:1.1.1.284 {source="skos:broadMatch"}
+xref: RHEA:63500
+is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27135" xsd:anyURI
+created_by: rynl
+creation_date: 2024-02-28T01:46:34Z

**Comment by sjm41** [comment]
Thanks @raymond91125. I'll comment here when RHEA have made the new term.

**Comment by sjm41** [comment]
Just received an email from Anne at RHEA:
>RHEA:78371 H+ + NADH + S-nitrosoglutathione = NAD+ + sulfinamide glutathione
(available soon).
So we should be able to add RHEA:78371 to GO:0080007 soon.

**Comment by sjm41** [comment]
Hold on - Anne has also pointed out some confusion about these reactions on my part.  I'll sort this out and post another comment about the final resolution later on today.

**Comment by sjm41** [comment]
Hi @raymond91125 

So I'd been confusing 'S-(hydroxysulfenamide)glutathione (CHEBI:229723), aka GSNHOH' with 'sulfinamide glutathione (CHEBI:145547)', which are related but different chemicals....

I've sorted this out with Anne at RHEA, and they have updated RHEA:63500 & RHEA:78371 to have the following equations:
RHEA:63500 H+ + NADPH + S-nitrosoglutathione = NADP+ + S-(hydroxysulfenamide)glutathione
RHEA:78371 H+ + NADH + S-nitrosoglutathione = NAD+ + S-(hydroxysulfenamide)glutathione
(RHEA:78371 is mapped to MetaCyc:RXN-17884)

So, the remaining tasks on the GO side are:
- [ ] Update defs (and comment) of GO:0080007 and GO:0160163 to use 'S-(hydroxysulfenamide)glutathione' rather than 'sulfinamide glutathione'.
- [ ] remove EC:1.1.1.284 xref from GO:0080007 and GO:0160163
- [ ] add  RHEA:78371 and  MetaCyc:RXN-17884 xrefs to GO:0080007
- [ ] make EC:1.1.1.284 an exact match xref on S-(hydroxymethyl)glutathione dehydrogenase  [NAD(P)H] activity (GO:0051903)

I can take care of these last bits myself, so I'll reassign the ticket to me and take care of them.  Thanks!
