### ISSUE TITLE
uniporter activity (GO:0015292)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27340]
Chatting with @hattrill about this term:

```id: GO:0015292
name: uniporter activity
def: "Catalysis of the transport of a single molecular species across a membrane; transport is independent of the movement of any other molecular species." [GOC:mtg_transport, ISBN:0815340729, PMID:10839820]
synonym: "facilitated diffusion carrier" EXACT []
synonym: "single-species transporter activity" EXACT []
synonym: "uniport" RELATED []
is_a: GO:0015291 ! secondary active transmembrane transporter activity
```

'uniporter activity' does not fit the definition of "GO:0015291 ! secondary active transmembrane transporter activity" , which is:
def: "Enables the transfer of a solute from one side of a membrane to the other, up its concentration gradient. The transporter binds the solute and undergoes a series of conformational changes. Transport works equally well in either direction and is driven by a chemiosmotic source of energy, not direct ATP coupling. Secondary active transporters include symporters and antiporters." [GOC:mtg_transport, ISBN:0198506732, ISBN:0815340729, PMID:10839820]

That is, uniporter activity is not driven "by a chemiosmotic source of energy,". since it is "independent of the movement of any other molecular species."

Supporting this, here is the wikipedia definition of uniporter (https://en.wikipedia.org/wiki/Uniporter):
Uniporters, also known as solute carriers or facilitated transporters, are a type of [membrane transport protein](https://en.wikipedia.org/wiki/Membrane_transport_protein) that passively transports solutes (small molecules, ions, or other substances) across a cell membrane.[[1]](https://en.wikipedia.org/wiki/Uniporter#cite_note-Zhang_XC-1) It uses [facilitated diffusion](https://en.wikipedia.org/wiki/Facilitated_diffusion) for the movement of solutes down their concentration gradient from an area of high concentration to an area of low concentration.

- [ ] So, 'GO:0015292 uniporter activity' parentage should be changed to this term:
```id: GO:0022803
name: passive transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0022814
def: "Enables the transfer of a single solute from one side of a membrane to the other by a mechanism involving conformational change, either by facilitated diffusion or in a membrane potential dependent process if the solute is charged." [GOC:mtg_transport, ISBN:0815340729]
synonym: "facilitated diffusion" RELATED []
synonym: "porters" BROAD []
synonym: "uniporter activity z" NARROW []
xref: Wikipedia:Facilitated_diffusion
is_a: GO:0022857 ! transmembrane transporter activity
```
---
However, making this change creates a problem for this child term of 'uniporter activity':
```
id: GO:0022810
name: membrane potential driven uniporter activity
def: "Enables the active transport of a solute across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged." [GOC:mtg_transport, ISBN:0815340729]
synonym: "porter" BROAD []
is_a: GO:0015292 ! uniporter activity
```

Definition here says this is a form of "active transport derived from membrane potential", so:
- [ ] change the parent on "GO:0022810 membrane potential driven uniporter activity" to "GO:0015291 ! secondary active transmembrane transporter activity"

Then also:
- [ ]  for the def "of GO:0022803 passive transmembrane transporter activity", change ", either by facilitated diffusion or in a membrane potential dependent process if the solute is charged." to "by facilitated diffusion.."

**Comment by sjm41** [comment]
This child term of 'uniporter activity' has no GO annotations or xrefs:
GO:0015544 phenyl propionate uniporter activity

I think it _might_ be the same as this RHEA:
https://www.rhea-db.org/rhea/29747 (maps to 3-phenylpropionate CHEBI:51057)
Which also has no annotations in UniProt.

So could delete this one?

**Comment by pgaudet** [comment]
Looks like GO:0015544 phenyl propionate uniporter activity could be used to annotate 
https://www.uniprot.org/uniprotkb/Q47142/entry
https://ecocyc.org/gene?orgid=ECOLI&id=G7330
@amandamackie what do you think ?

**Comment by amandamackie** [comment]
That entry is annotated as a putative 3-phenylpropionate transporter in EcoCyc. It looks like the transport mechanism has not been characterized so I would not assign a uniporter GO term.

**Comment by lbreuza** [comment]
Hi,

I think GO:0015267  channel activity should not be a child of GO:0022803  passive transmembrane transporter activity which states  " by a mechanism involving conformational change" which is exactly what makes the difference between channels and solute careers"
According to PMID: 10839820: 

Two primary modes of facilitated transport
have been recognized in biological systems: channel type and
carrier type (Fig. 1). In channel-type facilitated diffusion, the
solute passes in a diffusion-limiting process from one side of
the membrane to the other via a channel or pore that is lined
by appropriately hydrophilic (for hydrophilic substrates), hydrophobic (for hydrophobic substrates), or amphipathic (for
amphipathic substrates) amino acyl residue moieties of the
constituent protein(s).

**Comment by lbreuza** [comment]
> That is, uniporter activity is not driven "by a chemiosmotic source of energy,". since it is "independent of the movement of any other molecular species."

I do not agree as it is its own gradient that has been generated by a source of energy.

**Comment by sjm41** [comment]
> I think GO:0015267 channel activity should not be a child of GO:0022803 passive transmembrane transporter activity which states " by a mechanism involving conformational change" 
Or should "by a mechanism involving conformational change" be removed from the definition of 'passive transmembrane transporter activity' ?

**Comment by hattrill** [comment]
> Or should "by a mechanism involving conformational change" be removed from the definition of 'passive transmembrane transporter activity' ?

Yes, as there are pores/channels that are just open all the time.

**Comment by lbreuza** [comment]
> > I think GO:0015267 channel activity should not be a child of GO:0022803 passive transmembrane transporter activity which states " by a mechanism involving conformational change"
> 
> Or should "by a mechanism involving conformational change" be removed from the definition of 'passive transmembrane transporter activity' ?

Yes Steven, I was also thinking of something like this.

**Comment by sjm41** [comment]
>That is, uniporter activity is not driven "by a chemiosmotic source of energy,". since it is "independent of the movement of any other molecular species."
I do not agree as it is its own gradient that has been generated by a source of energy.

Hi @lbreuza
But do you agree that the GO 'uniporter activity' term belongs under 'passive transmembrane transporter activity' rather than "active transmembrane transporter activity" -> "secondary active transmembrane transporter activity"?
Or are you saying the uniporter activity is a form of active transport?

**Comment by lbreuza** [comment]
I usually refer to TCDB and the paper we have as evidence for the GO terms (PMID: 10839820), and what disturbs me is that they consider uniporters like symporters and antiporters, I assumed (but i might be wrong) using a gradient (their own for uniporters) created by an upstream mechanism. I would only consider channels for a passive transmembrane transporter activity.

**Comment by hattrill** [comment]
@lbreuza probably results from uniporter being used inconsistenly. 

Faciltated diffusion is passive, but there has to be a gradient for it to take place, channel or uniporter. Otherwise, the ion channels involved in nerve conduction would be secondary.

I think that classification of transporters into passive and secondary active is not very useful. TCDB, doesn't really try to capture this in it's current stucture. It uses these groupings:
1: Channels/Pores
2: Electrochemical Potential-driven Transporters
So separate out channel and carriers and they cheat a bit on the definition to make it fit with secondary:
"Electrochemical Potential-driven Transporters" Secondary carrier-type facilitators. Transport systems are included in this category if they utilize a carrier-mediated process to catalyze uniport (a single species is transported by facilitated diffusion in a process not coupled to the utilization of a primary source of energy), antiport (two or more species are transported in opposite directions in a tightly coupled process not directly linked to a form of energy other than chemiosmotic energy) and/or symport (two or more species are transported together in the same direction in a tightly coupled process not directly linked to a form of energy other than chemiosmotic energy)

but in many other places:
e.g. https://neurotext.library.stonybrook.edu/C1/C1_7/C1_7.html
transport down a gradient of one solute is classed as passive.

So, perhaps, like TCDB, we should ditch the primary and secondary classifications and have:
-Channel activity
-Carrier activity
as seems that really we want to capture the mechanism here.

**Comment by sjm41** [comment]
Thanks @lbreuza for pointing to the TCDB and PMID: 10839820 - definitely need to consider those sources.
As @hattrill said, the classification used in current TCDB seems to have moved on since PMID: 10839820 was published (in 2000).
Though I note that they still have 'primary active transporters' as a main and separate axis.
So, are we proposing that the GO hierarchy would change from this:
```
transmembrane transporter activity
    |__active transmembrane transporter activity
        |__primary active transmembrane transporter activity
        |__secondary active transmembrane transporter activity 
            |__antiporter activity
            |__symporter activity
            |__uniporter activity
    |__passive transmembrane transporter activity
        |__channel activity
```

to this:

```
transmembrane transporter activity
    |__carrier activity 
        |__primary active transmembrane transporter activity
        |__antiporter activity
        |__symporter activity
        |__uniporter activity
    |__channel activity
```

Or were you suggesting to ditch the 'primary active transmembrane transporter' grouping in your previous comment @hattrill ?

**Comment by hattrill** [comment]
Sorry, I meant passive and secondary rather than @sjm41 - I will correct that. Definitely keep primary active transmembrane transporter - it is the only one that can be well-defined!

I think that primary active transmembrane transporters should not be under carrier though, but I'd need to double check that.

**Comment by hattrill** [comment]
Think this is right:

transmembrane transporter activity
    |__primary active transmembrane transporter activity
    |__carrier activity 
        |__antiporter activity
        |__symporter activity
        |__uniporter activity
    |__channel activity

Might have to call carriers something like: "transmembrane transporter carrier activity" to distinguish it from other carrier activities in GO,

**Comment by lbreuza** [comment]
> Think this is right:
> 
> transmembrane transporter activity |__primary active transmembrane transporter activity |__carrier activity |__antiporter activity |__symporter activity |__uniporter activity |__channel activity
> 
> Might have to call carriers something like: "transmembrane transporter carrier activity" to distinguish it from other carrier activities in GO,

Shouldn't  carrier activity be a parent of  
|__antiporter activity
|__symporter activity
|__uniporter activity?

**Comment by sjm41** [comment]
I think Helen's formatting/nesting got lost - I've just reformatted it (but let me know Helen if I got it wrong!)

**Comment by aimol** [comment]
> Think this is right:
> 
> ```
> transmembrane transporter activity
>     |__primary active transmembrane transporter activity
>     |__carrier activity 
>         |__antiporter activity
>         |__symporter activity
>         |__uniporter activity
>     |__channel activity
> ```
> 
> Might have to call carriers something like: "transmembrane transporter carrier activity" to distinguish it from other carrier activities in GO,

Yes, I agree that it would be wise to use "transmembrane carrier activity" to distinguish from other carrier activities.

**Comment by lbreuza** [comment]
@sjm41 and @hattrill are you going to update the ontology accordingly?
Just wanted to follow-up before it drops from my radar.

**Comment by hattrill** [comment]
@lbreuza
Yesterday, I started to make some tickets to tidy up some of the problematic child terms of 'active transmembrane transporter activity':
e.g. https://github.com/geneontology/go-ontology/issues/27488
I will make new ticket to change this branch after I've checked the child terms.

**Comment by lbreuza** [comment]
Great! Thanks.

**Comment by hattrill** [comment]
Also, we will need a parent term for 'group translocator activity' which is a TC 4 set. https://tcdb.org/search/result.php?tc=4
TCDB description:
"Group translocation involves a combined chemical and vectorial reaction where the transported substrate is modified during the transport process.  This can be in a tightly coupled process where transport can not occur at an appreciable rate without substrate modification, or in a more loosely coupled process where transport can occur without  derivatization, but the normal process involves coupling.  Such processes can involve sugar phosphorylation using phosphoenolpyruvate (PEP) mediated by the phosphotransferase system (PTS; 4.A), nucleoside phosphorylation using ATP as the phosphoryl donor (PnuC; 4.B), or carboxylic acid thioesterification using Coenzyme A as the derivatizing agent (FAT; 4.C)."

Parent for terms:
GO:0008982 protein-N(PI)-phosphohistidine-sugar phosphotransferase activity
GO:0090563 protein-phosphocysteine-sugar phosphotransferase activity
