### ISSUE TITLE
fatty acid alpha-hydroxylase activity (GO:0080132)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27541]
I think "GO:0080132 fatty acid alpha-hydroxylase activity" equates to EC:1.14.18.6 (RHEA:46520), but I would appreciate a second opinion.  If this is true, then the tasks are:
- [ ] add xrefs to GO:0080132 (EC:1.14.18.6, RHEA:46520, MetaCyc:RXN3O-4042)
- [ ] add "4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase" from EC as synonym
- [ ] Change GO:0080132 def to match EC/RHEA
- [ ] Use better reference than PMID:19054355 in the def - see below
- [ ] Change parent from "oxidoreductase activity" to "GO:0016716 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen"

Here's what I see:

id: GO:0080132
name: fatty acid alpha-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the conversion of a fatty acid to an alpha-hydroxylated fatty acid. A hydroxyl group is added to the second carbon, counted from the carboxyl end, of a fatty acid chain." [PMID:19054355]
synonym: "fatty acid 2-hydroxylase" EXACT []
is_a: GO:0016491 ! oxidoreductase activity
created_by: dhl
creation_date: 2009-05-06T04:43:36Z

The reference (PMID:19054355) used here only describes this activity tangentially, saying "Mitchell and Martin (1997) reported previously that in Arabidopsis, At2g34770 (AtFAH1) was homologous to ScFAH1, and that it had fatty acid 2-hydroxylation activity in yeast."

The primary Mitchell and Martin (1997) reference is PMID: 9353282, and it was used as the source for this EC and corresponding RHEA:

EC:1.14.18.6 (https://www.enzyme-database.org/query.php?ec=1.14.18.6):
Name: 4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase
Comments: The enzyme, characterized from yeast and mammals, catalyzes the hydroxylation of carbon 2 of long- or very-long-chain fatty acids attached to (4R)-4-hydroxysphinganine during de novo ceramide synthesis.
The enzymes from yeast and from mammals contain an N-terminal cytochrome b5 domain that acts as the direct electron donor to the desaturase active site. 

RHEA:46520:
an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O 

GO:0080132 has 13 EXP annotations, including:
Yeast SCS7 (including from Mitchell and Martin (1997) = PMID: 9353282)
Rat Fa2h
Mouse Fa2h
Human FA2H
Fly Fa2h

RHEA:46520 has one annotation in UniProt, to Yeast SCS7.
EC:1.14.18.6 has 4 annotations in UniProt, including yeast SCS7.

Other sources for EC:1.14.18.6 / RHEA:46520 include papers referenced on the human FA2H UniProt page:
Alderson, N.L., Rembiesa, B.M., Walla, M.D., Bielawska, A., Bielawski, J. and Hama, H. The human FA2H gene encodes a fatty acid 2-hydroxylase. J. Biol. Chem. 279 (2004) 48562–48568. [DOI] [PMID: 15337768]
Guo, L., Zhang, X., Zhou, D., Okunade, A.L. and Su, X. Stereospecificity of fatty acid 2-hydroxylase and differential functions of 2-hydroxy fatty acid enantiomers. J. Lipid Res. 53 (2012) 1327–1335. [DOI] [PMID: 22517924]

**Comment by deustp01** [comment]
> GO:0080132 has 13 EXP annotations

And one Reactome mapping, [R-HSA-5693761 "FA2H hydroxylates 1,2-saturated fatty ](https://reactome.org/PathwayBrowser/#/R-HSA-5693761)acids", which looks like it should have a cross-reference to RHEA:38855 "a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O" but does not, for reasons I need to check.

**Comment by sjm41** [comment]
Thanks @deustp01.
In that case, it seems the "GO:0080132 fatty acid alpha-hydroxylase activity" term may have been used more as a 'grouping term' to annotate different, albeit related, activities?
In that case, the proposal here would be to create some more specific child terms, including the two RHEAs referred to above, i.e:

RHEA:46520:
an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O

and

RHEA:38855:
a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O

**Comment by deustp01** [comment]
> it seems the "GO:0080132 fatty acid alpha-hydroxylase activity" term may have been used more as a 'grouping term'

It definitely has,by us a shown here. But also as intended by RHEA, whose entry lists two more specific forms of the reaction and two more general forms. This leads to an important tangent issue, the role of grouping terms in annotation of broad-specificity enzymes. My recollection of old biochemistry literature is that no description of the catalytic properties of a newly characterized enzyme or transporter is that most such papers featured tables to show the range of inputs that could be acted on at physiologically interesting rates. A grouping term is really useful for capturing that range in a compact annotation. @ukemi ?

**Comment by pgaudet** [comment]
It looks like the most general reaction in RHEA is https://www.rhea-db.org/rhea/39983 ?

**Comment by sjm41** [comment]
> It looks like the most general reaction in RHEA is https://www.rhea-db.org/rhea/39983 ?

Yes, RHEA has two very similar 'general' terms for hydroxylation of 'free' fatty acids, arranged like this:

```
RHEA:39983 (a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = a 2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O)
   |_RHEA:38855 (a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O)
```

Note that the other RHEA mentioned at the top of this ticket (RHEA:46520 = EC:1.14.18.6) is for hydroxylation of fatty acids "attached to (4R)-4-hydroxysphinganine during de novo ceramide synthesis".

From its definitions and usage, it seems that the current fatty acid alpha-hydroxylase activity (GO:0080132) term encompasses hydroxylation of both 'free' and 'attached' fatty acids.  That's fine, and just means we could make some new GO terms for more specific children terms corresponding to:
- RHEA:39983 or RHEA:38855 (for 'free' fatty acids)
- RHEA:46520 = EC:1.14.18.6 (for '(4R)-4-hydroxysphinganine-attached' fatty acids)

In this view, the existing term GO:0102771 (EC:1.14.18.7 = RHEA:46512) would also become a child of GO:0080132 - that's for hydroxylation of fatty acids attached to sphinganine:
"an N-(1,2-saturated acyl)sphinganine + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = an N-[(2'R)-hydroxyacyl]sphinganine + 2 Fe(III)-[cytochrome b5] + H2O."

**Comment by deustp01** [comment]
> Does Reactome have evidence that free fatty acids are 2-hydroxylated in humans?

No, we don't. And in fact the reaction I cited above is the first step in the Reactome pathway "Sphingolipid de novo biosynthesis" ([R-HSA-1660661](https://reactome.org/PathwayBrowser/#/R-HSA-1660661)), and while the output hydroxylated fatty acids are not consumed in any of the other reactions annotated in that pathway, that looks like a gap in our annotation, not evidence that 2-hydroxylated free fatty acids have a role elsewhere in metabolism.

**Comment by sjm41** [comment]
OK, well in that case I think the proposal now is either:

1. Keep GO:0080132 as a grouping term and make a new child term for EC:1.14.18.6, like this:

```
oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen (GO:0016716) = EC:1.14.18.- 
    |_fatty acid alpha-hydroxylase activity (GO:0080132)
        |_4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase (NTR) = RHEA:46520/EC:1.14.18.6
        |_dihydroceramide fatty acyl 2-hydroxylase activity (GO:0102771) = RHEA:46512/EC:1.14.18.7
```
or:

2. Abandon the grouping term and instead equate GO:0080132 to RHEA:46520/EC:1.14.18.6, like this:
```
oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen (GO:0016716) = EC:1.14.18.- 
    |_4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase (GO:0080132) = RHEA:46520/EC:1.14.18.6
    |_dihydroceramide fatty acyl 2-hydroxylase activity (GO:0102771) = RHEA:46512/EC:1.14.18.7
```

I think I prefer version #1.

(In either scenario, we move GO:0080132 to be a child of GO:0016716 = EC:1.14.18.- )

**Comment by pgaudet** [comment]
Hi @sjm41 

Looking at these 2 ECs: 
**-EC:1.14.18.6**  states that this enzyme is characterized from yeast and mammals. Looking at the annotations, we only have yeast SCS7 associated (https://www.uniprot.org/uniprotkb/Q03529/entry); and that is associated with both EC:1.14.18.6 and EC:1.14.18.7
- The citations in ExplorEnz for [EC:1.14.18.6](https://www.enzyme-database.org/query.php?ec=1.14.18.6 )mention FAH2 as the human/mammalian enzyme with this activity; however in UniProt [FA2H](https://www.uniprot.org/uniprotkb/Q7L5A8/entry) is associated with a number of RHEAs, but neither RHEA:46520 nor RHEA:46512 (and no EC). 


Maybe a third possibility is to obsolete GO:0102771  dihydroceramide fatty acyl 2-hydroxylase activity and put both EC as NARRROW matches on fatty acid alpha-hydroxylase activity (GO:0080132) (no annotations; it's has a single IEA coming from the REAH mapping) 

Otherwise, we will need to create all the children RHEA? 
https://www.rhea-db.org/rhea/39983

- [RHEA:39823](https://www.rhea-db.org/rhea/39823)
- eicosanoate + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = 2-hydroxyeicosanoate + 2 Fe(III)-[cytochrome b5] + H2O
- [RHEA:39819](https://www.rhea-db.org/rhea/39819)
- docosanoate + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = 2-hydroxydocosanoate + 2 Fe(III)-[cytochrome b5] + H2O
- [RHEA:39815](https://www.rhea-db.org/rhea/39815)
- 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 + octadecanoate = (R)-2-hydroxyoctadecanoate + 2 Fe(III)-[cytochrome b5] + H2O
- [RHEA:38855](https://www.rhea-db.org/rhea/38855)
- a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O
- - [RHEA:38559](https://www.rhea-db.org/rhea/38559)
2 Fe(II)-[cytochrome b5] + 2 H+ + O2 + tetracosanoate = (R)-2-hydroxytetracosanoate + 2 Fe(III)-[cytochrome b5] + H2O
- - [RHEA:38551](https://www.rhea-db.org/rhea/38551)
2 Fe(II)-[cytochrome b5] + 2 H+ + hexadecanoate + O2 = (R)-2-hydroxyhexadecanoate + 2 Fe(III)-[cytochrome b5] + H2O

What do you think ?

**Comment by sjm41** [comment]
I've carefully reviewed all the comments above and delved deeper into the annotations and literature for the GO/EC/RHEA terms involved here.
As a reminder, this concerns annotating the described functions of the conserved FA2H/SCS7 protein, which is acknowledged to catalyse the 2-hydroxylation of free fatty acids and of fatty acyl chains within sphingolipids/ceramides (see PMID:36902339 for recent review).

I think the following is the safest and most accurate course of action:

---

**GO:0080132 fatty acid alpha-hydroxylase activity**
- keep this term as a generic, grouping term for the more specific types of activity (see below), meaning that current annotations are unaffected.
- but change name to 'fatty acid 2-hydroxylase activity' to reflect common usage
- and replace PMID:19054355 with PMID:36902339 as def xref, and indicate that the substrate may be free fatty acids or fatty acyl chains within sphingolipids/ceramides.
- also, change parent to "GO:0016716 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen"


---

**NTR for a child term specifically acting on free fatty acids, corresponding to RHEA:38855**

name: free fatty acid 2-hydroxylase activity
definition: Catalysis of the reaction: a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O. Note that the substrate is a free fatty acid, not a fatty acyl chain within a sphingolipids/ceramide. [RHEA:38855]
xref: RHEA:38855 exactMatch
is_a: GO:0016716 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen

RHEA:38855 is currently annotated to three proteins FA2H_HUMAN, FA2H_MOUSE, FA2H_RAT, and RHEA:38855 matches the Reactome mapping [R-HSA-5693761 "FA2H hydroxylates 1,2-saturated fatty ](https://reactome.org/PathwayBrowser/#/R-HSA-5693761)acids", which says "Fatty acid 2-hydroxylase (FA2H), an ER membrane-associated enzyme, catalyzes the cytochrome b5-dependent hydroxylation of free fatty acids on the saturated C2 position. 2-Hydroxylation of free fatty acids occurs before de novo ceramide synthesis." - Reactome may want to re-annotate that reaction to this more specific term.

---

**GO:0102771 dihydroceramide fatty acyl 2-hydroxylase activity**
- keep this term, but make it a child of GO:0080132
- this already has xrefs to EC:1.14.18.7 and RHEA:46512
- it has no EXP annotations, but the EC/RHEA is annotated to 3 proteins (FAH1_ARATH, FAH2_ARATH, SCS7_YEAST), and they sh/could acquire EXP annotations from the same sources used for the EC/RHEA annotations (and thus become available for ISS/PAINT annotations)

---

**NTR for EC 1.14.18.6 (= RHEA:46520 & RHEA:64532):**

name: 4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase activity
definition: Catalysis of the reaction: an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O
&
an N-(1,2 saturated very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base + 2 Fe(II)-[cytochrome b5] + 2 H(+) + O2 = an N-(2R-hydroxy-very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base + 2 Fe(III)-[cytochrome b5] + H2O
xref: EC:1.14.18.6 exactMatch
xref: RHEA:46520 narrowMatch
xref: RHEA:64532 narrowMatch
is_a: GO:0016716 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen

- this EC/RHEA is currently only annotated to a single protein: SCS7_YEAST, but it sh/could acquire an EXP annotation from the same sources used for the EC/RHEA annotations (and thus become available for ISS/PAINT annotations)

---

We end up with a small hierarchy like this:

```
fatty acid 2-hydroxylase activity (GO:0080132)
    |_free fatty acid 2-hydroxylase activity (NTR = RHEA:38855)
    |_dihydroceramide fatty acyl 2-hydroxylase activity (GO:0102771 = EC:1.14.18.7 = RHEA:46512)
    |_4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase activity (NTR = EC 1.14.18.6 = RHEA:46520/RHEA:64532)

```

**Comment by sjm41** [comment]
New terms:

[Term]
id: GO:0120520
name: free fatty acid 2-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 1,2-saturated fatty acid + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = a (R)-2-hydroxy fatty acid + 2 Fe(III)-[cytochrome b5] + H2O. Note that the substrate is a free fatty acid, not a fatty acyl chain within a sphingolipid." [GOC:sjm, RHEA:38855]
xref: RHEA:38855 {source="skos:exactMatch"}
is_a: GO:0080132 ! fatty acid 2-hydroxylase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27541" xsd:anyURI
created_by: sjm
creation_date: 2024-07-12T08:40:48Z

[Term]
id: GO:0120521
name: 4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O." [RHEA:46520]
xref: EC:1.14.18.6 {source="skos:broadMatch"}
xref: MetaCyc:RXN3O-4042 {source="skos:exactMatch"}
xref: RHEA:46520 {source="skos:exactMatch"}
is_a: GO:0080132 ! fatty acid 2-hydroxylase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27541" xsd:anyURI
created_by: sjm
creation_date: 2024-07-12T08:47:01Z

**Comment by sjm41** [comment]
Adding EC synonym to GO:0102771 1.14.18.7: plant sphingolipid fatty acid 2-hydroxylase

**Comment by sjm41** [comment]
Upon review, EC:1.14.18.6 should be exactMatch (not broadMatch) on this term:

id: GO:0120521
name: 4-hydroxysphinganine ceramide fatty acyl 2-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + 2 H+ + O2 = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O." [RHEA:46520]
xref: EC:1.14.18.6 {source="skos:broadMatch"}
xref: MetaCyc:RXN3O-4042 {source="skos:exactMatch"}
xref: RHEA:46520 {source="skos:exactMatch"}
xref: RHEA:64532 {source="skos:narrowMatch"}
is_a: GO:0080132 ! fatty acid 2-hydroxylase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27541" xsd:anyURI


The EC entry says:

Reaction catalysed:
1. an N-(1,2 saturated acyl)-(4R)-hydroxysphinganine + 2 Fe(II)-[cytochrome b5] + O2 + 2 H(+) = an N-(2R-hydroxyacyl)-4R-hydroxysphinganine + 2 Fe(III)-[cytochrome b5] + H2O
2. an N-(1,2 saturated very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base + 2 Fe(II)-[cytochrome b5] + O2 + 2 H(+) = an N-(2R-hydroxy-very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base + 2 Fe(III)-[cytochrome b5] + H2O

Comments:
The enzyme, characterized from yeast and mammals, catalyzes the hydroxylation of carbon 2 of long- or very-long-chain fatty acids attached to (4R)-4-hydroxysphinganine during de novo ceramide synthesis.


Reaction 1 is [RHEA:46520](https://www.rhea-db.org/rhea/46520), and reaction 2 is [RHEA:64532](https://www.rhea-db.org/rhea/64532).
And RHEA:46520 is the parent (more general reaction) to RHEA:64532.
