### ISSUE TITLE
GO:0061611 mannose to fructose-6-phosphate metabolic process

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27638]
Looking at these 2 terms:

id: GO:0019309
name: mannose catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of mannose, the aldohexose manno-hexose, the C-2 epimer of glucose." [GOC:ai]
synonym: "mannose breakdown" EXACT []
synonym: "mannose catabolism" EXACT []
synonym: "mannose degradation" EXACT []
xref: MetaCyc:MANNCAT-PWY
xref: MetaCyc:PWY3O-1743
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:37684 ! mannose
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI

id: GO:0061611
name: mannose to fructose-6-phosphate metabolic process
namespace: biological_process
def: "The chemical reactions and pathways in which mannose, the aldohexose manno-hexose, is converted to fructose-6-phosphate." [GOC:dph, ISBN:0201090910, ISBN:0879010479]
synonym: "mannose metabolism to fructose-6-phosphate" EXACT [GOC:dph]
is_a: GO:0006013 ! mannose metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: ends_with GO:0004476 ! mannose-6-phosphate isomerase activity
intersection_of: has_primary_input CHEBI:37684 ! mannose
intersection_of: has_primary_output CHEBI:57579 ! D-fructose 6-phosphate(2-)
intersection_of: starts_with GO:0019158 ! mannokinase activity
created_by: dph
creation_date: 2014-04-03T13:38:50Z

The MetaCyc xrefs currently on GO:0019309 are:
D-mannose degradation I (MANNCAT-PWY)
D-mannose -> fructose-6-phosphate, including transport into cell (via mannokinase & mannose-6-phosphate isomerase)
(archaea and bacteria)

D-mannose degradation II (PWY3O-1743)
D-mannose -> fructose-6-phosphate (via mannokinase & mannose-6-phosphate isomerase)
(eukaryotes, archaea, bacteria)

Given the above, I'd suggest:

- [x] Rename GO:0061611 to 'mannose to fructose-6-phosphate catabolic process'
- [x] Change the LD to make GO:0061611 a child of 'GO:0019309 mannose catabolic process'
- [x] Move the MetaCyc xrefs to GO:0061611.

What do you think @ukemi  and @deustp01 ?

Note that the following term  already classifies as a child of GO:0019309 mannose catabolic process:
id: GO:0061619
name: glycolytic process from mannose through fructose-6-phosphate
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of mannose into pyruvate, occurring through a fructose-6-phosphate intermediate, with the concomitant production of ATP and NADH." [GOC:dph, ISBN:0201090910, ISBN:0879010479]
intersection_of: GO:0061615 ! glycolytic process through fructose-6-phosphate
intersection_of: has_primary_input CHEBI:37684 ! mannose
intersection_of: starts_with GO:0061611 ! mannose to fructose-6-phosphate metabolic process
created_by: dph
creation_date: 2014-04-14T09:13:13Z

@rozaru

**Comment by sjm41** [comment]
Decision on call was that proposals above are reasonable and should proceed.
