### ISSUE TITLE
GO:0106364 and GO:0008681 parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27952]
[Term]
id: GO:0106364
name: 4-hydroxy-3-all-trans-hexaprenylbenzoate oxygenase activity
namespace: molecular_function
def: "4-hydroxy-3-all-trans-hexaprenylbenzoate + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = 3,4-dihydroxy-5-all-trans-hexaprenylbenzoate + H2O + 2 oxidized [2Fe-2S]-[ferredoxin]." [PMID:21944752, RHEA:20361]
xref: RHEA:20361
is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
created_by: hjd
creation_date: 2021-02-09T15:52:26Z

=> current parent here (GO:0016712) maps to EC:1.14.14.-
=> But RHEA:20361 maps the reaction to MetaCyc:RXN3O-58, who have given it an internal EC of '1.14.15.M7', suggesting the parent should be GO:0016713 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced iron-sulfur protein as one donor, and incorporation of one atom of oxygen (EC:1.14.15.-), which looks correct

- [x] Change parent to GO:0016713
- [x] Add xref MetaCyc:RXN3O-58

[Term]
id: GO:0008681
name: 2-octaprenyl-6-methoxyphenol hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-octaprenyl-6-methoxyphenol + O2 + 4 H+ = 2-octaprenyl-6-methoxy-1,4-benzoquinol + H2O." [PMID:27822549, PMID:4572721, RHEA:29407]
xref: MetaCyc:2-OCTAPRENYL-6-METHOXYPHENOL-HYDROX-RXN
xref: RHEA:29407
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

=> current parent here (GO:0016705) maps to EC:1.14.-.-
=> But MetaCyc:2-OCTAPRENYL-6-METHOXYPHENOL-HYDROX-RXN equates it to an internal EC of 1.14.13.M56, suggesting the parent should be GO:0016709 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen (EC:1.14.13.-)
=> Looking at MetaCyc and RHEA:29407, I see NADPH is omitted from the reaction. It should be:
2-methoxy-6-(all-trans-octaprenyl)phenol + H+ + NADPH + O2 = 2-methoxy-6-all-trans-octaprenyl-1,4-benzoquinol + H2O + NADP+

- [x] Change parent to GO:0016709
- [x] Change def to match RHEA
