### ISSUE TITLE
fatty aldehyde dehydrogenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28142]
id: GO:0102673
name: fatty aldehyde dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(1-) + H2O + a fatty aldehyde = NADH(2-) + 2 H+ + a fatty acid." [EC:1.2.1.3, GOC:pz]
xref: MetaCyc:RXN-4142
is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor

This term corresponds to RHEA:49832:
a fatty aldehyde + H2O + NAD(+) = a fatty acid + 2 H(+) + NADH

That term is part of a small hierarchy in RHEA that includes the following:
```
RHEA:16185 an aldehyde + H2O + NAD+ = a carboxylate + 2 H+ + NADH (= GO:0004029)
    |_RHEA:49832 a fatty aldehyde + H2O + NAD+ = a fatty acid + 2 H+ + NADH (= GO:0102673)
	|_ RHEA:69763 a medium-chain fatty aldehyde + H2O + NAD+ = a medium chain fatty acid + 2 H+ + NADH (GO:0052814)
	|_ RHEA:10652 a long-chain fatty aldehyde + H2O + NAD+ = a long-chain fatty acid + 2 H+ + NADH (GO:0050061)

```

- [x] add RHEA:49832 to GO:0102673 as term and def xref
- [x] change parent of GO:0102673 to GO:0004029
- [x] change parents of GO:0052814 and GO:0050061 to GO:0102673
- [x] change names of GO:0052814 and GO:0050061 to include 'fatty'
