### ISSUE TITLE
lipase activity edits

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28339]
Our lipase activity term and immediate child terms look like this:
```
hydrolase activity, acting on ester bonds
    |__lipase activity
           |__acylglycerol lipase activity
           |__galactolipase activity
           |__phospholipase activity
           |__sterol esterase activity
           |__triglyceride lipase activity
               |__lipoprotein lipase activity
```

After chatting with Lucila Aimo at RHEA and @pgaudet, there are several corrections to make:

id: GO:0016298
name: lipase activity
def: "Catalysis of the hydrolysis of a lipid or phospholipid." [GOC:mah, ISBN:0198506732]
is_a: GO:0016788 ! hydrolase activity, acting on ester bonds

- [x] All lipases are carboxylic ester hydrolase, so change parent here to 'GO:0052689 ! carboxylic ester hydrolase activity'
- [x] No need to specify 'phospholipid' (but not other lipid types) in the definition, so remove that bit.

---

id: GO:0047372
name: acylglycerol lipase activity
def: "Catalysis of the reaction: H2O + acylglycerol = a fatty acid + glycerol." [EC:3.1.1.23, MetaCyc:3.1.1.23-RXN]
xref: EC:3.1.1.23
xref: MetaCyc:3.1.1.23-RXN
xref: RHEA:34019
is_a: GO:0016298 ! lipase activity
is_a: GO:0052689 ! carboxylic ester hydrolase activity

- [x] Following point above, remove redundant parent 'GO:0052689 ! carboxylic ester hydrolase activity'
- [x] This is specifically for monoacylglycerol lipase (which is the alternative EC name), so change GO name to 'monoacylglycerol lipase activity'
- [x] RHEA xref here should be RHEA:15245
- [x] Update def to match RHEA:15245 "a monoacylglycerol + H2O = a fatty acid + glycerol + H+"
- [x] Change MetaCyc xref to MetaCyc:RXN-19280

---

id: GO:0004806
name: triglyceride lipase activity
def: "Catalysis of the reaction: triacylglycerol + H2O = diacylglycerol + a carboxylate." [EC:3.1.1.3]
xref: EC:3.1.1.3
xref: MetaCyc:TRIACYLGLYCEROL-LIPASE-RXN
xref: RHEA:12044
is_a: GO:0016298 ! lipase activity
is_a: GO:0052689 ! carboxylic ester hydrolase activity

- [x] Following point above, remove redundant parent 'GO:0052689 ! carboxylic ester hydrolase activity'
- [x] Change GO name to 'triacylglycerol lipase activity'
- [x] Update def to match RHEA:12044 "a triacylglycerol + H2O = a diacylglycerol + a fatty acid + H+"
- [x] Change MetaCyc xref to MetaCyc:RXN-19278

---

id: GO:0004465
name: lipoprotein lipase activity
def: "Catalysis of the reaction: triacylglycerol + H2O = diacylglycerol + a carboxylate, where the triacylglycerol is part of a lipoprotein." [EC:3.1.1.34, GOC:bf]
xref: EC:3.1.1.34
is_a: GO:0004806 ! triglyceride lipase activity

EC:3.1.1.34 says:
Hydrolyzes triacylglycerols and diacylglycerol in chylomicrons and low-density lipoprotein particles (VLDL).
Human protein purified from post-heparin plasma (LPL) shows no activity against triglyceride in the absence of added lipoprotein.
The principal reaction sequence of that enzyme is triglyceride -> 1,2-diglyceride -> 2-monoglyceride.
The hepatic enzyme (LIPC) also hydrolyzes triglycerides and phospholipids present in circulating plasma lipoproteins.

- [x] Append some text to the def to indicate these additional activities.

---

- [x] Make new term for 'diacylglycerol lipase activity':
name: diacylglycerol lipase activity
def: "Catalysis of the reaction: a diacylglycerol + H2O = a fatty acid + a monoacylglycerol + H+ [RHEA:32731]
xref: RHEA:32731
xref: MetaCyc:RXN-19279
is_a: GO:0016298 ! lipase activity

---

id: GO:0033878
name: hormone-sensitive lipase activity
def: "Catalysis of the reactions: diacylglycerol + H2O = monoacylglycerol + a carboxylate; triacylglycerol + H2O = diacylglycerol + a carboxylate; and monoacylglycerol + H2O = glycerol + a carboxylate." [EC:3.1.1.79]
xref: EC:3.1.1.79
xref: MetaCyc:TRIACYLGLYCEROL-LIPASE-RXN
is_a: GO:0052689 ! carboxylic ester hydrolase activity

This is really a gene product that can catalyse hydrolysis of monoacylglycerols, diacylglycerols, and triacylglycerol - ie. three of the GO terms listed above.

- [x] obsolete this GO term (5 EXP annotations to human LIPE, rat Lipe, human ABHD2, and Arabidopis AtOBL1)
- [x] add EC:3.1.1.79 as a broadMatch xref on the three mono/di/triacylglycerol lipase activity GO terms above

---

id: GO:0004771
name: sterol esterase activity
def: "Catalysis of the reaction: a steryl ester + H2O = a sterol + a fatty acid." [EC:3.1.1.13]
xref: EC:3.1.1.13
xref: MetaCyc:STEROL-ESTERASE-RXN
xref: RHEA:10100
is_a: GO:0016298 ! lipase activity
is_a: GO:0052689 ! carboxylic ester hydrolase activity

- [x] change name to 'sterol ester esterase activity'
- [x] update def to RHEA:10100 'a sterol ester + H2O = a fatty acid + a sterol + H+'
- [x] Following point above, remove redundant parent 'GO:0052689 ! carboxylic ester hydrolase activity'

---

id: GO:0047714
name: galactolipase activity
def: "Catalysis of the reaction: 1,2-diacyl-3-beta-D-galactosyl-sn-glycerol + 2 H2O = 3-beta-D-galactosyl-sn-glycerol + 2 carboxylates." [EC:3.1.1.26, MetaCyc:GALACTOLIPASE-RXN]
xref: EC:3.1.1.26
xref: MetaCyc:GALACTOLIPASE-RXN
xref: RHEA:13189
is_a: GO:0016298 ! lipase activity
is_a: GO:0052689 ! carboxylic ester hydrolase activity

- [x] update def to RHEA:13189 'a 1,2-diacyl-3-O-(beta-D-galactosyl)-sn-glycerol + 2 H2O = 3-beta-D-galactosyl-sn-glycerol + 2 a fatty acid + 2 H+'
- [x] Following point above, remove redundant parent 'GO:0052689 ! carboxylic ester hydrolase activity'
- [x] Merge GO:0102549 (see below) into GO:0047714 (same EC, specific substrate, no EXP annotations)

id: GO:0102549
name: 1-18:1-2-16:0-monogalactosyldiacylglycerol lipase activity
def: "Catalysis of the reaction: 1-18:1-2-16:0-monogalactosyldiacylglycerol + H2O = sn-1-lyso-2-16:0-monogalactosyldiacylglycerol + oleate + H+." [EC:3.1.1.26, GOC:pz]
xref: EC:3.1.1.26
xref: MetaCyc:RXN-14912
is_a: GO:0052689 ! carboxylic ester hydrolase activity

**Comment by sjm41** [comment]
Also:
- [x] remove redundant parent 'GO:0052689 ! carboxylic ester hydrolase activity' on GO:0008970 phospholipase A1 activity and GO:0004623 phospholipase A2 activity and GO:0004622 lysophospholipase activity

**Comment by sjm41** [comment]
- [ ] Merge the two terms below into the new term 'diacylglycerol lipase activity':

id: GO:0102259 (7 annotations, 1 IDA)
name: 1,2-diacylglycerol acylhydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + a 1,2-diacyl-sn-glycerol = a monoglyceride + a fatty acid." [GOC:pz, PMID:1477884]
xref: MetaCyc:RXN-12434
is_a: GO:0052689 ! carboxylic ester hydrolase activity

id: GO:0102258 (7 annotations, 1 IDA)
name: 1,3-diacylglycerol acylhydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + a 1,3-diglyceride = a monoglyceride + a fatty acid." [GOC:pz, PMID:21477884]
xref: MetaCyc:RXN-12433
is_a: GO:0052689 ! carboxylic ester hydrolase activity

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120516
+name: diacylglycerol lipase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a diacylglycerol + H2O = a fatty acid + a monoacylglycerol + H+." [RHEA:32731]
+xref: EC:3.1.1.79 {source="skos:broadMatch"}
+xref: MetaCyc:RXN-19279 {source="skos:exactMatch"}
+xref: RHEA:32731 {source="skos:exactMatch"}
+is_a: GO:0016298 ! lipase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28339" xsd:anyURI
+created_by: sjm
+creation_date: 2024-06-28T12:36:24Z
+

**Comment by pgaudet** [comment]
@sjm41 Can you give the reasons for merge? I assume GO:0102549 1-18:1-2-16:0-monogalactosyldiacylglycerol lipase activity is a specific substrate of GO:0102549?

**Comment by sjm41** [comment]
Hi @pgaudet
Can I leave the merges and obsoletion mentioned above (ie. the open tasks) to you?

**Comment by pgaudet** [comment]
yes of course

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
- GO:0102549 1-18:1-2-16:0-monogalactosyldiacylglycerol lipase activity & replace by GO:0047714 galactolipase activity 
- GO:0102259  1,2-diacylglycerol acylhydrolase activity & replace by GO:0120516 diacylglycerol lipase activity
- GO:0102258 1,3-diacylglycerol acylhydrolase activity & replace by GO:0120516 diacylglycerol lipase activity
- GO:0033878 hormone-sensitive lipase activity & replace by GO:0120516 diacylglycerol lipase activity

The reason for obsoletion is that these terms represent specific substrates. 

There are 7 UniProt, 1 TAIR >> will be automatically replaced
EC and MetaCyc mappings >> will be fixed during the changes. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28339

Thanks, Pascale

**Comment by sjm41** [comment]
Turns out this assertion is wrong:
> All lipases are carboxylic ester hydrolase, so change parent here to 'GO:0052689 ! carboxylic ester hydrolase activity'

Most lipases do group under GO:0052689 (EC:3.1.1.-) but others group under 'phosphoric diester hydrolase activity GO:0008081 (EC:3.1.4.-) - e.g. phospholipase C, sphingomyelin phosphodiesterase.
That is, 'lipase activity' is an orthogonal grouping class.

So, need to change the parent of 'lipase activity' back to hydrolase activity, acting on ester bonds (GO:0016788) (EC:3.1.-.-)

**Comment by sjm41** [comment]
> So, need to change the parent of 'lipase activity' back to hydrolase activity, acting on ester bonds (GO:0016788) (EC:3.1.-.-)

Yes, this was the correct thing to do, BUT I should also have re-instated/added parentage to GO:0052689 (EC:3.1.1.-) for these terms (at least):
monoacylglycerol lipase activity (GO:0047372) EC:3.1.1.23
triglyceride lipase activity (GO:0004806) EC:3.1.1.3
sterol esterase activity (GO:0004771) EC:3.1.1.13
galactolipase activity (GO:0047714) EC:3.1.1.26
phospholipase A1 activity (GO:0008970) EC:3.1.1.32
phospholipase A2 activity (GO:0004623) EC:3.1.1.4
lysophospholipase activity (GO:0004622) EC:3.1.1.5
