### ISSUE TITLE
GO:0043794 formate dehydrogenase (coenzyme F420) activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28347]
id: GO:0043794
name: formate dehydrogenase (coenzyme F420) activity
def: "Catalysis of the reaction: formate + coenzyme F420 = CO2 + reduced coenzyme F420." [PMID:3801411]
xref: EC:1.2.99.-
is_a: GO:0016903 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors

This leaf term has a high-level partial EC xref.

There are 2 annotations by MENGO from PMID:3531194 (1986 paper from the Ferry lab) to 2 Methanobacterium formicicum genes:
fdhA (UniProtKB:P06131)
fdhB (UniProtKB:P06130)

This appears to be the same as EC:1.17.98.3/RHEA:42764/RXN-15617.
formate + 2 H(+) + oxidized coenzyme F420-(gamma-L-Glu)(n) = CO2 + reduced coenzyme F420-(gamma-L-Glu)(n)

RHEA:42764 references other papers from the Ferry lab, including "FAD requirement for the reduction of coenzyme F420 by formate dehydrogenase from Methanobacterium formicicum." and "Composition of the coenzyme F420-dependent formate dehydrogenase from Methanobacterium formicicum."

- [x] replace EC:1.2.99.- with other xrefs mentioned above
- [x] change parentage to fit new EC
- [x] Update def to match RHEA
