### ISSUE TITLE
alcohol dehydrogenase/aldo-keto reductase hierarchy

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28532]
We currently have this arrangement:
```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
    |_alcohol dehydrogenase [NAD(P)+] activity (GO:0018455) [EC:1.1.1.71, RHEA:10736]
        |_alcohol dehydrogenase (NAD+) activity (GO:0004022) [EC:1.1.1.1, RHEA:10740]
            |_[SEVERAL CHILDREN]
    |_aldo-keto reductase (NADPH) activity (GO:0004033) [no EC/RHEA]
        |_alcohol dehydrogenase (NADP+) activity (GO:0008106) [EC:1.1.1.2, RHEA:15937] aka "aldehyde reductase"
            |_[SEVERAL CHILDREN]
        |_carbonyl reductase (NADPH) activity (GO:0004090) [EC:1.1.1.184, RHEA:19257] aka "ketone reductase"
```

Note that all the reactions above are 'alcohol dehydrogenase' reactions - 'alcohol dehydrogenase' and 'Aldo/keto reductase' describe the same reaction though from opposite directions, and use either NAD or NADP as the acceptor.

Anyway, there are a few parentage and xref issues with the current hierarchy:

---

id: GO:0004022
**name: alcohol dehydrogenase (NAD+) activity**
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+." [EC:1.1.1.1]
xref: EC:1.1.1.1
xref: MetaCyc:ALCOHOL-DEHYDROG-GENERIC-RXN
xref: RHEA:10740
xref: UM-BBD_reactionID:r0022
xref: UM-BBD_reactionID:r0603
is_a: GO:0018455 ! alcohol dehydrogenase [NAD(P)+] activity

EC 1.1.1.1
**alcohol dehydrogenase**
a primary alcohol + NAD(+) = an aldehyde + H(+) + NADH
a secondary alcohol + NAD(+) = a ketone + H(+) + NADH
Mapped to: RHEA:10736	a primary alcohol + NAD+ = an aldehyde + H+ + NADH
Mapped to: RHEA:10740	a secondary alcohol + NAD+ = a ketone + H+ + NADH

Tasks:
- [x] Make RHEA:10740 narrowMatch xref
- [x] Add RHEA:10736 as second narrowMatch xref
- [x] Make MetaCyc:ALCOHOL-DEHYDROG-GENERIC-RXN narrowMatch xref
- [x] Add MetaCyc:RXN-12448 as narrowMatch xref
- [x] Make EC:1.1.1.1 exactMatch xref
- [x] Remove the two UM-BBD_reactionID xrefs, which are specific for octanol and Dodecanol

---

id: GO:0018455
**name: alcohol dehydrogenase [NAD(P)+] activity**
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NAD(P)+ = an aldehyde + NAD(P)H + H+." [EC:1.1.1.71]
xref: EC:1.1.1.71
xref: MetaCyc:ALCOHOL-DEHYDROGENASE-NADP+-RXN
xref: RHEA:10736
xref: UM-BBD_reactionID:r0172
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

EC:1.1.1.71
**alcohol dehydrogenase [NAD(P)(+)]**
a primary alcohol + NAD(+) = an aldehyde + H(+) + NADH
a primary alcohol + NADP(+) = an aldehyde + H(+) + NADPH
Reduces aliphatic aldehydes of chain length from C2 to C14, with greatest activity on C4, C6 and C8 aldehydes. Also reduces retinal to retinol.

Issue:
This is a grouping term in GO, but it's definition (and EC xref) are more specific than its children - i.e. it is specific for primary alcohols/aldehydes, while its child (GO:0004022 - see above) also includes secondary alcohols/ketones.  If we stick with the current definition, then we'll need to do some complicated/awkward rearranging of term relationships.

I think the simplest/better solution here is to:
- [x] Broaden the GO:0018455 definition to include secondary alcohols/ketones
- [x] Make EC:1.1.1.71 a narrowMatch xref
- [x] Similarly, make MetaCyc:ALCOHOL-DEHYDROGENASE-NADP+-RXN a narrowMatch xref

Also:
- [x] Remove RHEA:10736 xref (since that is specifically for NAD and should be added to GO:0004022 - see above)
- [x] Delete UM-BBD_reactionID:r0172 (the UM-BBD page says this is "EC:1.1.1.71" but then also says it's NADP+ specific, so it's unclear what that xref corresponds to)

---

id: GO:0004033
**name: aldo-keto reductase (NADPH) activity**
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NADP+ = an aldehyde or a ketone + NADPH + H+." [GOC:ai]
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27180" xsd:anyURI

Tasks:
- [x] If we broaden the definition of GO:0018455 to include secondary alcohols/ketones, then we should make that the parent of GO:0004033

---

id: GO:0008106
**name: alcohol dehydrogenase (NADP+) activity**
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NADP+ = an aldehyde + NADPH + H+." [EC:1.1.1.2]
xref: EC:1.1.1.2
xref: MetaCyc:ALCOHOL-DEHYDROGENASE-NADPORNOP+-RXN
xref: RHEA:15937
is_a: GO:0004033 ! aldo-keto reductase (NADPH) activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28183" xsd:anyURI

EC:1.1.1.2
**alcohol dehydrogenase (NADP(+))**
a primary alcohol + NADP(+) = an aldehyde + H(+) + NADPH
Some members of this group oxidize only primary alcohols; others act also on secondary alcohols.

- [x] Widen GO definition to include secondary alcohols/ketones, as per the EC comment. (Then it also matches the def of the sister term GO:0004022 alcohol dehydrogenase (NAD+) activity)
- [x] Make EC:1.1.1.2 exactMatch
- [x] Make RHEA:15937 narrowMatch

---

If we implement the above, the hierarchy becomes:

```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616) [EC:1.1.1.-]
    |_alcohol dehydrogenase [NAD(P)+] activity (GO:0018455) [EC:1.1.1.71]
        |_alcohol dehydrogenase (NAD+) activity (GO:0004022) [EC:1.1.1.1, RHEA:10740, RHEA:10736]
            |_[SEVERAL CHILDREN]
        |_aldo-keto reductase (NADPH) activity (GO:0004033) [no EC]
            |_alcohol dehydrogenase (NADP+) activity (GO:0008106) [EC:1.1.1.2, RHEA:15937]
                |_[SEVERAL CHILDREN]
            |_carbonyl reductase (NADPH) activity (GO:0004090) [EC:1.1.1.184, RHEA:19257]
```

What do you think @pgaudet ?

**Comment by pgaudet** [comment]
Just a question: if we broaden the def of GO:0018455 definition to include secondary alcohols/ketones, thenshould we also change the term name?

**Comment by sjm41** [comment]
>  if we broaden the def of GO:0018455 definition to include secondary alcohols/ketones, then should we also change the term name?

I don't think so.
Since the current GO:0018455 term name is "alcohol dehydrogenase [NAD(P)+] activity") rather than "**primary** alcohol dehydrogenase [NAD(P)+] activity", the implication is that it describes an activity that works with both primary and secondary alcohols.
Similarly, the name of the "GO:0004022 alcohol dehydrogenase (NAD+) activity" child term, which is already defined as working on both primary and secondary alcohols, just says "alcohol dehydrogenase".

**Comment by pgaudet** [comment]
Hi @sjm41 

My question about the changing the term label was about the aldo-keto versus alcohol distinction than about the primary/ secondary – intuitively an aldo-keto should not be is_a alcohol, although I did see what you wrote about these being the same reactions, in opposite directions. 

Looking more closely, we could consider obsoleting [aldo-keto reductase (NADPH) activity](http://purl.obolibrary.org/obo/GO_0004033) since it has no xrefs and seems to have been misused. 

For example the protein name of  https://www.uniprot.org/uniprotkb/P42330/entry is Aldo-keto reductase family 1 member C3, and is annotated to EC:1.1.1.357, which is missing from GO. 

So we could take advantage of this re-organization to get rid of aldo-keto reductase (NADPH) activity (GO:0004033) since that has no mappings. What do you think? 


Thanks, Pascale

**Comment by sjm41** [comment]
>So we could take advantage of this re-organization to get rid of aldo-keto reductase (NADPH) activity (GO:0004033) since that has no mappings. What do you think?

Yes, that looks good to me.
Though I see there are 23 direct EXP annotations to GO:0004033 that would need to be reviewed.

Obsoleting GO:0004033 (and doing the other tasks above) would lead to this simpler and more logical arrangement:

```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616) [EC:1.1.1.-]
    |_alcohol dehydrogenase [NAD(P)+] activity (GO:0018455) [EC:1.1.1.71]
        |_alcohol dehydrogenase (NAD+) activity (GO:0004022) [EC:1.1.1.1, RHEA:10740, RHEA:10736]
            |_[SEVERAL CHILDREN]
        |_alcohol dehydrogenase (NADP+) activity (GO:0008106) [EC:1.1.1.2, RHEA:15937]
            |_carbonyl reductase (NADPH) activity (GO:0004090) [EC:1.1.1.184, RHEA:19257]
            |_[SEVERAL OTHER CHILDREN]
```

**Comment by sjm41** [comment]
@pgaudet Let me know if I should go ahead and make the other (non-obsoletion) changes proposed above.

**Comment by deustp01** [comment]
> I see there are 23 direct EXP annotations to GO:0004033

Reactome is responsible for 7 of those and it looks like all could be patched with terms in the proposed simplified hierarchy.

**Comment by pgaudet** [comment]
yes yes

I had this on my list to discuss with you tomorrow, but please go ahead and get started.

**Comment by sjm41** [comment]
OK, I've done the 'easy' edits and we can discuss the final bits tomorrow.

**Comment by sjm41** [comment]
Looking at this term (which is in the hierarchy being discussed in this ticket):

id: GO:0050236
name: pyridoxine:NADP 4-dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: NADP+ + pyridoxine = H+ + NADPH + pyridoxal." [EC:1.1.1.65, RHEA:16129]
synonym: "PL reductase activity" RELATED [EC:1.1.1.65]
synonym: "pyridoxal reductase activity" RELATED [EC:1.1.1.65]
synonym: "pyridoxin dehydrogenase activity" RELATED [EC:1.1.1.65]
synonym: "pyridoxine dehydrogenase activity" RELATED [EC:1.1.1.65]
synonym: "pyridoxine:NADP 4-oxidoreductase activity" RELATED [EC:1.1.1.65]
synonym: "pyridoxol dehydrogenase activity" RELATED [EC:1.1.1.65]
xref: EC:1.1.1.65
xref: KEGG_REACTION:R01708
xref: MetaCyc:PYRIDOXINE-4-DEHYDROGENASE-RXN
xref: RHEA:16129
is_a: GO:0004033 ! aldo-keto reductase (NADPH) activity


- [ ] Change name to 'pyridoxine 4-dehydrogenase (NADP+) activity' to follow EC name and current GO naming conventions
- [ ] remove EC from def xref
- [ ] change parent to more specific alcohol dehydrogenase (NADP+) activity (GO:0008106)

**Comment by sjm41** [comment]
@pgaudet  I'm trying to close this ticket...

Here's how the hierarchy now looks now:

```
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616) [EC:1.1.1.-]
    |_alcohol dehydrogenase [NAD(P)+] activity (GO:0018455) [EC:1.1.1.71 - narrow]
        |_alcohol dehydrogenase (NAD+) activity (GO:0004022) [EC:1.1.1.1, RHEA:10740, RHEA:10736]
            |_[SEVERAL CHILDREN]
        |_aldo-keto reductase (NADPH) activity (GO:0004033) [no EC]
            |_alcohol dehydrogenase (NADP+) activity (GO:0008106) [EC:1.1.1.2, RHEA:15937 - narrow]
                |_[SEVERAL CHILDREN]
```

I think we should go ahead and obsoleted  aldo-keto reductase (NADPH) activity (GO:0004033), as proposed above.

In addition to the reasons stated above, 'alcohol dehydrogenase (NADP+) activity (GO:0008106)' is the single child of 'aldo-keto reductase (NADPH) activity (GO:0004033)' and forever, their definitions are the same:

id: GO:0004033
name: aldo-keto reductase (NADPH) activity
def: "Catalysis of the reaction: an alcohol + NADP+ = an aldehyde or a ketone + NADPH + H+." [GOC:ai]

id: GO:0008106
name: alcohol dehydrogenase (NADP+) activity
def: "Catalysis of the reaction: an alcohol + NADP+ = an aldehyde or ketone + NADPH + H+." [EC:1.1.1.2]

So GO:0008106 can be a direct replacement for GO:0004033, meaning the 24 direct EXP annotations to GO:0004033 won't need to be checked - they can just move.

What do you think?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0004033 aldo-keto reductase (NADPH) activity & replace by GO:0008106 GO:0008106, because these terms represent the same reaction. There are 69 annotations to this term 


Group | Number of manual annotations
-- | --
CGD | 1
EcoCyc | 2
EcoliWiki | 1
MGI | 2
Reactome | 17
RGD | 5
SGD | 4
TAIR | 1
UniProt | 14
ZFIN | 2

There is 1 InterPro mapping and 20 Reactome mappings.

**Comment by deustp01** [comment]
Reactome done.
