### ISSUE TITLE
carbonyl reductase (NADPH) activity (GO:0004090)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28530]
id: GO:0004090
name: carbonyl reductase (NADPH) activity
namespace: molecular_function
def: "Catalysis of the reaction: R-CHOH-R' + NADP+ = R-CO-R' + NADPH + H+." [EC:1.1.1.184]
synonym: "aldehyde reductase 1" RELATED [EC:1.1.1.184]
synonym: "aldehyde reductase I activity" RELATED [EC:1.1.1.184]
synonym: "ALR3" RELATED [EC:1.1.1.184]
synonym: "carbonyl reductase activity" RELATED [EC:1.1.1.184]
synonym: "NADPH-dependent carbonyl reductase activity" RELATED [EC:1.1.1.184]
synonym: "NADPH2-dependent carbonyl reductase activity" RELATED [EC:1.1.1.184]
synonym: "nonspecific NADPH-dependent carbonyl reductase activity" RELATED [EC:1.1.1.184]
synonym: "prostaglandin 9-ketoreductase activity" NARROW [EC:1.1.1.184]
synonym: "secondary-alcohol:NADP+ oxidoreductase activity" RELATED [EC:1.1.1.184]
synonym: "xenobiotic ketone reductase activity" NARROW [EC:1.1.1.184]
xref: EC:1.1.1.184
xref: MetaCyc:CARBONYL-REDUCTASE-NADPH-RXN
xref: RHEA:19257
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

- [x] Update def to the clearer, current EC/RHEA def: a secondary alcohol + NADP+ = a ketone + H+ + NADPH
- [x] Change parent to GO:0004033:
- [x] Make xrefs exactMatch

id: GO:0004033
name: aldo-keto reductase (NADPH) activity
def: "Catalysis of the reaction: an alcohol + NADP+ = an aldehyde or a ketone + NADPH + H+." [GOC:ai]
synonym: "alcohol dehydrogenase (NADP+) activity" NARROW []
synonym: "aldo-keto reductase (NADP) activity" EXACT []
synonym: "aldo-keto reductase (NADP+) activity" EXACT []
synonym: "aldo-keto reductase activity" EXACT []
synonym: "NADPH-dependent aldo-keto reductase activity" EXACT [GOC:vw]
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
