### ISSUE TITLE
Transferred ECs to update

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28647]
From https://github.com/geneontology/go-ontology/pull/28636:

ERROR: http://purl.obolibrary.org/obo/GO_0016844 has a definition xref to an obsolete EC: "EC:4.3.3.2"
ERROR: http://purl.obolibrary.org/obo/GO_0016844 has a synonym xref to an obsolete EC: "EC:4.3.3.2"
ERROR: http://purl.obolibrary.org/obo/GO_0016844 has an xref to an obsolete EC: "EC:4.3.3.2"
ERROR: http://purl.obolibrary.org/obo/GO_0030269 has a definition xref to an obsolete EC: "EC:2.1.1.86"
ERROR: http://purl.obolibrary.org/obo/GO_0030269 has a synonym xref to an obsolete EC: "EC:2.1.1.86"
ERROR: http://purl.obolibrary.org/obo/GO_0030269 has an xref to an obsolete EC: "EC:2.1.1.86"
ERROR: http://purl.obolibrary.org/obo/GO_0050474 has a definition xref to an obsolete EC: "EC:4.2.1.78"
ERROR: http://purl.obolibrary.org/obo/GO_0050474 has a synonym xref to an obsolete EC: "EC:4.2.1.78"
ERROR: http://purl.obolibrary.org/obo/GO_0050474 has an xref to an obsolete EC: "EC:4.2.1.78"
ERROR: http://purl.obolibrary.org/obo/GO_0050556 has a definition xref to an obsolete EC: "EC:4.3.3.3"
ERROR: http://purl.obolibrary.org/obo/GO_0050556 has a synonym xref to an obsolete EC: "EC:4.3.3.3"
ERROR: http://purl.obolibrary.org/obo/GO_0050556 has an xref to an obsolete EC: "EC:4.3.3.3"
ERROR: http://purl.obolibrary.org/obo/GO_0050557 has a definition xref to an obsolete EC: "EC:4.3.3.4"
ERROR: http://purl.obolibrary.org/obo/GO_0050557 has a synonym xref to an obsolete EC: "EC:4.3.3.4"
ERROR: http://purl.obolibrary.org/obo/GO_0050557 has an xref to an obsolete EC: "EC:4.3.3.4"

EC 4.3.3.2
Transferred entry: [3.5.99.13](https://enzyme.expasy.org/EC/3.5.99.13)

EC 2.1.1.86
Transferred entry: [7.2.1.4](https://enzyme.expasy.org/EC/7.2.1.4)

EC 4.2.1.78
Transferred entry: [3.5.99.14](https://enzyme.expasy.org/EC/3.5.99.14)

EC 4.3.3.3
Transferred entry: [3.5.99.15](https://enzyme.expasy.org/EC/3.5.99.15)

EC 4.3.3.4
Transferred entry: [3.5.99.16](https://enzyme.expasy.org/EC/3.5.99.16)

So, the good news is that these 5 cases are all 1:1 transfers.
But the complication in each cases is the reaction/enzyme has changed its major classification (e.g. lyase to hydrolase), so we will need to review and change the parentage in GO.

**Comment by sjm41** [comment]
id: GO:0016844
name: strictosidine synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3alpha(S)-strictosidine + H2O = secologanin + tryptamine." [EC:4.3.3.2, RHEA:15013]
synonym: "3-alpha(S)-strictosidine tryptamine-lyase (secologanin-forming)" RELATED [EC:4.3.3.2]
synonym: "3-alpha(S)-strictosidine tryptamine-lyase activity" RELATED [EC:4.3.3.2]
synonym: "STR activity" RELATED [EC:4.3.3.2]
synonym: "strictosidine synthetase activity" RELATED [EC:4.3.3.2]
xref: EC:4.3.3.2
xref: KEGG_REACTION:R03738
xref: MetaCyc:STRICTOSIDINE-SYNTHASE-RXN
xref: RHEA:15013
is_a: GO:0016843 ! amine-lyase activity

- [ ] Change EC term xref to EC:3.5.99.13
- [ ] Check and update synonym EC xrefs
- [ ] remove EC from def (just use RHEA)
- [ ] change parent to GO:0016810 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (xref: EC:3.5.-.-)

---

id: GO:0030269
name: tetrahydromethanopterin S-methyltransferase activity
namespace: molecular_function
alt_id: GO:0018709
def: "Catalysis of the reaction: 5-methyltetrahydromethanopterin + coenzyme M = 5,6,7,8-tetrahydromethanopterin + methyl-coenzyme M. 2-(methylthio)ethanesulfonate is also known as methyl-CoM." [EC:2.1.1.86, RHEA:53492]
synonym: "5-methyl-5,6,7,8-tetrahydromethanopterin:2-mercaptoethanesulfonate 2-methyltransferase activity" RELATED [EC:2.1.1.86]
synonym: "N(5)-methyltetrahydromethanopterin--coenzyme M methyltransferase activity" RELATED [EC:2.1.1.86]
synonym: "N5-methyltetrahydromethanopterin--coenzyme M methyltransferase activity" RELATED [EC:2.1.1.86]
synonym: "tetrahydromethanopterin methyltransferase activity" RELATED [EC:2.1.1.86]
xref: EC:2.1.1.86
xref: KEGG_REACTION:R04347
xref: MetaCyc:2.1.1.86-RXN
xref: RHEA:53492
xref: UM-BBD_reactionID:r0355
is_a: GO:0008172 ! S-methyltransferase activity
is_a: GO:0042086 ! 5-methyl-5,6,7,8-tetrahydromethanopterin-dependent methyltransferase activity

- [ ] Change EC term xref to EC:7.2.1.4
- [ ] Check and update synonym EC xrefs
- [ ] remove EC from def (just use RHEA)
- [ ] add "GO:0015081 sodium ion transmembrane transporter activity" (and keep current parents since still true??)

---

id: GO:0050474
name: (S)-norcoclaurine synthase activity
namespace: molecular_function
alt_id: GO:0050475
def: "Catalysis of the reaction: 4-(2-aminoethyl)benzene-1,2-diol + 4-hydroxyphenylacetaldehyde = (S)-norcoclaurine + H2O." [EC:4.2.1.78]
synonym: "(S)-norlaudanosoline synthase activity" RELATED [EC:4.2.1.78]
synonym: "4-hydroxyphenylacetaldehyde hydro-lyase (adding dopamine)" RELATED [EC:4.2.1.78]
synonym: "4-hydroxyphenylacetaldehyde hydro-lyase [adding dopamine; (S)-norcoclaurine-forming]" RELATED [EC:4.2.1.78]
xref: EC:4.2.1.78
xref: MetaCyc:S-NORLAUDANOSOLINE-SYNTHASE-RXN
xref: RHEA:16173
is_a: GO:0016836 ! hydro-lyase activity

- [ ] Change EC term xref to EC:3.5.99.14
- [ ] Check and update synonym EC xrefs
- [ ] remove EC from def (use RHEA instead)
- [ ] change parent to GO:0016810 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (xref: EC:3.5.-.-)

---

id: GO:0050556
name: deacetylisoipecoside synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: deacetylisoipecoside + H2O = dopamine + secologanin." [EC:4.3.3.3, RHEA:21756]
synonym: "deacetylisoipecoside dopamine-lyase (secologanin-forming)" RELATED [EC:4.3.3.3]
synonym: "deacetylisoipecoside dopamine-lyase activity" RELATED [EC:4.3.3.3]
xref: EC:4.3.3.3
xref: KEGG_REACTION:R05750
xref: MetaCyc:4.3.3.3-RXN
xref: RHEA:21756
is_a: GO:0016843 ! amine-lyase activity

- [ ] Change EC term xref to EC:3.5.99.15
- [ ] Check and update synonym EC xrefs
- [ ] remove EC from def (just use RHEA)
- [ ] change parent to GO:0016810 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (xref: EC:3.5.-.-)

---

id: GO:0050557
name: deacetylipecoside synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: deacetylipecoside + H2O = dopamine + secologanin." [EC:4.3.3.4, RHEA:12296]
synonym: "deacetylipecoside dopamine-lyase (secologanin-forming)" RELATED [EC:4.3.3.4]
synonym: "deacetylipecoside dopamine-lyase activity" RELATED [EC:4.3.3.4]
xref: EC:4.3.3.4
xref: KEGG_REACTION:R05749
xref: MetaCyc:4.3.3.4-RXN
xref: RHEA:12296
is_a: GO:0016843 ! amine-lyase activity

- [ ] Change EC term xref to EC:3.5.99.16
- [ ] Check and update synonym EC xrefs
- [ ] remove EC from def (just use RHEA)
- [ ] change parent to GO:0016810 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (xref: EC:3.5.-.-)
