### ISSUE TITLE
Clean up xref handling in ontology outputs

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#28763]
We have been annotating xrefs using qualifiers like `skos:narrowMatch` and `skos:exactMatch` (#20620). Right now the degree to which these annotations are carried through the pipeline varies, and likewise the handling of these qualifiers in outputs varies. We will make handling of these more sensible in a few ways:

- [ ] Only allow exact and narrow mappings into x2go files
- [ ] Only allow exact and narrow mappings into production OBO files
- [ ] Ensure trailing qualifiers are included in OBO files. These were previously filtered out.
- [ ] Generate direct skos triples from the qualified xrefs, as a more straightforward representation of mappings in the ontology #27247
  - We should make sure that the OBO representation of these triples uses CURIEs, by specifying the needed IDSPACEs (related: #28012)
- [ ] Generate SSSOM versions of mappings files, which is able to represent the qualifiers #20147
- [ ] Ensure xref qualifiers are correctly structured #28417

**Comment by pgaudet** [comment]
I am assigning myself to add documentation once this is done.

**Comment by ValWood** [comment]
tagging myself so that I can remove my filter when  it's fixed.

**Comment by balhoff** [comment]
We should discuss URI expansions for SKOS predicate values in the OBO prefixes Slack channel.

**Comment by balhoff** [comment]
Consider merging external x2go mappings into the built ontology for release: https://github.com/geneontology/go-ontology/blob/111d6fbe6ea1b68639f71a52985bfe2f3fa4a44a/src/ontology/Makefile#L612-L622

Also, consider retrieving external x2go mappings directly as SSSOM.
