### ISSUE TITLE
NAD(P) metabolic process terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#29050]
We currently have this arrangement:

```
NAD metabolic process
|__NAD biosynthetic process
|__NAD catabolic process
|__NADH metabolic process
    |__NADH oxidation
    |__NADH regeneration

NADP metabolic process
|__NADP biosynthetic process
|__NADP catabolic process
|__NADPH oxidation
|__NADPH regeneration
```

And here are the terms:

id: GO:0019674
name: NAD metabolic process
def: "The chemical reactions and pathways involving nicotinamide adenine dinucleotide (NAD), a coenzyme present in most living cells and derived from the B vitamin nicotinic acid." [GOC:jl, ISBN:0618254153]
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:13389 ! NAD
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21577" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23467" xsd:anyURI

id: GO:0009435
name: NAD biosynthetic process
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide, a coenzyme present in most living cells and derived from the B vitamin nicotinic acid; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH." [GOC:jl, ISBN:0618254153]
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:13389 ! NAD
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21577" xsd:anyURI

id: GO:0019677
name: NAD catabolic process
def: "The chemical reactions and pathways resulting in the breakdown of nicotinamide adenine dinucleotide, a coenzyme present in most living cells and derived from the B vitamin nicotinic acid; catabolism may be of either the oxidized form, NAD, or the reduced form, NADH." [GOC:jl, ISBN:0618254153]
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:13389 ! NAD
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21577" xsd:anyURI

id: GO:0006734 (28 direct EXP annotations)
name: NADH metabolic process
def: "The chemical reactions and pathways involving reduced nicotinamide adenine dinucleotide (NADH), a coenzyme present in most living cells and derived from the B vitamin nicotinic acid." [GOC:jl, ISBN:0618254153]
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:57945 ! NADH(2-)

id: GO:0006116 (25 direct EXP annotations)
name: NADH oxidation
def: "A metabolic process that results in the oxidation of reduced nicotinamide adenine dinucleotide, NADH, to the oxidized form, NAD+." [GOC:ai]
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input CHEBI:57945 ! NADH(2-)
intersection_of: has_primary_output CHEBI:57540 ! NAD(1-)
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21577" xsd:anyURI

id: GO:0006735 (9 direct EXP annotations)
name: NADH regeneration
def: "A metabolic process that generates a pool of NADH by the reduction of NAD+." [GOC:mah]
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_output CHEBI:57945 ! NADH(2-)
intersection_of: has_primary_input CHEBI:57540 ! NAD(1-)
intersection_of: has_primary_output CHEBI:57945 ! NADH(2-)

---

id: GO:0006739
name: NADP metabolic process
def: "The chemical reactions and pathways involving nicotinamide-adenine dinucleotide phosphate, a coenzyme involved in many redox and biosynthetic reactions; metabolism may be of either the oxidized form, NADP, or the reduced form, NADPH." [GOC:mah]
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:58349 ! NADP(3-)
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23467" xsd:anyURI

id: GO:0006741
name: NADP biosynthetic process
def: "The chemical reactions and pathways resulting in the formation of nicotinamide-adenine dinucleotide phosphate, a coenzyme involved in many redox and biosynthetic reactions; biosynthesis may be of either the oxidized form, NADP, or the reduced form, NADPH." [GOC:mah]
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:58349 ! NADP(3-)

id: GO:0006742
name: NADP catabolic process
def: "The chemical reactions and pathways resulting in the breakdown of nicotinamide-adenine dinucleotide phosphate, a coenzyme involved in many redox and biosynthetic reactions; catabolism may be of either the oxidized form, NADP, or the reduced form, NADPH." [GOC:mah]
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:58349 ! NADP(3-)

id: GO:0070995 (16 direct EXP annotations)
name: NADPH oxidation
def: "A metabolic process that results in the oxidation of reduced nicotinamide adenine dinucleotide, NADPH, to the oxidized form, NADP." [GOC:BHF, GOC:mah]
is_a: GO:0006739 ! NADP metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input CHEBI:57783 ! NADPH(4-)
intersection_of: has_primary_output CHEBI:58349 ! NADP(3-)

id: GO:0006740 (24 direct EXP annotations)
name: NADPH regeneration
def: "A metabolic process that generates a pool of NADPH by the reduction of NADP+." [GOC:mah]
is_a: GO:0006091 ! generation of precursor metabolites and energy
is_a: GO:0006739 ! NADP metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input CHEBI:58349 ! NADP(3-)
intersection_of: has_primary_output CHEBI:57783 ! NADPH(4-)

---

I think there are several issues to address here:

- [x] In all these defs, "the oxidized form" should be reported as 'NAD+' or ''NADP+' rather than just 'NAD' or 'NADP'.

- [x] For the 'NAD metabolic process' term def, should add "metabolism may be of either the oxidized form, NAD+, or the reduced form, NADH." to match the defs of the child 'NAD biosynthetic/catabolic process' terms as well as the def of the equivalent 'NADP metabolic process' term.

- [ ] Implementing the point above would make the "NADH metabolic process" term redundant, so it should be obsoleted (or rather merged into the parent 'NAD metabolic process' term). Doing so would also then match how the NADP branch is already organised.

- [x] As alluded to in #27924, "NADH oxidation" and "NADPH oxidation" are just inevitable consequences of these factors acting as co-enzymes for oxidoreductase enzymes - I can't see any utility in having these terms (as defined), since they could be applied to any oxidoreductase reaction using NAD(P)H and operating in the reductase direction. Suggest these two terms are obsoleted.

- [x] Change the primary_input/output chemical on the NAD metabolic/biosynthesis/catabolic terms from 'CHEBI:13389 ! NAD' to 'CHEBI:57540 ! NAD(1-)' to be consistent with how this is reported in the other terms mentioned above. (This was meant to be fixed in #23467, but doesn't look like it actually happened.)

- [x] The LD of the 'NADH regeneration' term has the same CHEBI as both 'has_output' and 'has_primary_output' - remove the former.

- [x] The 'NADPH regeneration' term appears to have a "is_a: GO:0006739 ! NADP metabolic process" relation that is redundant with the LD - need to check and remove if so.

I found PMID:28648096 is a good general review of NAD(H) and NADP(H) biology, including synthetic pathways.

@rozaru  @deustp01  @ukemi 

See also ticket #24279

**Comment by rozaru** [comment]
The NAD biosynthetic process branch will need some updating too.

```
NAD biosynthetic process
    |__'de novo' NAD biosynthetic process
    |   |__'de novo' NAD biosynthetic process from aspartate
    |   |__'de novo' NAD biosynthetic process from tryptophan(+ regulatory terms)
    |__NAD biosynthesis via nicotinamide riboside salvage pathway
    |__NAD salvage
```
This is how the GO terms fits into the various pathways known to make NAD.

![image](https://github.com/user-attachments/assets/63002a36-0911-4e91-ae7c-bb0f4c02b039)


There are various issues:

1. term definitions needs to be updated
2. some Xref to MetacCyc are missing
3. misplaced terms
---

For the parent:

> **GO:0009435 NAD biosynthetic process**
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide, a coenzyme present in most living cells and derived from the B vitamin nicotinic acid; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

- the definition is too restrictive and doesn’t mention the alternative routes
- vitamin B3 would be the correct term and this term normally includes various forms including nicotinamide and nicotinic acid (nicotinate)

Proposal 1:

def:"The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), a coenzyme present in most living cells; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

Proposal 2:

def:"The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), a coenzyme present in most living cells and is derived from various sources including vitamin B3; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

---
For these 2 terms:

> GO:0034628 **'de novo' NAD biosynthetic process from aspartate**
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the synthesis of aspartate from simpler precursors; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

> GO:0034354 **'de novo' NAD biosynthetic process from tryptophan**
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the synthesis of tryptophan from simpler precursors; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

- both definitions “beginning with the synthesis of aspartate/tryptophane”. This is incorrect as it is their catabolism that provides the precursor quinolinate for NAD biosynthesis
- normally it's **L**-aspartate and **L**-tryptophan

Proposal:

GO:0034628 'de novo' NAD biosynthetic process from L-aspartate
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the catabolism of L-aspartate into the precursor quinolinate; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

GO:0034354 'de novo' NAD biosynthetic process from L-tryptophan
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the catabolism of L-tryptophan into the precursor quinolinate; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

---
For these terms:

> GO:0034355 NAD salvage
> def: "Any process that generates nicotinamide adenine dinucleotide (NAD) from derivatives of it, without de novo synthesis; salvage is usually from the degradation products nicotinic acid (Na) and nicotinamide (Nam)."

- “from the degradation products...” it’s probably true but they are mostly acquired from the diet
- the term name may be updated
-  In the literature, the production of NAD from nicotinate (nicotinic acid) is called the Preiss-Handler pathway, some authors include it in the salvage pathway other not. For the moment the NAD salvage GO term includes it. 

Proposal:

GO:0034355 NAD salvage biosynthetic process
Def: Any process that generates nicotinamide adenine dinucleotide (NAD) from vitamin B3 derivatives including nicotinic acid (NA) and nicotinamide (NAM), without de novo synthesis. NAD can also be produced from beta-nicotinamide D-ribonucleotide (NMN) or beta-nicotinamide D-riboside (NR).

> GO:0034356 NAD biosynthesis via nicotinamide riboside salvage pathway
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD) from the vitamin precursor nicotinamide riboside."

- it should be a child of GO:0034355 NAD salvage
- Should this term be kept or merged to NAD salvage?
- If the term is kept the name and the definition will need to be updated and the other compounds would need their own GO term

**Comment by pgaudet** [comment]
Hi @rozaru 

Maybe GO:0034355 NAD biosynthetic process by/via (the) salvage pathway sounds less GO-speak?

**Comment by rozaru** [comment]
@pgaudet 
I like your suggestion "NAD biosynthetic process via the salvage pathway", it works better.

**Comment by rozaru** [comment]
After discussion with @ukemi and @deustp01, the following updates are proposed which take into account the comments above.

The changes involve:
- updating GO term name, definition, output/input and MetaCyc Xref (see below)
- making the following GO terms obsolete (see below)
|__NADH metabolic process
    |   |__NADH oxidation
    |   |__NADH regeneration
- making the 2 shuttle terms direct children of NAD metabolic process
NAD+ metabolic process
    |__glycerophosphate shuttle
    |__malate-aspartate shuttle 
- finding a new place for "sulphoglycolysis" in the ontology (see below)


The NADP metabolic branch will be look at later and may involve further changes.

Current NAD branch:

```
NAD metabolic process
    |__NAD biosynthetic process
    |   |__'de novo' NAD biosynthetic process
    |   |   |__'de novo' NAD biosynthetic process from aspartate
    |   |   |__'de novo' NAD biosynthetic process from tryptophan(+)
    |   |__NAD biosynthesis via nicotinamide riboside salvage pathway
    |   |__NAD salvage
    |__NAD catabolic process
    |   |__canonical glycolysis
    |__NADH metabolic process TO REMOVE
    |   |__NADH oxidation TO REMOVE
    |   |   |__glycerophosphate shuttle DIRECT CHILD OF NAD MET PRO
            |   |   |__malate-aspartate DIRECT CHILD OF NAD MET PRO
            |   |__NADH regeneration TO REMOVE
            |   |   |__canonical glycolysis
            |   |__sulphoglycolysis TO REMOVE
    |__regulation of NAD metabolic process
```

Updated NAD branch:

```
NAD+ metabolic process
        |__NAD+ biosynthetic process
        |   |__'de novo' NAD+ biosynthetic process
        |   |   |__'de novo' NAD+ biosynthetic process from aspartate
        |   |   |__'de novo' NAD+ biosynthetic process from tryptophan(+)
        |   |__NAD+ salvage
        	|__NAD+ biosynthesis via nicotinamide riboside salvage pathway            
        |__NAD+ catabolic process
        |__glycerophosphate shuttle
        |__malate-aspartate shuttle 
        |__regulation of NAD+ metabolic process
```


**Terms to update**

- [ ] GO:0019674 NAD metabolic process

From:
> def: "The chemical reactions and pathways involving nicotinamide adenine dinucleotide (NAD), a coenzyme present in most living cells and derived from the B vitamin nicotinic acid." [GOC:jl, ISBN:0618254153]
> intersection_of: has_primary_input_or_output CHEBI:13389 ! NAD

To:
def: "The chemical reactions and pathways involving nicotinamide adenine dinucleotide (NAD), a coenzyme involved in many redox and catabolic reactions; metabolism may be of either the oxidized form, NAD+, or the reduced form, NADH." [GOC:jl, ISBN:0618254153]
intersection_of: has_primary_input_or_output **CHEBI:57540 ! NAD(1−)**

----

- [ ] GO:0009435 NAD biosynthetic process

From:
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide, a coenzyme present in most living cells and derived from the B vitamin nicotinic acid; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

To:
def:"The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), a coenzyme involved in many redox and catabolic reactions and is derived from various sources including vitamin B3; biosynthesis may be of either the oxidized form, NAD+, or the reduced form, NADH."
intersection_of: has_primary_output **CHEBI:57540] ! NAD(1−)**

----

- [ ] GO:0034628 'de novo' NAD biosynthetic process from aspartate

From:
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the synthesis of aspartate from simpler precursors; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

To:
name: 'de novo' NAD biosynthetic process from **L-aspartate**
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the catabolism of L-aspartate into the precursor quinolinate; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."
**comment: This pathway is found in bacteria, Archae and may also occur in plants.**
intersection_of: has_primary_input **CHEBI:29991 ! L-aspartate(1−)**
intersection_of: has_primary_output CHEBI:25527 ! **CHEBI:57540 ! NAD(1−)**
**MetaCyc: PYRIDNUCSYN-PWY**
**MetaCyc: PWY-8352**
**MetaCyc: PWY-8277**

----

- [ ] GO:0034354 'de novo' NAD biosynthetic process from tryptophan

From:
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the synthesis of tryptophan from simpler precursors; biosynthesis may be of either the oxidized form, NAD, or the reduced form, NADH."

To:
name: 'de novo' NAD biosynthetic process from **L-tryptophan**
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD), beginning with the catabolism of L-tryptophan into the precursor quinolinate; biosynthesis may be of either the oxidized form, NAD+, or the reduced form, NADH."
**comment: This pathway is found in eukaryotes.**
intersection_of: has_primary_input **CHEBI:57912 ! L-tryptophan zwitterion**
intersection_of: has_primary_output CHEBI:25527 ! **CHEBI:57540 ! NAD(1−)**
**MetaCyc: NADSYN-PWY**
**MetaCyc: PWY-5653**

- [ ] The regulatory children terms need to be updated to:

id: GO:1905012
name: regulation of 'de novo' NAD biosynthetic process from **L-tryptophan**
def: "Any process that modulates the frequency, rate or extent of 'de novo' NAD biosynthetic process from **L-tryptophan**."

id: GO:1905013
name: negative regulation of 'de novo' NAD biosynthetic process from **L-tryptophan**
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of 'de novo' NAD biosynthetic process from **L-tryptophan**."

id: GO:1905014
name: positive regulation of 'de novo' NAD biosynthetic process from **L-tryptophan**
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of 'de novo' NAD biosynthetic process from **L-tryptophan**." 

----

- [ ] GO:0034355 NAD salvage

From:
> def: "Any process that generates nicotinamide adenine dinucleotide (NAD) from derivatives of it, without de novo synthesis; salvage is usually from the degradation products nicotinic acid (Na) and nicotinamide (Nam)."

To:
name: **NAD biosynthetic process via the salvage pathway** _(or keep the original name?)_
Def: Any process that generates nicotinamide adenine dinucleotide (NAD) from vitamin B3 derivatives including nicotinic acid (NA) and nicotinamide (NAM), without de novo synthesis. NAD can also be produced from beta-nicotinamide D-ribonucleotide (NMN), nicotinamide riboside (NR) or nicotinate riboside (NAR).
intersection_of: has_primary_output **CHEBI:57540 ! NAD(1−)**
**MetaCyc: NAD-BIOSYNTHESIS-III** (nicotinamide, bacteria)
**MetaCyc: PWY-8511** (nicotinate, bacteria, eukaryote)
**MetaCyc: PWY-5381** (cycle, plants)
**MetaCyc: PYRIDNUCSAL-PWY** (cycle, bacteria)
**MetaCyc: PWY-7761** (cycle, bacteria)
**MetaCyc: PWY3O-4107** (nicotinate, cycle, eukaryotes, Preiss-Handler pathway)

----

- [ ] GO:0034356 NAD biosynthesis via nicotinamide riboside salvage pathway

**This should be a child of GO:0034355 NAD salvage.**

From:
> def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD) from the vitamin precursor nicotinamide riboside."

To:
name: GO:0034356 **NAD biosynthetic process via nicotinamide riboside salvage pathway**
def: "The chemical reactions and pathways resulting in the formation of nicotinamide adenine dinucleotide (NAD) from the nicotinamide riboside (NR)."
intersection_of: has_primary_input **CHEBI:15927 ! N-ribosylnicotinamide**
intersection_of: has_primary_output  **CHEBI:57540 ! NAD(1−)**
**MetaCyc: PWY3O-4106**

There was some confusion in the GO terms for which compounds are Vitamin B3 derivates:
Nicotinate (NA, nicotinic acid/niacin) and nicotinamide (NAM, niacinamide) are related forms (vitamers) of vitamin B3 (see [ChEBI](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:176839) and PMID:30559273).

----

- [ ] GO:0019677 NAD catabolic process

From:

> def: "The chemical reactions and pathways resulting in the breakdown of nicotinamide adenine dinucleotide (NAD), a coenzyme present in most living cells and derived from the B vitamin nicotinic acid; catabolism may be of either the oxidized form, NAD, or the reduced form, NADH." [GOC:jl, ISBN:0618254153]

To:
def:"The chemical reactions and pathways resulting in the breakdown of nicotinamide adenine dinucleotide (NAD), a coenzyme involved in many redox and catabolic reactions; catabolism may be of either the oxidized form, NAD+, or the reduced form, NADH."
intersection_of: has_primary_input  **CHEBI:57540 ! NAD(1−)**
**MetaCyc: NAD-BIOSYNTHESIS-II** (the way the pathway is shown looks like catabolism, plants)

The NAD catabolic process usually feeds the NAD salvage pathway.

----


**Terms to obsolete**

            |__NADH metabolic process
            |   |__NADH oxidation
            |   |__NADH regeneration

- These terms cover usually a 1 step reaction (NAD -> NADH) which are often part of other processes (ex. glycolysis).
- Most of the genes annotated with the terms could be annotated to another process or their MF is enough to describe their function.
- For "NADH metabolic process", the inclusion of NADH in the definition of NAD metabolic process makes this term redundant.

- The only issue that remain is where to put the GO term "sulphoglycolysis" (no annotation).
"The chemical reactions and pathways resulting in the breakdown of 6-sulfoquinovose(1-) resulting in the formation of glycerone phosphate (DHAP) and pyruvate."
6-sulfoquinovose is sulfonic acid derivative of glucose. 
Could this term be a child of GO:0006096 glycolytic process?

**Comment by tberardini** [comment]
Back from a few days off. I think that as long as there's no proposal to obsolete the NADP/H terms, the improvements that are suggested for NAD/H sound great and whichever ones are applicable to NADP/H would improve those terms as well.

**Comment by ukemi** [comment]
Thanks @tberardini. I think there is a proposal to obsolete the NADPH metabolic process terms because there was an argument that the only thing NADPH does is inter-convert with NADP. @rozaru, correct me if I am wrong.

**Comment by sjm41** [comment]
I'm going to start working on the revisions to the NAD branch now.

**Comment by sjm41** [comment]
Still to do in the NAD branch:

- [x] Add taxon constraint 'only in eukaryotes' to GO:0034354 'de novo' NAD biosynthetic process from tryptophan
- [x] Obsolete 'NADH metabolic process' (26 direct EXP annotations)
- [x] Obsolete 'NADH oxidation' (27 direct EXP annotations)
- [x] Obsolete 'NADPH oxidation'   (12 direct EXP annotations)
- [ ] Obsolete 'NADH regeneration' (9 direct EXP) >> see #29818 
- [x] Consider obsoleting 'GO:0034627  de novo' NAD biosynthetic process (1 direct EXP) as an unnecessary grouping term
(Rossana: Probably this comes from the literature where de novo' NAD synthesis is used to group the Asp and Trp.) 
- [x] Consider obsoleting 'GO:0034356 NAD biosynthesis via nicotinamide riboside salvage pathway' (7 direct EXP), since it's a single child of its parent term (we don't have separate terms for the other specific salvage pathways)
- [ ] Consider obsoleting 'GO:1905012 regulation of 'de novo' NAD biosynthetic process from L-tryptophan' and it's two children (only 2 TAS annotations to the parent, none to the children), and other terms in this branch don't have regulation terms)

**Comment by ukemi** [comment]
You should remove NAD as a primary input to canonical glycolysis. Clearly something has gone wonky with that over time and glycolysis is now inferred to catabolize it. It will be interesting to see what will happen with the children of NADH regeneration when you do this. Might want to check the logical def for that.

**Comment by ukemi** [comment]
Ah. OK. I am getting ahead of myself, but I don't think anyone would ever think glycolysis catabolizes NAD.

**Comment by sjm41** [comment]
I changed the 'has_primary_input CHEBI:57540 ! NAD(1-)' to 'has_participant CHEBI:57540 ! NAD(1-)' on canonical glycolysis. (let me know if you think it's better just to remove it entirely).

That's fixed the spurious parentages - current tree now looks like this:

![Image](https://github.com/user-attachments/assets/9d664938-bf1e-40b3-ad2f-9b90dfd138e2)

**Comment by ukemi** [comment]
It's not wrong, but probably not necessary in the LD since my guess is it won't ever be used for reasoning. The reason we had a lot of those differentia in the LDs was that we originally experimented with adding them and removing them for complete classification of the pathway wrt what else was in GO. We added and subtracted MFs and participants, ran the reasoner and then looked at the results. We tried to get the most streamlined LD that gave us full classification, but nothing incorrect. We anticipated the days when the functions would be formally defined and those could also be used.......... But I really don't think this kind of work is a priority any more.

**Comment by sjm41** [comment]
> It's not wrong, but probably not necessary in the LD since my guess is it won't ever be used for reasoning.

OK, it's now gone!

**Comment by sjm41** [comment]
@pgaudet Any chance you'd be able to take care of the final NAD-related tasks in the [comment above](https://github.com/geneontology/go-ontology/issues/29050#issuecomment-2640449029), if you agree with them?

**Comment by sjm41** [comment]
Hi @pgaudet Are you able to review/action the tasks in the [comment](the https://github.com/geneontology/go-ontology/issues/29050#issuecomment-2640449029) above? Happy to chat if we need to clarify anything. Thanks!

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

- GO:0034627 de novo' NAD biosynthetic process (1 direct EXP - moved down)  as an unnecessary grouping term
(Rossana: Probably this comes from the literature where de novo' NAD synthesis is used to group the Asp and Trp.)
and 
-  GO:0034356 NAD biosynthesis via nicotinamide riboside salvage pathway (7 direct EXP), since it's a single child of its parent term (we don't have separate terms for the other specific salvage pathways)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

GO:0006116	NADH oxidation
GO:0070995	NADPH oxidation

The reason for obsoletion is that these terms represent reactants in oxidation and reduction reactions. 
See https://github.com/geneontology/go-ontology/issues/29050

Annotations are here: https://docs.google.com/spreadsheets/d/1sm-72LgsOnezC8pzq4yAq9twDWQf910WjhwiLf4VK80/edit?gid=0#gid=0

There are 45 manual annotations to these terms: 

AgBase | 2 | DONE
-- | -- | --
BHF-UCL | 4 |  
CAFA | 3 |  
EcoCyc | 1 |  
FlyBase | 4 |  
MGI | 2 |  
RGD | 8 |  
SGD | 12 |  
TAIR | 1 |  
UniProt | 8 | DONE

The proposed action is to just remove annotations, as these are redundant with MF annotations. You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/29050

Thanks

Pascale

**Comment by lreiser** [comment]
removed TAIR annotation

**Comment by rozaru** [comment]
> From @pgaudet  – I am just wondering about NAD(P)H regeneration – some papers seem to mention this as a specific ‘purpose’ of some reactions, for example: [https://pubmed.ncbi.nlm.nih.gov/7628449/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpubmed.ncbi.nlm.nih.gov%2F7628449%2F&data=05%7C02%7Crz367%40universityofcambridgecloud.onmicrosoft.com%7Ca7900ecfd838409c04c108dd573f1338%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638762650633518050%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=EsR7z9nCvtug1YnBV13iSVQqknlO2V3yIwJTljBfquY%3D&reserved=0)

**NADH regeneration and NADPH regeneration**
Def: A metabolic process that generates a pool of NAD(P)H by the reduction of NAD(P)+.

The problem with this term is that it usually corresponds to a 1 step reaction and is often embedded in other metabolic processes such as the oxidative branch of the pentose phosphate (1st reaction), conversion of pyruvate into lactate etc..

NAD(P)H regeneration in organelles is a bit more complicated as NADH and NADPH cannot cross the membrane and often involves more than 1 reaction.

- In mitochondria, the regeneration is carried out by the glycerophosphate and malate/aspartate shuttles
- In the peroxisome, depending on the species,  it is carried out by the isocitrate/2-oxoglutarate shuttle (NADP) and malate-oxaloacetate shuttle (NAD).
In the section 2.4 of this[ reference](https://www.sciencedirect.com/science/article/pii/S0167488906002400?via%3Dihub) they discuss the shuttles that “regenerate” the pools of NAD and NADP in the preoxisome.

There is the possibility to keep the term to group the shuttles but as the current definition stands curators are likely going to annotate any enzyme that involves NAD(P)H -> NAD(P) with this term when mentioned in the context of NAD(P)H regeneration.

**Comment by pgaudet** [comment]
Thanks @rozaru 
I made a new issue for NADH regeneration and NADPH regeneration
https://github.com/geneontology/go-ontology/issues/29818

**Comment by sjm41** [comment]
I'm reviewing this ticket with the aim of trying to close it....

@ukemi You said previously that we should remove NAD(1-) as a primary input in the LD for canonical glycolysis, which was done - see https://github.com/geneontology/go-ontology/issues/29050#issuecomment-2640659970

But I see that we left NADH(2-) as a primary output in the LD - not sure if that was intentional or an oversight.
Anyway, would you advise we also remove that?


And I see the same questions apply to "sulphoglycolysis".
This currently has 'has participant' some 'NAD(1-)') and 'has primary output' some 'NADH(2-)'.
Would you advise these are also removed from this GO term?

Thanks.

**Comment by sjm41** [comment]
Hi @pgaudet 

Can we proceed with this point:
The "NADH metabolic process" (GO:0006734) grouping term is redundant with the "NAD+ metabolic process" (GO:0019674) term - so GO:0006734 should be obsoleted (or rather merged into GO:0019674).
Doing this will also then match how the NADP branch is already organised.


Current terms:

id: GO:0006734
name: NADH metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving reduced nicotinamide adenine dinucleotide (NADH), a coenzyme present in most living cells and derived from the B vitamin nicotinic acid." [GOC:jl, ISBN:0618254153]
synonym: "NAD (reduced) metabolic process" EXACT []
synonym: "NAD (reduced) metabolism" EXACT []
synonym: "NADH metabolism" EXACT []
synonym: "reduced NAD metabolic process" EXACT []
synonym: "reduced NAD metabolism" EXACT []
synonym: "reduced nicotinamide adenine dinucleotide metabolic process" EXACT []
synonym: "reduced nicotinamide adenine dinucleotide metabolism" EXACT []
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:57945 ! NADH(2-)


id: GO:0019674
name: NAD+ metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving nicotinamide adenine dinucleotide (NAD+), a coenzyme that interconverts with its reduced form, NADH, in many redox and catabolic reactions." [PMID:28648096]
synonym: "NAD (oxidized) metabolic process" EXACT []
synonym: "NAD (oxidized) metabolism" EXACT []
synonym: "NAD metabolic process" EXACT []
synonym: "NAD metabolism" EXACT []
synonym: "NAD phosphorylation and dephosphorylation" NARROW []
synonym: "nicotinamide adenine dinucleotide metabolic process" EXACT []
synonym: "nicotinamide adenine dinucleotide metabolism" EXACT []
synonym: "oxidized NAD metabolic process" EXACT []
synonym: "oxidized NAD metabolism" EXACT []
synonym: "oxidized nicotinamide adenine dinucleotide metabolic process" EXACT []
synonym: "oxidized nicotinamide adenine dinucleotide metabolism" EXACT []
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:57540 ! NAD(1-)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0006734 NADH metabolic process with replace by GO:0019674 NAD+ metabolic process. The reason for obsoletion is that these 2 terms are equivalent. 

There are 24 annotations to this term, and 1 extension, see https://github.com/geneontology/go-annotation/issues/5783


Impacted groups: 
Group | Number of annotations
-- | --
ComplexPortal | 4
FlyBase | 8
MGI | 1
ParkinsonsUK-UCL | 1
RGD | 6
SGD | 1
TAIR | 2
UniProt | 1

This term is not in any subset.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/29050

Thanks, Pascale
